### ISSUE TITLE
Bug: tfgen does not include descriptions for nested config fields

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-terraform-bridge#1045]
### What happened?

A [user reported missing examples for the Docker provider configuration](https://github.com/pulumi/pulumi-docker/issues/550) and [I noticed that even the descriptions were missing](https://www.pulumi.com/registry/packages/docker/api-docs/provider/#providerregistryauth).

After failing to create an upstream patch against an `index.md` file, I realized that unlike for Resources/Data Sources, for Provider.Config, we read descriptions (and only descriptions) from the [TF schema directly](https://github.com/kreuzwerker/terraform-provider-docker/blob/master/internal/provider/provider.go#L69).

The `Description` fields exist for the nested resource; we are just not consuming them.

### Expected Behavior

I expected nested schema descriptions to be read into the provider schema correctly.

### Steps to reproduce

1. Patch `upstream/internal/provider/provider.go` on the Docker provider - edit the description for `ca_material`, and edit the one for `registry_auth:address`
2. With the new patch in place, run `make tfgen`
3. Observe `caMaterial` having an updated description, while `registryAuth.Adddress` has no description at all.

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jazzyfresh** [comment]
Thanks for noticing this! Adding it to the broken docs epic https://github.com/pulumi/home/issues/2738
