### ISSUE TITLE
pulumi-docker.Container docs mention terraform

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-terraform-bridge#1048]
See https://www.pulumi.com/registry/packages/docker/api-docs/container/#memoryswap_csharp for details:
<img width="1029" alt="Screenshot 2023-04-26 at 3 00 36 PM" src="https://user-images.githubusercontent.com/22222529/234712623-f8795352-64df-433a-b108-e9d2eabfcf44.png">

We need to confirm that the bridge scrubs these mentions.

---

Downstream issues:
- https://github.com/pulumi/pulumi-snowflake/issues/287
- The originating issue was present in `pulumi-docker`, but didn't have its own issue filed.

**Comment by mjeffryes** [comment]
This is fixed now
