### ISSUE TITLE
Converting `terraform-aws-eks`: error: `no resource plugin 'pulumi-resource-time' found`

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-terraform-bridge#1058]
Error converting https://github.com/terraform-aws-modules/terraform-aws-eks:

After working around #1057:

```
$ pulumi convert --from terraform --language typescript --out pulumi
warning: Plugin converters are currently experimental
error: could not generate output program: load pcl program: no resource plugin 'pulumi-resource-time' found in the workspace or on your $PATH
```

We don't currently bridge the TF Time provider. Should we? Should we have a better error message for when there isn't a Pulumi bridged provider?

Can we still emit generated code when we don't have a provider available?

**Comment by justinvp** [comment]
Options:
1. Improve the error message. Try to find 3rd party provider that covers this.
2. Programgen should not be so strict about requiring exact types for things. If it can't find schema, assume what's given is correct and generate as best it can.

**Comment by justinvp** [comment]
Specifically for `pulumi convert`, I wonder if we should consider automatically downloading pulumiverse plugins? They are listed in the registry, after all. If we're uncomfortable with that for some reason, maybe check pulumiverse and prompt before installing, with a note that it's a 3rd party plugin?

**Comment by justinvp** [comment]
Hard code list for now until we have proper registry lookup

**Comment by Frassle** [comment]
Engine now hardcodes a list of well known pulumiverse plugins, we can extend this to covers others if needed.
