### ISSUE TITLE
limits link dropped?

### ISSUE THREAD

**Issue by ericrudder** [pulumi/pulumi-terraform-bridge#11]
File: [docs/reference/pkg/nodejs/pulumi/aws/lambda/_index.md](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/lambda/)

property timeout 
public timeout: pulumi.Output<number | undefined>;
The amount of time your Lambda Function has to run in seconds. Defaults to 3. See [Limits][5]

**Comment by ekrengel** [comment]
@stack72 are you working on this or should i take it on?
