### ISSUE TITLE
Doc generation meta-issue

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform-bridge#113]
We want to broadly improve the accuracy of our documentation generated for libraries built from this bridge.  This issue will track this overall improvement.  Currently - this includes at least:
* https://github.com/pulumi/pulumi-terraform-bridge/issues/15
* https://github.com/pulumi/pulumi-terraform-bridge/issues/11
* https://github.com/pulumi/pulumi-terraform-bridge/issues/52
* https://github.com/pulumi/pulumi-terraform-bridge/issues/80

The goal is that all overview and property (including nested property) documentation is included and is accurate.  We should ideally find a way to measure this level of completeness and accuracy, and ensure we can drive it to a high bar.

**Comment by stack72** [comment]
I believe that @justinvp suggested we use the same markdown parser as used on the docs site - gopkg.in/russross/blackfriday.v2

**Comment by leezen** [comment]
Tracked items are closed. Let's create any new ones as necessary as this issue is fairly unspecific.
