### ISSUE TITLE
Convert `terraform-azurerm-caf`: `no resource plugin 'pulumi-resource-azurerm'`

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-terraform-bridge#1130]
Error converting https://github.com/aztfmod/terraform-azurerm-caf:

```
pulumi convert --from terraform --language typescript --out pulumi
warning: Plugin converters are currently experimental
error: could not generate output program: failed to bind program: no resource plugin 'pulumi-resource-azurerm' found in the workspace or on your $PATH
```

**Comment by justinvp** [comment]
We previously discussed hard-coding a known set of TF providers that map to Pulumi providers, so that they can be automatically downloaded, to improve the experience.

**Comment by Frassle** [comment]
Should be fixed in the converter now. The converter can send hints of what pulumi plugin corresponds to a terraform provider.
