### ISSUE TITLE
Resolving doc errors

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-terraform-bridge#1141]
### What happened?

I am attempting to try out the auto token mapping.
I have configured the mapping like so:

```
err := x.ComputeDefaults(&prov, x.TokensMappedModules("harness_", mainMod,
		map[string]string{
			"platform":      "platform",
			"cloudprovider": "cloudprovider",
			"service":       "service",
		}, x.MakeStandardToken(mainPkg)))
	contract.AssertNoErrorf(err, "failed to compute default token mappings")
```

I then get an error:

```
error: failed to gather package metadata: problem gathering resources: 1 error occurred:
	* could not find docs for resource 'harness_platform_apikey'. Override the Docs property in the resource mapping. See type tfbridge.DocInfo for details.
```

If I was explicitly mapping the resource, I'd override the property. How do I resolve this with auto token mapping?

### Expected Behavior

I can build the provider

### Steps to reproduce

See above

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Injecting an override something like this before x.ComputeDefaults should fix the error/warning

```
	prov.Resources["harness_platform_apikey"] = &tfbridge.ResourceInfo{
		Docs: &tfbridge.DocInfo{
			Markdown: []byte(`Some docs here`),
		},
	}

```

Also note PULUMI_MISSING_DOCS_ERROR env var (false = warning, true = error) that controls the severity of the missing docs condition.

**Comment by iwahbe** [comment]
You can also add the following after `x.ComputeDefaults` is called:
```go
prov.Resources["harness_platform_apikey"].Docs = &tfbridge.DocInfo{
	Markdown: []byte(`Some docs here`),
}
```
