### ISSUE TITLE
Enable generating pyproject.toml files in order to publish Python wheels

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-terraform-bridge#1154]
The upstream Python SDK codegen will be updated to support generating a pyproject.toml and unblock publishing wheels. To support this, we'll track that issue:
- pulumi/pulumi#12805 

And we'll then need to implement a flag for tfgen to toggle generating a pyproject.toml, and updating ci-mgmt scripts or the provider publishing action to publish as a wheel.

**Comment by justinvp** [comment]
Just a note that when building from the `Makefile`, we currently use `sed` to inject the version into `setup.py`. For example: https://github.com/pulumi/pulumi-random/blob/4b9b45fe9587fd77d472700e16ae61194b965942/Makefile#L70

```
sed -i.bak -e 's/^VERSION = .*/VERSION = "$(PYPI_VERSION)"/g' -e 's/^PLUGIN_VERSION = .*/PLUGIN_VERSION = "$(VERSION)"/g' ./bin/setup.py
```

It looks like we'll have to do the same with the new `pyproject.toml` file.

**Comment by AaronFriel** [comment]
Yeah; if we were further along with `pulumi package publish-sdk` we would utilize that. 

To make sure we edit the right value, I've added a requested change here: https://github.com/pulumi/pulumi/pull/12805#discussion_r1204826600

**Comment by iwahbe** [comment]
@t0yv0 is this issue still relevant?

**Comment by t0yv0** [comment]
This is currently supported. Bridged providers such as pulumi-aws https://github.com/pulumi/pulumi-aws/blob/master/sdk/python/pyproject.toml mostly have Pyproject TOML enabled now. Here's an example of turning the flag on https://github.com/pulumi/pulumi-aws/pull/2813/files#diff-34c57e622183cb0d8dd0d3f9eaa0861b3340120e9b2ad811bac7ac7be4cea4b1R6893
