### ISSUE TITLE
Update Go to v1.20

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi-terraform-bridge#1167]
### What happened?

When trying to update a provider that uses this library, I ran into an error:
```
../../../../go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.9.2/internal/muxer/muxer.go:75:33: undefined: errors.Join
```

This is because https://github.com/pulumi/pulumi-terraform-bridge/blob/902e9d5f3c181c4a64079d06e2ae9adf0d474696/pf/internal/muxer/muxer.go#L75 uses the new `errors.Join` function which was introduced in Go v1.20. Any downstream projects that uses this function without compiling with Go v1.20 will error out.

We should update our go.mod files to indicate that v1.20 of Go should be used, since this breaks backwards compatibility with Go 1.19 and below.

### Expected Behavior

Build/compilation to be successful, or a warning message indicating that the Golang compiler is a different version to the one declared by this project's go.mod.

### Steps to reproduce

Use `tfgen.MainWithMuxer` on Golang v1.19.X or below. Eg. `make tfgen` in the pulumi-gcp providers repo.

### Output of `pulumi about`

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Thank you for filing! @t0yv0 could you take a look? 🙏
