### ISSUE TITLE
Promote experimental automations (token mapping, aliasing) to GA

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-terraform-bridge#1180]

**Comment by iwahbe** [comment]
While we make this change, we should change the signature of `AutoAliasing` from func `AutoAliasing(providerInfo *tfbridge.ProviderInfo, artifact tfbridge.ProviderMetadata) error` to `AutoAliasing(providerInfo *tfbridge.ProviderInfo)`. This is always called with `artifact = providerInfo.GetMetadata()`, so there is no need for the extra parameter.

**Comment by iwahbe** [comment]
Before we refactor our provider fleet, we should also add `Must*` variations of `ComputeDefaults` and `AutoAliasing`, since AFAIK we never handle the returned error, we just assert on it.
