### ISSUE TITLE
`ComputeDefaults` and `AutoAliasing` don't work on pure PF providers

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-terraform-bridge#1197]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

`ComputeDefaults` and `AutoAliasing` both work by examining `tfbridge.ProviderInfo.P` (`.P`). This works for sdk-v2 providers because `.P` holds the provider (and thus all its schema information). This also works for muxed providers since `MainWithMuxer` expects a value for `.P` with a correct schema (and `pfbridge.MuxShimWithPF` providers one).

Pure PF based providers leave `.P` empty, so `ComputeDefaults` fails.

### Affected area/feature

I believe we should fold this change in with removing `pf/tfbridge.ProviderInfo` by embedding `pf/tfbridge.ProviderInfo.NewProvider` into the `.P`. Either way, we need a schema-correct value to stick in `.P`.

**Comment by t0yv0** [comment]
Possibly fixed with https://github.com/pulumi/pulumi-terraform-bridge/issues/1210
