### ISSUE TITLE
terraform-provider-vantage blocked on numeric ID support

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1198]
### What happened?

@jaxxstorm reports an issue blocking terraform-provider-vantage. Similarly to https://github.com/pulumi/pulumi-terraform-bridge/issues/352 the bridge assumes ID field is a string so when TF defines a numeric ID the system runs into problems. Unlike the pkg/v3 bridge, PF is also more strict by default so workarounds to pretend the ID is a string do not apply. We need to make sure this scenario works naturally:

https://github.com/vantage-sh/terraform-provider-vantage/blob/main/vantage/aws_provider_resource.go#L25

### Expected Behavior

users can bridge providers with resources defining the "ID" fields as numbers.

### Steps to reproduce

See above.

### Output of `pulumi about`

N/A

### Additional context

pf/v0.11.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Related: https://github.com/pulumi/pulumi-terraform-bridge/issues/352

**Comment by guineveresaenger** [comment]
Just ran into this for pulumi-dnsimple as well.
