### ISSUE TITLE
Terraform bridge fails when updated to Pulumi v3.70.0

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-terraform-bridge#1215]
This looks like a breaking change in the Mapping interface, as this call on line 53 requires a third parameter:

https://github.com/pulumi/pulumi-terraform-bridge/blob/7bc9e16218c726269dbf8bdacd7f24eefd4a320a/pkg/tf2pulumi/il/plugin_info.go#L50-L53

**Comment by muhlba91** [comment]
this seems to work for me now with the newest bridge release (`v3.50.1`)
