### ISSUE TITLE
Add place to hold examples in schema

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi-terraform-bridge#122]
In the “old way” of generating docs, the examples are included as a doc comments on the resource class. We should have a way to inject examples into the docs that are generated using the new schema.

**Comment by pgavlin** [comment]
IMO we should keep the examples embedded in the doc comments, but should spec out how exactly they're represented.

**Comment by praneetloke** [comment]
The other thing, if we do still keep them in the doc comments, which I can see as being useful if you are looking at the resource in your IDE, is we would want to update the current API doc generator to hide those examples. That's because, the new resource doc would already have the examples and showing the same ones again in the language-specific API doc would be redundant on the website, at least.
