### ISSUE TITLE
Allow migrating resources to Plugin Framework

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1244]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Provide functionality to migrate a given bridged resource to Plugin Framework. We may want to try migrating resources ahead of the upstream migration schedule if doing so resolves known issues. Specifically issues with Diff handling are of interest and may be fixed by migrating:

https://github.com/pulumi/pulumi-aws/issues?q=is%3Aopen+is%3Aissue+label%3Abug%2Fdiff (currently 11 issues)

Implementation may use:

https://pkg.go.dev/github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5to6server

**Comment by t0yv0** [comment]
Looking at this more closely, this unfortunately is a lot more difficult than it seemed and we can't make immediate progress.

The key problem is that the functionality to automatically promote a SDKv2 resource to Plugin Framework interfaces is working at the level of gRPC:

[func UpgradeServer(_ context.Context, v5server func() tfprotov5.ProviderServer) (tfprotov6.ProviderServer, error)](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5to6server#UpgradeServer)

But there are no primitives in the bridge to convert tfprotov6.ProviderServer to Pulumi; instead PF support is accepting a provider from github.com/hashicorp/terraform-plugin-framework/provider package.

So the pre-requisite would be to support bridging gRPC-level providers like tfprotov6.ProviderServer to Pulumi.

**Comment by t0yv0** [comment]
@mjeffryes @iwahbe did your prototype unlock new possibilities here?

**Comment by iwahbe** [comment]
I believe that our prototype is directionally correct, but didn't get far enough to fully prove this out. I believe that migrating resources won't be fully backwards, but it could be close enough to fix specific resources.

**Comment by iwahbe** [comment]
I'd be very surprised if this will fix issues. We should prioritize fixing bugs in SDKv2 vs attempting to upgrade providers preemptily.
