### ISSUE TITLE
Consider simplifying Diff implementation for legacy provider interface

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform-bridge#1245]
From #1243:

> This code serves two purposes:
> 
> * implementing ignoreChanges feature
> * computing DetailedDiff
> From digging around earlier, it appeared that DetailedDiff is an optional feature, and if let unimplemented, the engine computes and displays an adequate diff anyway including for nested values. Based on this, Plugin Framework providers still leave it as unimplemented. It this accurate or there is some functionality that's DetailedDiff here is needed for?
> 
> As to ignoreChanges, after some debate in https://github.com/pulumi/pulumi-terraform-bridge/issues/920 the PF implementation settled on a Pulumi-level-only implementation that would not need to look inside the TF Diffs. That implementation seems to be more closely aligned with the feature docs.
> 
> So, the pathway to delete this code is to (1) drop DetailedDiff and (2) switch out ignoreChanges to the different implementation. Given the risks it probably makes more sense to keep maintaining it.
> 
> Another phaseout strategy for diff-related issues we discussed with @friel was https://github.com/pulumi/pulumi-terraform-bridge/issues/1244 - essentially given that we believe upstream resources will be migrating to PF eventually, we want to have an option to try to artificially accelerate this process for individual resources or entire providers as means of fixing diff-related bugs including this one.

Using this new issue to track deciding whether we want to make changes to align these and simplify the implementation for the legacy bridge to match.

**Comment by VenelinMartinov** [comment]
This sounds like it will not work for GCP: https://github.com/pulumi/pulumi-gcp/issues/1275

GCP has a `defaultLabels` property on the provider which allows applying labels to all resources. TF takes this into account when diffing and correctly produces a diff but a pulumi-only implementation would miss this.

I don't see a decent way of injecting this information at the pulumi level, so we likely need to maintain our own detailed diff.

I'm interested how PF GCP resources act with default labels given the lack of detailed diff there - I'll open an issue to test our behaviour there.

**Comment by VenelinMartinov** [comment]
Actually I think https://github.com/pulumi/pulumi-terraform-bridge/issues/752 already supersedes this - @t0yv0 can we close this issue? Seems like we should rather likely implement DetailedDiff for PF instead.

**Comment by t0yv0** [comment]
Yes the 752 has more detail on a possible way forward.
