### ISSUE TITLE
Property error404Document breaks the program

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-terraform-bridge#127]
The property named `error404Document` is incorrectly translated to the terraform name `error404_document` while the actual name is `error_404_document` [docs](https://www.terraform.io/docs/providers/azurerm/r/storage_account.html#error_404_document).

```
error: azure:storage/account:Account resource 'websitesa' has a problem:
static_website.0: invalid or unknown key: error404_document
```

I guess we can override the property in the provider definition, but maybe let's first check if there is a fix in the bridge.

Repro program:
```ts
import * as azure from "@pulumi/azure";
import * as pulumi from "@pulumi/pulumi";

// Create an Azure Resource Group
const resourceGroup = new azure.core.ResourceGroup("website-rg", {
    location: azure.Locations.WestUS,
});

// Create a Storage Account for our static website
const storageAccount = new azure.storage.Account("websitesa", {
    resourceGroupName: resourceGroup.name,
    accountReplicationType: "LRS",
    accountTier: "Standard",
    accountKind: "StorageV2",
    staticWebsite: {
        indexDocument: "index.html",
        error404Document: "404.html",
    },
});
```

Packages:
```json
{
    "name": "azure-ts-static-website",
    "devDependencies": {
        "@types/node": "^8.0.0"
    },
    "dependencies": {
        "@pulumi/pulumi": "^1.0.0",
        "@pulumi/azure": "^2.0.0"
    }
}
```

**Comment by gertjvr** [comment]
Looking at the code could we use something like https://github.com/iancoleman/strcase/blob/master/snake.go#L33 to solve the issue?

**Comment by mikhailshilkov** [comment]
@leezen This is a nasty issue, I think we should prioritize it

**Comment by lukehoban** [comment]
I think for now we should just fix this directly in the Azure provider - see https://github.com/pulumi/pulumi-azure/pull/555.  It's not immediately clear that we can have a single built-in algorithm for mapping names that gets 100% of names correct in both directions - I believe there are inconsistent naming patterns used in snake_casing in upstream providers, such that we will always have to add overrides to the default logic for some subset of properties.  For now, I think it is safer to fix any known cases of this (`error_404_document` is the only one I'm aware of).

**Comment by gertjvr** [comment]
Think this issue can also be closed now.
