### ISSUE TITLE
Schema codegen is non-deterministic

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-terraform-bridge#129]
@stack72 appied the latest bridge, including the schema-based generation, to `pulumi-azure`. However, the build fails due to changes in the generated schema **and** generated python files.

See [this PR](https://github.com/pulumi/pulumi-azure/pull/486) but also easily reproducible locally. Every time we run `make` there's a new set of differences in python files.

Examples of diff:

```
git diff sdk/python/pulumi_azure/appservice/app_service.py
diff --git a/sdk/python/pulumi_azure/appservice/app_service.py b/sdk/python/pulumi_azure/appservice/app_service.py
index c8559b2f..cfb8bc73 100644
--- a/sdk/python/pulumi_azure/appservice/app_service.py
+++ b/sdk/python/pulumi_azure/appservice/app_service.py
@@ -22,10 +22,10 @@ class AppService(pulumi.CustomResource):
     """
     A `auth_settings` block as defined below.
 
-      * `activeDirectory` (`dict`)
+      * `active_directory` (`dict`)
         * `allowedAudiences` (`list`)
         * `client_id` (`str`)
-        * `clientSecret` (`str`)
+        * `client_secret` (`str`)
 
       * `additionalLoginParams` (`dict`)
       * `allowedExternalRedirectUrls` (`list`)
@@ -33,18 +33,18 @@ class AppService(pulumi.CustomResource):
       * `enabled` (`bool`) - Is the App Service Enabled?
       * `facebook` (`dict`)
         * `app_id` (`str`)
-        * `appSecret` (`str`)
+        * `app_secret` (`str`)
         * `oauthScopes` (`list`)
 
       * `google` (`dict`)
         * `client_id` (`str`)
-        * `clientSecret` (`str`)
+        * `client_secret` (`str`)
         * `oauthScopes` (`list`)
```

The schema is stable for me after the first run, but then my result is different from Paul's and from CI's. It's harder to tell the exact diff, but I see something like this:

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/1454008/76409905-5a9e0500-638f-11ea-973e-301d1ab806b4.png">

**Comment by pgavlin** [comment]
I swear I fixed this. I'll see if I can repro locally.

**Comment by pgavlin** [comment]
> The schema is stable for me after the first run, but then my result is different from Paul's and from CI's. It's harder to tell the exact diff, but I see something like this:

This is probably due to a different version of `tf2pulumi` on your local machine than in CI. If I run with v0.6.0, I can't repro this piece.

**Comment by lukehoban** [comment]
From #4056:

> Note that this is not quite a complete fix for the linked issue: it does not fix the instability in the version that is embedded in the schema. It does fix the Python codegen, though.

So leaving this open to track instability in the version in the schema.

**Comment by mikhailshilkov** [comment]
FWIW, I had to exclude `generate_schema` command from `build` and only run it manually locally for the currently updated providers. So yes, we still need to do something here.

**Comment by mikhailshilkov** [comment]
Removing P1 as the initial urgency went away. Do we still want to re-include the `generate_schema` step to `build`?

**Comment by stack72** [comment]
@mikhailshilkov I am going to close this out - we no longer check in the generated files and we have added the generate_schema as part of the build
