### ISSUE TITLE
User unable to bridge a provider thanks to r.tf.SchemaMap undefined

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1302]
### What happened?

```
$make tfgen
[ -x /opt/homebrew/bin/pulumi ] || curl -fsSL https://get.pulumi.com/ | sh
pulumi plugin install resource random 4.3.1
(cd provider && go build -o /Users/gsuess/SemDatex/pulumi/harvester/bin/pulumi-tfgen-harvester -ldflags "-X github.com/semdatex/pulumi-harvester/provider/pkg/version.Version=0.0.1-alpha.1688662856+041f43bc.dirty" github.com/semdatex/pulumi-harvester/provider/cmd/pulumi-tfgen-harvester)
# github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2
../../../../go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.54.1/pkg/tfshim/sdk-v2/resource.go:24:26: r.tf.SchemaMap undefined (type *schema.Resource has no field or method SchemaMap)
../../../../go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.54.1/pkg/tfshim/sdk-v2/resource.go:90:67: r.tf.SchemaMap undefined (type *schema.Resource has no field or method SchemaMap)
../../../../go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.54.1/pkg/tfshim/sdk-v2/resource.go:91:22: r.tf.SchemaMap undefined (type *schema.Resource has no field or method SchemaMap)
../../../../go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.54.1/pkg/tfshim/sdk-v2/schema.go:137:23: e.SchemaMap undefined (type *schema.Resource has no field or method SchemaMap)
make: *** [tfgen] Error 1
```

https://github.com/harvester/terraform-provider-harvester

### Expected Behavior

Build success

### Steps to reproduce

See above

### Output of `pulumi about`

N/A

### Additional context

Is this related to the bridge using a customized fork -replace of V2 SDK? Can we fix this?

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by benlongo** [comment]
Seeing the same thing trying to make a bridge for https://github.com/SquadcastHub/terraform-provider-squadcast

**Comment by benlongo** [comment]
did those links get mangled by markdown formatting?

**Comment by t0yv0** [comment]
Yes, apologies. Basically the replace from https://github.com/pulumi/pulumi-terraform-bridge/blob/master/go.mod#L6

**Comment by t0yv0** [comment]
```
github.com/hashicorp/terraform-plugin-sdk/v2 => github.com/pulumi/terraform-plugin-sdk/v2 v2.0.0-20230710100801-03a71d0fca3d
```

**Comment by benlongo** [comment]
On a more general note, how do I find a list of the versions for `github.com/pulumi/terraform-plugin-sdk/v2`? I'm very new to go so this replace magic is still a bit confusing to me and I don't fully understand the versioning relationship between `github.com/hashicorp/terraform-plugin-sdk/v2` and `github.com/pulumi/terraform-plugin-sdk/v2`
