### ISSUE TITLE
[Muxer] De-duplicate identical error messages in CheckConfigure

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-terraform-bridge#1418]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The muxer de-duplicates identical CheckConfig's `plugin.CheckFailure`, but doesn't do anything with pure go `error`s. It should compare the error messages `reflect.Equal` or `err1.Error() == err2.Error()` and discard one error if they are the same. This avoids duplicate errors showing up in muxed providers.

See https://github.com/pulumi/pulumi-aws/issues/2285#issuecomment-1750343750 for details.

**Comment by VenelinMartinov** [comment]
Is there some other failure case which triggers identical errors? With https://github.com/pulumi/pulumi-aws/issues/2285#issuecomment-1750343750 the errors raised are not actually identical. The RequestIDs are different:

```
Errors: {
               &errors.errorString{s:"unable to validate AWS credentials. \nDetails: No valid credential sources found. Please see https://www.pulumi.com/registry/packages/aws/installation-configuration/\nfor more information about providing credentials.\n\nError: failed to refresh cached credentials, refresh cached SSO token failed, unable to refresh SSO token, operation error SSO OIDC: CreateToken, https response error StatusCode: 400, RequestID: 3c6b0f80-596c-4afb-aed3-5075972c86d7, InvalidGrantException: \n\nMake sure you have set your AWS region, e.g. `pulumi config set aws:region us-west-2`. \n"},
               &errors.errorString{s:"unable to validate AWS credentials. \nDetails: No valid credential sources found. Please see https://www.pulumi.com/registry/packages/aws/installation-configuration/\nfor more information about providing credentials.\n\nError: failed to refresh cached credentials, refresh cached SSO token failed, unable to refresh SSO token, operation error SSO OIDC: CreateToken, https response error StatusCode: 400, RequestID: d410e929-950d-4eeb-ad5e-2c2903e0fc9a, InvalidGrantException: \n\nMake sure you have set your AWS region, e.g. `pulumi config set aws:region us-west-2`. \n"},
           }
```

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-gcp/issues/129 related still open.
