### ISSUE TITLE
Provider configuration errors use TF (i.e. wrong) attribute names 

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-terraform-bridge#1424]
### What happened?

If `pulumi up` or `pulumi preview` is run without sufficient provider configuration, the user gets this error message:

```text
cloudflare:index:WorkerScript (hello-world-script):
    error: must provide one of "api_key", "api_token" or "api_user_service_key".: must provide one of "api_key", "api_token" or "api_user_service_key".
```

This is incorrect. They should be, e.g. `cloudflare:apiKey`.

### Example

n/a - any old CloudFlare example will work (or maybe any that uses the `WorkerScript` resource).

### Output of `pulumi about`

```text
CLI          
Version      3.86.1-dev.0
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME        VERSION
cloudflare  5.12.0
nodejs      unknown

Host     
OS       darwin
Version  14.0
Arch     arm64

This project is written in nodejs: executable='/Users/jkodroff/.nvm/versions/node/v20.8.0/bin/node' version='v20.8.0'

Current Stack: jkodrofftest/cloudflare-tutorial/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jkodroff
User           jkodroff
Organizations  jkodroff, oracle-workshop, jkodrofftest, aws-partnership, zephyr, demo, pulumi
Token type     personal

Dependencies:
NAME                VERSION
@pulumi/cloudflare  5.12.0
@pulumi/pulumi      3.87.0
@types/node         18.18.4
typescript          4.9.5

Pulumi locates its logs in /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Somewhat related: https://github.com/pulumi/pulumi-terraform-bridge/issues/199

**Comment by t0yv0** [comment]
See https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfbridge/check_failures.go

**Comment by t0yv0** [comment]
In fact this appears to be covered already by `if reasonType == MissingKey {` - can we make sure first it reproduces on cloudflare built against the latest bridge, and if it does, why the error detection fails to kick in? Thanks a  ton!

**Comment by t0yv0** [comment]
Ah I see, perhaps check-failures is only scanning provider-level config properties but missing resource properties are still not handled. It would be great to get this in!

**Comment by VenelinMartinov** [comment]
For the cloudflare problem it seems like the terraform schema is lacking the validation of the config that it requires exactly on of the 3 keys. That's we we error on this during `Configure` instead of `CheckConfig`.

I manually added it upstream but the error is slightly wrong again:
```
error: pulumi:providers:cloudflare resource 'default_5_13_0' has a problem: could not validate provider configuration: Invalid Attribute Combination. No attribute specified when one (and only one) of [api_token,api_user_service_key,api_key] is required. Check `pulumi config get cloudflare:apiKey`.
```
I think we don't have a match for this type of error in `check_failures.go`.

Given that the alternative requires an upstream change, I'll go for running a string replacement on the error message we get in `Configure`.

**Comment by VenelinMartinov** [comment]
Kind of related: https://github.com/pulumi/pulumi-aws/issues/3028
