### ISSUE TITLE
Bug: tfgen does not include descriptions for resources with ReplaceExamplesSection = true

### ISSUE THREAD

**Issue by ocobles** [pulumi/pulumi-terraform-bridge#1497]
### What happened?

in Equinix's provider, we are replacing the tf examples with the option
https://github.com/pulumi/pulumi-terraform-bridge/blob/b83370c2fe7eaf28a5d7741fc52dcd31d4abde49/pkg/tfbridge/info.go#L306

I noticed that now the resources don't have their description in the registry, just the examples. I don't know how the rendering works in the registry site, but checking other providers I see that the difference in `schema.json` is that in the resource `description` field, the description goes before the tag `{{% examples %}}`.

It seems this is happening because of https://github.com/pulumi/pulumi-terraform-bridge/blob/b83370c2fe7eaf28a5d7741fc52dcd31d4abde49/pkg/tfgen/docs.go#L1272-L1278

### Example

- Resource:
https://github.com/equinix/pulumi-equinix/blob/ba8962c48cd99f3ffa0c108a785506280cf92443/provider/resources.go#L137-L139

- Examples file:
https://github.com/equinix/pulumi-equinix/blob/ba8962c48cd99f3ffa0c108a785506280cf92443/docs/resource/equinix_fabric_connection.examples.md

- Generated schema:
https://github.com/equinix/pulumi-equinix/blob/ba8962c48cd99f3ffa0c108a785506280cf92443/provider/cmd/pulumi-resource-equinix/schema.json#L9851

- Registry:
https://www.pulumi.com/registry/packages/equinix/api-docs/fabric/connection/

Here's another example without a description in AWS classic provider:

- https://www.pulumi.com/registry/packages/aws/api-docs/acm/certificatevalidation/
- https://github.com/pulumi/pulumi-aws/blob/master/docs/resource/aws_acm_certificate_validation.examples.md

### Output of `pulumi about`

CLI          
Version      3.89.0
Go Version   go1.21.1
Go Compiler  gc

Host     
OS       darwin
Version  13.6
Arch     x86_64

### Additional context

If that's the case, I would expect something like

```
if strings.Contains(docs, "```typescript") || strings.Contains(docs, "```python") ||
		strings.Contains(docs, "```go") || strings.Contains(docs, "```yaml") ||
		strings.Contains(docs, "```csharp") || strings.Contains(docs, "```java") {
		// we have explicitly rewritten these examples and need to just return them directly rather than trying
		// to reconvert them. But we need to surround them in the examples shortcode for rendering on the registry

		// Find the index of "## Example Usage"
		exampleIndex := strings.Index(docs, "## Example Usage")

		// Build the new description
		newDescription := fmt.Sprintf("%s\n\n{{%% examples %%}}\n%s\n{{%% /examples %%}}",
			docs[:exampleIndex],
			docs[exampleIndex:])

		return newDescription
	}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@ocobles Yes, I think your analysis is right here. Any chance you are in a position to open a PR to fix this?

**Comment by ocobles** [comment]
Of course, happy to contribute :)
