### ISSUE TITLE
clusterType values not listed

### ISSUE THREAD

**Issue by brucemackenzie** [pulumi/pulumi-terraform-bridge#1507]
File: [themes/default/content/registry/packages/mongodbatlas/api-docs/cluster/_index.md](https://www.pulumi.com/registry/packages/mongodbatlas/api-docs/cluster/)

Looking in the src code I found these values possible for `clusterType`:
`REPLICASET`, `GEOSHARDED`, `SHARDED`

**Comment by iwahbe** [comment]
Yep, this is a bug in our docs parsing code. Thanks for reporting it.

**Comment by guineveresaenger** [comment]
I believe this is, if not a duplicate, then at least related to https://github.com/pulumi/pulumi-terraform-bridge/issues/1358.

**Comment by guineveresaenger** [comment]
Update: We can in fact fix this by more strictly parsing potential properties as presenting in `snake_case` only. 

#1969 will not address situations such as #1358, since in that case we're seeing only lowercase values.
