### ISSUE TITLE
No logs recorded from the upstream provider even when TF_LOG=trace is set

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1536]
### What happened?

At some point the codebase lost the ability to capture and show logs originating from the TF provider internals, specifically for SDKv2 based providers. As a result, diagnosing issues with bridged providers such as pulumi-aws is exceedingly difficult, as following https://www.pulumi.com/docs/support/troubleshooting/ instructions is not adding any information requested by `TF_LOG=TRACE` and the logs customers share with us are not easy to act on.

```
TF_LOG=TRACE pulumi up --logtostderr --logflow -v=10 2> out.txt
```

### Example

To reproduce, modify SDKv2 code to guarantee a log message, for example this:

```
func (r *Resource) SimpleDiff(
	ctx context.Context,
	s *terraform.InstanceState,
	c *terraform.ResourceConfig,
	meta interface{}) (*terraform.InstanceDiff, error) {

	logging.HelperSchemaError(ctx, "#### SimpleDiff")
```

Rebuild a bridged provider such as pulumi-aws against this modified SDKv2. Run a pulumi up on a sample program, with flags as per troubleshooting page (TF_LOG=trace). 

Observe that the error level TF log message is not captured by Pulumi or emitted in the logs at all.

### Output of `pulumi about`

Affects bridge v3.65.0 and aws v6.9.0.

### Additional context

The root cause here seems that at some point the SDKv2 framework moved from emitting messages via built-in "log" package from Go stdlib to using 	"github.com/hashicorp/terraform-plugin-log/tfsdklog", the same underlying library as Plugin Framework based providers use. This change invalidates the use of  logging interceptors based on "log" for the purposes of capturing TF logs. 

There is prior art in this codebase of integrating with tfsdklog that was built to capture logs coming from Plugin Framework based providers:

https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pf/internal/logging/recover_keys.go#L65

Perhaps with a little refactoring this machinery can be adapted to capture SDKv2 based logs as well.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
This sounds pretty bad, we should probably find time to diagnose and fix this.

**Comment by t0yv0** [comment]
Yeah this is blocking our customer investigation so definitely including it in the iteration. I'm going to self-assign for now but happy to delegate. @iwahbe what we just talked about.  @VenelinMartinov  if you're interested.

**Comment by VenelinMartinov** [comment]
I'd be happy to take a stab at this if it isn't blocking your current work.

**Comment by iwahbe** [comment]
@t0yv0 As I understand, this is blocking your ability to get good debug info for https://github.com/pulumi/pulumi-aws/issues/2987. @VenelinMartinov Please prioritize this issue so we can get https://github.com/pulumi/pulumi-aws/issues/2987 fixed ASAP.

**Comment by t0yv0** [comment]
We chatted with @VenelinMartinov and agreed I'll tackle this for now since it's on the critical path to P1.

**Comment by t0yv0** [comment]
Unfortunately having to reopen this issue per https://github.com/pulumi/pulumi-terraform-bridge/commit/a0d01d3f8bcd0872c68b89a6ba73871b0cb6ddce 

The original implementation caused downstream check failure in pulumi-gcp and pulumi-azure tests broken.

https://github.com/pulumi/pulumi-azure/issues/1479

In GCP TestAccLoadbalancer started failing, easy to reproduce locally. 

We should fix this before shipping the changes.
