### ISSUE TITLE
Property sections included in resource description

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform-bridge#159]
On for example https://www.pulumi.com/docs/reference/pkg/aws/emr/cluster/, many of the property descriptions are getting included in the resource summary section.

**Comment by ekrengel** [comment]
Is this what youre talking about? 

![image](https://user-images.githubusercontent.com/8304499/79511217-b3e2ff00-7ff3-11ea-8a4d-8ca22cad6882.png)

I am working on something related per https://github.com/pulumi/docs/issues/2919

**Comment by ekrengel** [comment]
This looks slightly different to what I was solving for, but in same realm. Will add a test case and see if I can fix this as well .

**Comment by ekrengel** [comment]
Oh this is what you mean: 
![image](https://user-images.githubusercontent.com/8304499/79512214-d8d87180-7ff5-11ea-82a9-b9987ad2371e.png)

nvm unrelated to my issue!

**Comment by lukehoban** [comment]
I was specifically calling out sections like https://www.pulumi.com/docs/reference/pkg/aws/emr/cluster/#core-instance-group-configuration-block which I believe should not be included in the resource level description.
