### ISSUE TITLE
Refresh pollutes state for programs that use Assets and Archives

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1595]
### What happened?

When using assets and archives, as common for lambas in AWS for example, refresh wipes out the asset/archive information from the state and replaces it with machine-local references. This is inherently dangerous if multiple boxes are used to perform `pulumi` operations against a shared statefile. 

### Example

The motivating example is a highly upvoted issue in pulumi-aws:

https://github.com/pulumi/pulumi/issues/6235

https://github.com/pulumi/pulumi-aws/issues/3185 even more minimal repro is here. 

### Output of `pulumi about`

See above.

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Seeing lots of incidences in azure tests as well. Any time azure:storage/blob:Blob is used, in particular when used with overlays that automatically provision functions like this one:

```typescript
export const subscription = topic.onEvent("test", async (context, arg) => {
```

**Comment by iwahbe** [comment]
I've added this bug to the planning sheet for next iteration.
