### ISSUE TITLE
Deprecate testing/x in favour of the module in providertest

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#1604]
### What happened?

We should deprecate https://github.com/pulumi/pulumi-terraform-bridge/tree/master/testing/x as it now lives in https://github.com/pulumi/providertest/tree/main/replay

We should merge the recent changes from tf-bridge there and have tf-bridge tests use providertest instead.

### Example

.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Sounds good to me. FYI Go linters supports module level deprecations:

https://github.com/pulumi/pulumi-terraform-bridge/blob/2bb619413b2cca3d6acec58c76acb25dbb844fcb/pkg/tfbridge/x/package.go#L1-L10
