### ISSUE TITLE
Talos provider fails to build on latest bridge with type conflict

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1626]
### What happened?

From @ringods :

 I updated my Talos package to use the latest tf-bridge commit. I want to start testing the muxer that Thomas Meckel contributed. My go.mod changes:
    github.com/pulumi/pulumi-terraform-bridge/pf v0.23.1-0.20240111163851-bda33f369ae3
	github.com/pulumi/pulumi-terraform-bridge/v3 v3.70.1-0.20240111163851-bda33f369ae3

But my provider doesn't build anymore:
error: failed to create Pulumi schema: talos:machine/generated/MachineSecretsSecrets:MachineSecretsSecrets: conflicting type definitions

The error is introduced in https://github.com/pulumi/pulumi-terraform-bridge/pull/1550 but does not seem to give sufficient guidance how to resolve the type collision. 

### Example

See above

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Confirmed with a minified repro https://github.com/pulumi/pulumi-terraform-bridge/pull/1550 broke simple ExtraTypes examples that unfortunately were untested in this codebase. Let me look at reverting it.

**Comment by t0yv0** [comment]
Looks like per https://github.com/pulumi/pulumi-terraform-bridge/pull/1628#issuecomment-1899167921 there might be an additional error in the new version of OCI that might have a similar but slightly different root cause CC @iwahbe

**Comment by iwahbe** [comment]
@t0yv0 Can you post the minified repro?

**Comment by t0yv0** [comment]
It's in a PR.

**Comment by iwahbe** [comment]
This was fixed by reverting https://github.com/pulumi/pulumi-terraform-bridge/pull/1628.
