### ISSUE TITLE
Do not generate schema and convert examples over and over for each language

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1636]
Currently standard makefiles have a `make tfgen` target and `make build_nodejs` target (focusing on Node but there is one for every language). Unfortunately the work of converting and building TF examples is not shared but is duplicated across these targets. This slows down CI runs but also can be surprising in development where `make build_nodejs` executes side-effects associated with example conversion but that is not expected (such as emitting warnings or editing replacements.json file in AWS).

Previous attempt to fix this up broke so had to be reverted:
https://github.com/pulumi/pulumi-terraform-bridge/pull/1457

The key issue is one level up at the Makefile level: we are not passing the schema and examples generated at `make tfgen` phase to the individual `make build_nodejs` phase.  Currently `make build_nodejs` invokes the tfgen binary like this:

```
/Users/t0yv0/code/pulumi-random/bin/pulumi-tfgen-random nodejs --out sdk/nodejs/
```
But perhaps it could invoke it like this instead:

```
/Users/t0yv0/code/pulumi-random/bin/pulumi-tfgen-random nodejs --out sdk/nodejs/ --schema path/to/schema.json
```

In which case it could use a prebuilt schema from `make tfgen` instead of rebuilding it from scratch.

**Comment by t0yv0** [comment]
This is fixed I think with examples cache. CC @iwahbe @mjeffryes 

https://github.com/pulumi/pulumi-terraform-bridge/pull/1793

**Comment by t0yv0** [comment]
We still generate schema over and over, but it turns out that schema generation applies target-language-variant regex replaces that result in different output, it's really something that could be factored out but it's "fast enough." Caching examples delivered most of the benefit for iteration speed here.

**Comment by iwahbe** [comment]
I'm happy to close based on that. The problem we were facing is speed, and if caching solves the problem then I'm happy.
