### ISSUE TITLE
Tracking: timeout-related issues

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1652]
Opening a tracking list to not lose this in G-docs, although it is not entirely clear all these issues originate in the bridge. They do skew to bridged-providers though.

- p/p [Custom Timeouts ignored for ASG in Python (maybe other resources and/or languages) #12987](https://github.com/pulumi/pulumi/issues/12987)
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1651

### awsx

- [autoscaling - custom timeouts are not propagated to child resources #530](https://github.com/pulumi/pulumi-awsx/issues/530)

- [Fargate service updating failing with timeout #354](https://github.com/pulumi/pulumi-awsx/issues/354) (The actual failure is a different issue but custom timeouts had no effect)

### aws
- [customTimeouts not honored for ecs.Service #1336](https://github.com/pulumi/pulumi-aws/issues/1336) (Closed but I’m not sure that’s correct)
- aws [NodeGroup set with customTimeout on update to 4h hits a timeout error of 20m #3442](https://github.com/pulumi/pulumi-aws/issues/3442)

### eks
eks [Custom timeouts are not propagated to child resources #393](https://github.com/pulumi/pulumi-eks/issues/393)

**Comment by t0yv0** [comment]
@thomas11 thanks for the original list

**Comment by DominicRoyStang** [comment]
@t0yv0 Not listed in the issues above, but I'm using `{ customTimeouts: { delete: '2m' } }` on an `aws.ec2.SecurityGroup`, and it still takes 20 minutes to destroy (doesn't time out).

Additional context: this is used in an attempt to deal with this terraform issue that also affects Pulumi: https://github.com/hashicorp/terraform-provider-aws/issues/265

In my case, it's a security group for a Lambda in a VPC.

**Comment by t0yv0** [comment]
Could you please file in pulumi/pulumi-aws with a repro @DominicRoyStang that could help us a whole lot to prioritize!

**Comment by DominicRoyStang** [comment]
Here you go: https://github.com/pulumi/pulumi-aws/issues/4382

Repro repo: https://github.com/DominicRoyStang/pulumi-delete-timeout-bug-report

**Comment by t0yv0** [comment]
Closing - the issues in this list had very different root causes after all. We've been able to fix some of them.
