### ISSUE TITLE
Tag person who started bridge upgrade on failures

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#1670]
### What happened?

Looks like @t0yv0 always gets tagged on bridge upgrade failures, even when he didn't participate.

### Example

https://github.com/pulumi/pulumi-hcloud/pull/401
I kicked that off

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
@VenelinMartinov Should I assign this to you?
