### ISSUE TITLE
Master is broken for use in providers

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-terraform-bridge#169]
Using the current version of the `pulumi-terraform-bridge` master branch causes large differences in the providers' generated code and actually breaks it.

Example of the build: https://github.com/pulumi/pulumi-terraform-bridge/runs/606506435?check_suite_focus=true

An example of a change in AWS:

```diff
@@ -198,7 +198,7 @@ namespace Pulumi.Aws.CloudHsmV2
         /// The state of the cluster.
         /// </summary>
         [Input("clusterState")]
-        public Input<string>? State { get; set; }
+        public Input<string>? ClusterState { get; set; }
 
         /// <summary>
         /// The type of HSM module in the cluster. Currently, only hsm1.medium is supported.
```

**Comment by lukehoban** [comment]
Was this perhaps related to https://github.com/pulumi/pulumi/pull/4454?

**Comment by mikhailshilkov** [comment]
@lukehoban Yes, probably. Some guessing here: https://github.com/pulumi/pulumi/pull/4468

**Comment by stack72** [comment]
@mikhailshilkov I believe you have fixed this now - going to close this as we get no breaking changes in the diff
