### ISSUE TITLE
Remove examples from "description" field

### ISSUE THREAD

**Issue by sean1588** [pulumi/pulumi-terraform-bridge#1714]
We want to have more control over content ordering when we render on the page. The resource description, code examples, and import section are all part of the "description" field in the schema. Could we consider removing the examples section out of the description and perhaps move it to its own dedicated field in the schema. This would give us more flexibility to move the examples to a specific section of the page when we render.

**Comment by iwahbe** [comment]
Right now we are actually moving in the opposite direction. Upstream docs don't always have a clearly delineated examples section. We get the best results when we assume as little structure about upstream as possible.

If the schema adds support for an examples section, I don't think we want to do anything more complicated then look for an `## Examples` header and move everything under it from `description` to `examples`.

@sean1588 I would start this effort by opening an issue in pulumi/pulumi to add `"examples"` as a section to the schema format. There we would need to nail down what codegen should do with examples, if anything and what format it has.

**Comment by sean1588** [comment]
Thanks @iwahbe. Ok sounds good. This sounds similar to what is being suggested in this [issue] 
 (https://github.com/pulumi/docs/pull/10898) in the pulumi/pulumi repo. I'll close this one in favor of that one.

**Comment by iwahbe** [comment]
> Thanks @iwahbe. Ok sounds good. This sounds similar to what is being suggested in this [issue](https://github.com/pulumi/docs/pull/10898) in the pulumi/pulumi repo. I'll close this one in favor of that one.

I think you linked the wrong issue here :)
