### ISSUE TITLE
Automate PF dependency and tag push for bridge releases

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#1723]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

As part of bridge releases we currently do need to update the pf->bridge dependency and push a new pf tag.
We could automate that. That will allow us to automate the whole bridge release once we also have https://github.com/pulumi/pulumi-terraform-bridge/issues/1721

**Comment by t0yv0** [comment]
How about removing the go module instead?

**Comment by VenelinMartinov** [comment]
Yeah that seems quite sensible but I don't really have an idea of how many users would be affected.

Also is there a way to go through a deprecation step? Have pf in both places for a while and deprecate the separate pf module?

**Comment by t0yv0** [comment]
Yes, definitely, it would be possible. We'd owe a detailed note on the migration path to our users. I think we need to think through this a bit further on second thought and we don't need to block automation on that... After all dependency segregation afforded by the pf/go.mod is a bit of a benefit that might get more important over time.  We also might need to work out how to limit bridged providers runtime dependencies on pulumi/pulumi packages that are not needed.
