### ISSUE TITLE
Drop examples containing `NotImplemented` calls

### ISSUE THREAD

**Issue by sean1588** [pulumi/pulumi-terraform-bridge#1732]
Following the rollout of the new converter we are now generating some new examples that were not being emitted previously. This is overall great, but some of the new examples contain `NotImplemented` calls in them. In the short term we should drop these examples until they can be addressed, so these examples do not get rendered on the site.

page example: https://www.pulumi.com/registry/packages/aws/api-docs/ecs/service/#redeploy-service-on-every-apply

**Comment by t0yv0** [comment]
copying https://github.com/pulumi/pulumi/issues/15589 as I've been putting my updates there.
