### ISSUE TITLE
Getting undefined schema error

### ISSUE THREAD

**Issue by thulasirajkomminar** [pulumi/pulumi-terraform-bridge#1739]
### What happened?

Trying to bridge a terraform provider with the latest version but when running `tfgen` command I’m getting the below error.
```

# github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen
../../../../go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.76.0/pkg/tfgen/main.go:37:2: undefined: schema
make: *** [tfgen] Error 1
```

If I comment that particular line from my downloaded package I do not get this error.

### Example

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @thulasirajkomminar. Do you have this `replace` in your `go.mod`?

```
replace github.com/hashicorp/terraform-plugin-sdk/v2 => github.com/pulumi/terraform-plugin-sdk/v2 v2.0.0-20240202163305-e2a20ae13ef9
```

**Comment by thulasirajkomminar** [comment]
> Hi @thulasirajkomminar. Do you have this `replace` in your `go.mod`?
> 
> ```
> replace github.com/hashicorp/terraform-plugin-sdk/v2 => github.com/pulumi/terraform-plugin-sdk/v2 v2.0.0-20240202163305-e2a20ae13ef9
> ```

The terraform provider uses `github.com/hashicorp/terraform-plugin-framework` so shouldn't it be that?

**Comment by thulasirajkomminar** [comment]
@iwahbe I tried to run `tfgen` on this module `https://github.com/pulumi/pulumi-tls `but get the same error.

**Comment by thulasirajkomminar** [comment]
NVM It works in a different macbook.
