### ISSUE TITLE
TFGen undefined: schema.RunProviderInternalValidation

### ISSUE THREAD

**Issue by muhlba91** [pulumi/pulumi-terraform-bridge#1752]
### What happened?

When updating to the bridge `v.77.0` (i get the same error starting from `v.74.0`) I receive the following error:
`Error: ../../../../go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.77.0/pkg/tfgen/main.go:38:9: undefined: schema.RunProviderInternalValidation`

### Example

Provider: https://github.com/muhlba91/pulumi-proxmoxve/tree/renovate/github.com-pulumi-pulumi-terraform-bridge-v3-3.x
GitHub Actions run: https://github.com/muhlba91/pulumi-proxmoxve/actions/runs/8244384348/job/22546524894#step:6:245

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by muhlba91** [comment]
thank you! i have not realized this version was updated and still had an older one.

**Comment by VenelinMartinov** [comment]
@muhlba91 you might want to look into using https://github.com/pulumi/upgrade-provider for upgrading your provider - it handles these replaces as part of the flow.

Here is an example of how we use it in pulumi-aws: https://github.com/pulumi/pulumi-aws/blob/master/.github/workflows/upgrade-bridge.yml
