### ISSUE TITLE
terraform-provider-aws changed bool to string for some schema properties

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-terraform-bridge#176]
This is essentially a braking change for our users - this is due to Terraform wanting to have a nullable type that doesn't pass any default option to the AWS API when a user doesn't specify a value

We need a way to be able to deal with this in Pulumi and to maybe detect when this happens

**Comment by lukehoban** [comment]
If we override the type in our layer to be "bool", does it work?  In particular (a) does the case of passing `true`/`false` work and (b) does the case of it being undefined correctly map to the undefined value instead of to `false`?

**Comment by stack72** [comment]
So I overrode the schema as follows:

```
"aws_launch_template": {
				Tok: awsDataSource(ec2Mod, "getLaunchTemplate"),
				Fields: map[string]*tfbridge.SchemaInfo{
					"network_interfaces": {
						Elem: &tfbridge.SchemaInfo{
							Fields: map[string]*tfbridge.SchemaInfo{
								"associate_public_ip_address": {
									Type: "boolean",
								},
							},
						},
					},
				},
			},
```

When I run pulumi up to get the output, it still comes back as a string it seems:

```
          {
                "urn": "urn:pulumi:dev::launchtempalte::pulumi:pulumi:Stack::launchtempalte-dev",
                "custom": false,
                "type": "pulumi:pulumi:Stack",
                "outputs": {
                    "x": {
                        "associatePublicIpAddress": "true",
                        "deleteOnTermination": false,
                        "description": "",
                        "deviceIndex": 0,
                        "ipv4AddressCount": 0,
                        "ipv4Addresses": [],
                        "ipv6AddressCount": 0,
                        "ipv6Addresses": [],
                        "networkInterfaceId": "",
                        "privateIpAddress": "",
                        "securityGroups": [],
                        "subnetId": ""
                    }
                }
            },
```

even though the type is boolean...

```
interface GetLaunchTemplateNetworkInterface {
        associatePublicIpAddress: boolean;
        deleteOnTermination: boolean;
        /**
         * Description of the launch template.
         */
        description: string;
        deviceIndex: number;
        ipv4AddressCount: number;
        ipv4Addresses: string[];
        ipv6AddressCount: number;
        ipv6Addresses: string[];
        networkInterfaceId: string;
        privateIpAddress: string;
        securityGroups: string[];
        subnetId: string;
    }
```

**Comment by lukehoban** [comment]
> When I run pulumi up to get the output, it still comes back as a string it seems

Hmm - that's a little surprising - we have `CoerceTerraformString` in the bridge that looks like it should handle this specific case.  It's possible/likely it isn't honoring overrides in the SchemaInfo?  I think a fairly targeted fix there would likely solve this.

But I assume your comment also means that it *did* work to pass a boolean value in?  Which means there is no change needed on the inputs side, as Terraform just internally handles the coercions?
