### ISSUE TITLE
Bridge should handle SchemaConfigModeAttr block attributes

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#1762]
### What happened?

During the work on https://github.com/pulumi/pulumi-terraform-bridge/pull/1725 I stumbled upon a panic in pulumi-azure: https://github.com/pulumi/pulumi-terraform-bridge/pull/1725#issuecomment-2000133252

TF SDK providers seem to have a special backwards-compatibility mode which allows specific resources to opt-in to a behaviour where they can distinguish between nil and empty collections - https://developer.hashicorp.com/terraform/plugin/sdkv2/guides/terraform-0.12-compatibility#computed-resource-attributes

This is not handled anywhere in the bridge and I suspect is the root cause for https://github.com/pulumi/pulumi-azure/issues/1881 and the panic in https://github.com/pulumi/pulumi-terraform-bridge/pull/1725#issuecomment-2000133252

### Example

```typescript
const resourceGroup = new azure.core.ResourceGroup("test", {location: "westus2"});

const namespace = new eventhub.EventHubNamespace("test", {
    resourceGroupName: resourceGroup.name,
    sku: "Standard",
    networkRulesets: {
         defaultAction: "Allow",
         ipRules: [{
             action: "Allow",
             ipMask: "0.0.0.0/0",
         }],
     },
});
```

### Output of `pulumi about`

tested with azure 5.69 which uses 3.77 of the bridge

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Really hard to make progress here without sufficient tests. This would be easier with https://github.com/pulumi/pulumi-terraform-bridge/issues/1766 but it'd still need some work as TF JSON syntax might have limitations related to this issue: https://developer.hashicorp.com/terraform/language/attr-as-blocks#in-json-syntax

**Comment by t0yv0** [comment]
Can you try to specify a test a long the lines of 

https://github.com/pulumi/pulumi-terraform-bridge/issues/1736

This should be doable but needs a little bit of thinking.

We can maybe check that ConfigureFunc receives the exact same data under Pulumi and TF over a range of auto-generated schemes with SchemaConfigModeAttr variability, and that it emits similar warnings - though comparing emitted warnings can get a bit gnarly and need some massaging.

**Comment by t0yv0** [comment]
I'd like to pair early next week to have a look together. This is going to be interesting.
