### ISSUE TITLE
Framework for comparing bridged provider inputs with TF against pulumi

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#1764]
### What happened?

During https://github.com/pulumi/pulumi-terraform-bridge/pull/1725 it became quite obvious that I couldn't possibly make such changes without extensive testing against TF behaviour.

The work there also exposed some further discrepancies between the bridge and TF: https://github.com/pulumi/pulumi-terraform-bridge/issues/1762. Such a framework would make addressing that issue easier too.

Such a framework would have made the work on https://github.com/pulumi/pulumi-terraform-bridge/issues/1546 easier. It'd also help following up on some further possible discrepancies related to that: https://github.com/pulumi/pulumi-terraform-bridge/issues/1763

Possibly already being addressed by https://github.com/pulumi/pulumi-terraform-bridge/pull/1728 but I'd like to dump a wish-list here so we can better discuss the exact needs.

### Example

Here is the wish-list. I'd like an ~easy way to write a TF provider with custom assertions on the input bag inside each of the provider methods (`Validate`, `Diff`, `Apply`, config methods).

This would allow us to write tests with various resource schemas to assert that the bridge matches TF in the way it transforms inputs and passes them to the TF provider.

Something like:

```golang
myResource := &pluginsdk.Resource{
    Schema: map[string]*pluginsdk.Schema{
        ...,
        "network_rulesets": {
		Type:       pluginsdk.TypeList,
		Optional:   true,
		MaxItems:   1,
		Computed:   true,
		ConfigMode: pluginsdk.SchemaConfigModeAttr,
		Elem: &pluginsdk.Resource{
			Schema: map[string]*pluginsdk.Schema{
				"default_action": {
					Type:     pluginsdk.TypeString,
					Required: true,
					ValidateFunc: validation.StringInSlice([]string{
						string(networkrulesets.DefaultActionAllow),
						string(networkrulesets.DefaultActionDeny),
					}, false),
				},
         },
    Create: func (...) { require.Contains(resBag, "my_prop") },
    Update: func (...) {require.Equals(resBag["prop_1", "exact_value"},
}


func TestMyResource(t *testing.T) {
  TFInputs := ...
  pulumiInputs := ...
  err := framework.RunTFRes(t, myResource, TFInputs)
  assert.NoError(err)
  framework.RunPulumiRes(t, myResource, pulumiInputs)
  assert.NoError(err)
}
```

Maybe something like this? Or perhaps we could record the TF inputs and compare the whole thing to the pulumi ones?

We'd likely need it for the reverse way too.

Automatically converting the TF program to a pulumi one seems like an option extra to me - this framework would be extremely useful without that bit too.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Also one thing which I found related to https://github.com/pulumi/pulumi-terraform-bridge/pull/1728 which might be interesting is that the JSON TF syntax might not be fully equivalent to the HCL one: https://developer.hashicorp.com/terraform/language/attr-as-blocks#in-json-syntax

This seems to be a case where HCL can express some configuration while JSON can't.

**Comment by VenelinMartinov** [comment]
Closed with https://github.com/pulumi/pulumi-terraform-bridge/pull/1728

**Comment by t0yv0** [comment]
Marking as dup, I think there's another ticket for the same work. Thanks!
