### ISSUE TITLE
Tracking cross-test related tickets

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1766]
Work related to making it easy to compare the behavior of a TF provider under TF proper and the behavior of the same provider in bridged form when run under Pulumi.

- https://github.com/pulumi/pulumi-terraform-bridge/issues/1764
- https://github.com/pulumi/pulumi-terraform-bridge/pull/1728
- Cross-tests for Check
  - https://github.com/pulumi/pulumi-terraform-bridge/issues/1763
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1282
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1762
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1736
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1791
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1792

**Comment by VenelinMartinov** [comment]
Opened https://github.com/pulumi/pulumi-terraform-bridge/issues/1792 for testing our input transformations
