### ISSUE TITLE
Some property descriptions missing from nested type fields

### ISSUE THREAD

**Issue by sean1588** [pulumi/pulumi-terraform-bridge#1774]
We have descriptions missing in some nested type fields. I'm not sure the reasoning and can't really find a pattern for when this occurs that's obvious, but here is an example on the lambda page. 

https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/#functionsnapstart (optimizationStatus missing)
https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/#functionvpcconfig (vpcId missing)

**Comment by guineveresaenger** [comment]
Looking at the pattern here:

These are [Attribute types upstream](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#attribute-reference), meaning they map to Outputs on our end.

But the two examples you quoted are Attributes of subtypes (as evidenced by the `.` in their name) and somehow they're (probably erroneously) being mapped as Inputs. Unsure why descriptions are blank, but if you look at the [Pulumi Outputs section](https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/#outputs) you will see that `optimization_status` is there, untranslated to Pulumi type conventions and as a dangling bullet point in an unrelated field.

Not sure if this is two bugs or one but the likely desired state here is 
1. these fields should not be Inputs at all 
2. The Output documentation should respect bullet points and list nested Outputs.

**Comment by guineveresaenger** [comment]
Update:

The bug where we erroneously tack on an extra bullet point that's really the description for another field is a straightforward fix - it's a regex adjustment.

<img width="709" alt="Screenshot 2024-03-26 at 10 45 57 AM" src="https://github.com/pulumi/pulumi-terraform-bridge/assets/13116240/26ed474a-d7c4-410a-af1e-3e1f5eab25ca">

But the bigger issue is that I do not think we crawl the schema correctly for nested Output descriptions. Nested Output values are possibly rare (?) and upstream flattens them. We do not, and lose them somewhere along the way.

**Comment by guineveresaenger** [comment]
Here is a draft PR that addresses some of this:
https://github.com/pulumi/pulumi-terraform-bridge/pull/1798

**Comment by sean1588** [comment]
thanks so much @guineveresaenger 💜 !
