### ISSUE TITLE
Props with underscores in `ExtraTypes` not translated correctly to camelCase in C# and Typescript

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-terraform-bridge#1786]
### What happened?

For the Talos package, I replace a JSON string property with nested types defined in `ExtraTypes`. Some of the types have property names with an underscore. In the generated C# and Typescript SDKs, these properties are not converted to the usual camel cased property names.

## an ExtraType in resources.go

https://github.com/pulumiverse/pulumi-talos/blob/366f84ccb283fffd12278d52d27765cdfdd8e25f/provider/resources.go#L112-L121

## generated C# code

https://github.com/pulumiverse/pulumi-talos/blob/366f84ccb283fffd12278d52d27765cdfdd8e25f/sdk/dotnet/Machine/Inputs/SecretsArgs.cs#L19-L49
https://github.com/pulumiverse/pulumi-talos/blob/366f84ccb283fffd12278d52d27765cdfdd8e25f/sdk/dotnet/Machine/Outputs/SecretsResult.cs#L20-L27

## generated Typescript code

https://github.com/pulumiverse/pulumi-talos/blob/366f84ccb283fffd12278d52d27765cdfdd8e25f/sdk/nodejs/types/input.ts#L425-L434
https://github.com/pulumiverse/pulumi-talos/blob/366f84ccb283fffd12278d52d27765cdfdd8e25f/sdk/nodejs/types/output.ts#L292-L301

### Output of `pulumi about`

N/A. All build dependencies can be seen in https://github.com/pulumiverse/pulumi-talos

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @ringods. The `ExtraTypes` field in `ProviderInfo` is injected directly into the generated Pulumi schema, which means that the type names need to be in Pulumi's capitalization system (camelCase) for word breaks to be detected.

In your case, that means changing `bootstrap_token` to `bootstrapToken`, `secretbox_encryption_secret` to `secretboxEncryptionSecret`, `k8s_aggregator` to `k8sAggregator`, ect.

**Comment by ringods** [comment]
@iwahbe thanks for the feedback. I thought I had to use the Terraform property names.

**Comment by iwahbe** [comment]
> @iwahbe thanks for the feedback. I thought I had to use the Terraform property names.

You do for `Resources` (tf domain), but `ExtraResources`, `ExtraTypes`, etc are in the pulumi domain. I've made that mistake too.

**Comment by ringods** [comment]
> You do for `Resources` (tf domain), but `ExtraResources`, `ExtraTypes`, etc are in the pulumi domain. I've made that mistake too.

Can you add this to the docs somewhere?

**Comment by ringods** [comment]
If you would like from a Markdown file to these sources, I think so.
