### ISSUE TITLE
Cross-testing for Inputs

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#1792]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
We've had quite a few discrepancies in the way we transform pulumi inputs to terraform inputs. It'd be nice to have some exhaustive cross-testing of the transformations here.

Especially relevant is the stuff around `MaxItemsOne` - quite a few issues there.

We should also consider transitions around `MaxItemsOne` - removed, added etc. - we've seen some issues there before and likely more lurking.

https://github.com/pulumi/pulumi-terraform-bridge/issues/1229
https://github.com/pulumi/pulumi-terraform-bridge/issues/1546
https://github.com/pulumi/pulumi-terraform-bridge/issues/1767
https://github.com/pulumi/pulumi-terraform-bridge/issues/1762
and more probably

**Comment by VenelinMartinov** [comment]
The tests can take roughly this shape: https://github.com/pulumi/pulumi-terraform-bridge/pull/1784/files#diff-433bc136b7d15900d3779d4a443fb325e1f0480a946c221265465ed67fcdfd8e

We run some action (Create, Update, Delete, etc.), and save the inputs received by the provider method and then compare them between pulumi and TF.

It'd be amazing if we have a way to generate a matrix for testing, like suggested in https://github.com/pulumi/pulumi-terraform-bridge/issues/1790

**Comment by mjeffryes** [comment]
how does this differ from https://github.com/pulumi/pulumi-terraform-bridge/issues/1764?

**Comment by VenelinMartinov** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/issues/1764 is essentially closed by https://github.com/pulumi/pulumi-terraform-bridge/pull/1728

I opened it as a wish-list of what should be possible for the framework, before Anton explained his PR. We had a chat after and he's addressed most of my points in https://github.com/pulumi/pulumi-terraform-bridge/pull/1728

**Comment by t0yv0** [comment]
I've filed a few more tickets today I'm sorry we need to dedup here. But I actually quite like this one.

The rapid generator and extended diff tests in aren't passing yet (finding counter-examples):
https://github.com/pulumi/pulumi-terraform-bridge/pull/1801

But to get diff to pass the first thing that needs to pass is Create conformance. If we can't get create right then obviously the diff on the subsequent pulumi up will be working off a problem already. So I like the idea of being absolutely certain that the following theorem holds.

For every possible schema s and value v, CreateContextFunc receives exact same value under TF CLI as under Pulumi and the bridged provider.

I'm expecting that chasing create conformance will uncover a few interesting missing cases for regular input tests to the https://github.com/pulumi/pulumi-terraform-bridge/pull/1853 tests matrix. But testing MakeTerraformInputs leaves important details out that CreateConextFunc-level testing will catch, namely how TF CLI computes the Plan and how RawPlan, RawConfig are passed down (once we get to updates, it also covers RawState, but for creates RawState==null).
