### ISSUE TITLE
upgrade-provider takes too long for AWS

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#1807]
### What happened?

https://github.com/pulumi/pulumi-aws/actions/runs/8480468929/job/23236242070

When running downstream tests, the `upgrade-provider` action took 1 hour 15 minutes for AWS. This is almost as much as the next slowest provider took for `upgrade-provider` + build + test.

This significantly slows down the iteration speed with downstream tests as well as bridge upgrades.

It'd be great if we can identify where we are spending this time and speed it up a bit.

### Example

.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
I'd close as won't fix TBH. It almost always fails for AWS, there's almost every single time inevitable patch conflicts or some tweaking needed; we do it manually for now and the ask bottoms out at speeding up AWS builds which is non-trivial. Unless someone sees a quick win I think we might just live with it and try to async this processing as much as possible.

**Comment by VenelinMartinov** [comment]
This really was for the bridge upgrade - due to us blocking on downstream tests, this significantly slows down bridge releases.
This usually does not require manual fixes and I feel like there must be some quick wins we can get here.

**Comment by t0yv0** [comment]
The low-hanging fruit is mostly picked in AWS builds I'm afraid.

**Comment by VenelinMartinov** [comment]
Okay, happy to close this then.

**Comment by t0yv0** [comment]
I think at some point we can have a test suite that's quite confident here we can drop AWS out of downstream checks. After all the checks still run before we release AWS. We can work this out

**Comment by t0yv0** [comment]
Not planned for now. upgrade-provider almost always fails in AWS but we ship updates manually. Until a better time..
