### ISSUE TITLE
Downstream check script does not check for errors in upgrade-provider action

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#1816]
### What happened?

After running downstream checks we then make sure that all providers succeed with the new bridge.

This can fail if the upgrade-provider action fails - we no longer raise p1s for this and the `downstream_check` script does not take that into account.

In this case it is benign but it could potentially cause us to miss downstream issues, especially if they are in tfgen.

### Example

https://github.com/pulumi/pulumi-vault/actions/runs/8480681653/job/23236832051

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
`ci-mgmt` keeps a list of providers that should have a status at https://raw.githubusercontent.com/pulumi/ci-mgmt/master/provider-ci/providers.json. We should download that list and check that each listed item has a status (or print MISSING) if not.

**Comment by VenelinMartinov** [comment]
tfgen errors always hit this - I just hit it: https://github.com/pulumi/pulumi-aws/actions/runs/8648259460/job/23711655817
