### ISSUE TITLE
Ensure InternalValidate is called at build time

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1852]
### What happened?

Schemas for sdk-v2 based providers are subject to InternalValidate that rejects invalid schemas. We would like to assume that a schema that the bridge needs to handle passes the validation so we do not need to support degenerate combinations. To make this safe, ensure that bridge providers run this validation at build-time and reject non-conforming schemas.

### Example

https://github.com/pulumi/terraform-plugin-sdk/blob/4f60ee4e2975c25b88b392e69c87551bb0e26dfc/helper/schema/provider.go#L225
https://github.com/pulumi/pulumi-terraform-bridge/blob/cffb5535b798ea08661ffdc2b865cfced207133f/pkg/tfbridge/provider.go#L567
https://github.com/pulumi/pulumi-terraform-bridge/blob/cffb5535b798ea08661ffdc2b865cfced207133f/pkg/tfbridge/provider.go#L465
https://github.com/pulumi/pulumi-terraform-bridge/blob/cffb5535b798ea08661ffdc2b865cfced207133f/pkg/tfgen/main.go#L38

Looks like tfgen does call schema.RunProviderInternalValidation = true which is good but need to also make sure that tfgen executes provider.Validate which in turn executes InternalValidate, as we were not sure.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Note also that the referenced links validate SchemaMap for the provider configuration only! However, the schemas we are interested in as well (or mostly) are SchemaMap declarations for resources and datasources. We need to make sure that if there are any errors in those they are detected at build time.

**Comment by VenelinMartinov** [comment]
Note that the provider `InternalValidate` in turn calls `InternalValidate` on all resources and datasources:

https://github.com/pulumi/terraform-plugin-sdk/blob/e2a20ae13ef98738ebac0566e9ed25f570226e0a/helper/schema/provider.go#L146

https://github.com/pulumi/terraform-plugin-sdk/blob/e2a20ae13ef98738ebac0566e9ed25f570226e0a/helper/schema/provider.go#L146

**Comment by VenelinMartinov** [comment]
Unfortunately I think we've regressed here in https://github.com/pulumi/pulumi-terraform-bridge/pull/1669

I injected a panic in the InternalValidate method in the plugin-sdk but running `make tfgen` in pulumi-aws linked against that plugin-sdk did not yield any errors.

I'll address this next.

**Comment by t0yv0** [comment]
Yeah perhaps some e2e test to hold this in place can help. Thank you!
