### ISSUE TITLE
Bug: ignore invalid hcl or terraform blocks

### ISSUE THREAD

**Issue by tmeckel** [pulumi/pulumi-terraform-bridge#1890]
### What happened?

The [vatesfr xenorchestra Terrform provider](https://raw.githubusercontent.com/vatesfr/terraform-provider-xenorchestra/master/docs/resources/vm.md) is using markdown code blocks which do not contain Terraform (HCL) code and thus cause warnings while creating code examples out of the resource definition.

![image](https://github.com/pulumi/pulumi-converter-terraform/assets/14177833/39603ac0-4906-46a6-9af9-8b2de54fdcd3)

```shell
warning: unable to convert HCL example for Pulumi entity '#/resources/xenorchestra:index/vm:Vm'. The example will be dropped from any generated docs or SDKs: 1 error occurred:
        * [csharp, go, java, python, typescript, yaml] :3,11-12: Invalid character; This character is not used within the language., and 5 other diagnostic(s)
```

`jq '.|select(.ExampleName=="#/resources/xenorchestra:index/vm:Vm")' cov/byExample.json`

```json
{
  "ExampleName": "#/resources/xenorchestra:index/vm:Vm",
  "OriginalHCL": "# cloud_config.tftpl file used by the cloudinit templating.\n\n#cloud-config\nhostname: ${hostname}\nfqdn: ${hostname}.${domain}\npackage_upgrade: true\n",
  "ConversionResults": {
    "csharp": {
      "FailureSeverity": 2,
      "FailureInfo": "Invalid character: This character is not used within the language.; Argument or block definition required: An argument or block definition is required here. To set an argument, use the equals sign \"=\" to introduce the argument value.",
      "Program": "",
      "TranslationCount": 1
    },
    "go": {
      "FailureSeverity": 2,
      "FailureInfo": "Invalid character: This character is not used within the language.; Argument or block definition required: An argument or block definition is required here. To set an argument, use the equals sign \"=\" to introduce the argument value.",
      "Program": "",
      "TranslationCount": 1
    },
    "java": {
      "FailureSeverity": 2,
      "FailureInfo": "Invalid character: This character is not used within the language.; Argument or block definition required: An argument or block definition is required here. To set an argument, use the equals sign \"=\" to introduce the argument value.",
      "Program": "",
      "TranslationCount": 1
    },
    "python": {
      "FailureSeverity": 2,
      "FailureInfo": "Invalid character: This character is not used within the language.; Argument or block definition required: An argument or block definition is required here. To set an argument, use the equals sign \"=\" to introduce the argument value.",
      "Program": "",
      "TranslationCount": 1
    },
    "typescript": {
      "FailureSeverity": 2,
      "FailureInfo": "Invalid character: This character is not used within the language.; Argument or block definition required: An argument or block definition is required here. To set an argument, use the equals sign \"=\" to introduce the argument value.",
      "Program": "",
      "TranslationCount": 1
    },
    "yaml": {
      "FailureSeverity": 2,
      "FailureInfo": "Invalid character: This character is not used within the language.; Argument or block definition required: An argument or block definition is required here. To set an argument, use the equals sign \"=\" to introduce the argument value.",
      "Program": "",
      "TranslationCount": 1
    }
  }
}
```

### Example

```terraform
# cloud_config.tftpl file used by the cloudinit templating.

#cloud-config
hostname: ${hostname}
fqdn: ${hostname}.${domain}
package_upgrade: true
```

```hcl
# Content of the terraform files
data "xenorchestra_pool" "pool" {
    name_label = "pool name"
}

data "xenorchestra_template" "template" {
    name_label = "Puppet agent - Bionic 18.04 - 1"
}

data "xenorchestra_network" "net" {
  name_label = "Pool-wide network associated with eth0"
}

resource "xenorchestra_cloud_config" "bar" {
  name = "cloud config name"
  # Template the cloudinit if needed
  template = templatefile("cloud_config.tftpl", {
    hostname = "your-hostname"
    domain = "your.domain.com"
  })
}

resource "xenorchestra_vm" "bar" {
    memory_max = 1073733632
    cpus  = 1
    cloud_config = xenorchestra_cloud_config.bar.template
    name_label = "Name"
    name_description = "description"
    template = data.xenorchestra_template.template.id

    # Prefer to run the VM on the primary pool instance
    affinity_host = data.xenorchestra_pool.pool.master
    network {
      network_id = data.xenorchestra_network.net.id
    }

    disk {
      sr_id = "7f469400-4a2b-5624-cf62-61e522e50ea1"
      name_label = "Ubuntu Bionic Beaver 18.04_imavo"
      size = 32212254720
    }

    tags = [
      "Ubuntu",
      "Bionic",
    ]

    // Override the default create timeout from 5 mins to 20.
    timeouts {
      create = "20m"
    }

    // Note: Xen Orchestra populates values within Xenstore and will need ignored via
    // lifecycle ignore_changes or modeled in your terraform code
    xenstore = {
      key1 = "val1"
      key2 = "val2"
    }
}

# vm resource that waits until its first network interface
# is assigned an IP via DHCP
resource "xenorchestra_vm" "vm" {
  ...
  # Specify VM with two network interfaces
  network {
    ...
    expected_ip_cidr = "10.0.0.0/16"
  }
  network {
    ...
  }
}

output "first-network-interface-ips" {
  value = xenorchestra_vm.vm.network[0].ipv4_addresses
}
```

### Output of `pulumi about`

CLI          
Version      3.109.0
Go Version   go1.22.0
Go Compiler  gc

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com
User           Unknown
Organizations  
Token type     personal

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @tmeckel. Thanks for reporting this to us. The bridge treats \`\`\`terraform exactly like \`\`\`hcl, as do many terraform providers. For example (from the [AWS docs](https://github.com/hashicorp/terraform-provider-aws/blob/797d38d66c80e23b37e2034b57b64aff2dbdd38a/website/docs/index.html.markdown#L25-L44)):

```md
```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {
  region = "us-east-1"
}

# Create a VPC
resource "aws_vpc" "example" {
  cidr_block = "10.0.0.0/16"
}
```

I don't think we can change this behavior without regressing in other providers. You can look into [DocsRules](https://github.com/pulumi/pulumi-terraform-bridge/blob/94c1de4f7880017730eda9d4613895ad52b07ca9/pkg/tfbridge/info/info.go#L119-L120) to patch upstream but I'm not sure what we can do in the bridge.

**Comment by tmeckel** [comment]
@iwahbe As I said in the discussion about the affected Terraform provider, I jumped to conclusions about what happened too quickly and opened this issue here. In the end, it turned out that all the issues can and must be fixed in the upstream Terraform provider, and so I debated with myself to close this issue anyway.

However, in this particular situation, the problems with the upstream docs could be easily fixed because the upstream Terraform provider and the wrapping Pulumi provider are controlled by the same entity. This is often not the case. @t0yv0 mentioned that he has some regular expressions that could be valuable in this situation, as they could filter out illegal HCL code. Still, the potential side effects need to be carefully observed.

**Comment by t0yv0** [comment]
Yeah when the code block is unlabelled (three backticks, no language), we now use a regex heuristic to decide if it's TF or not. This could be extended to blocks that are labelled. That being said, it's not unreasonable to emit a warning either. What's missing is warning class codes like `pubr-invalid-hcl` that the provider author could put in an ignore file similar to a linter config, if they do not want to go ahead and patch the examples to fix the warning.
