### ISSUE TITLE
not enough arguments in call to GeneratePackage

### ISSUE THREAD

**Issue by belfhi** [pulumi/pulumi-terraform-bridge#1897]
### What happened?

Since Pulumi `v3.113.3`, the `GeneratePackage` function was changed by @Frassle 
If the current version of pulumi is used with 

### Example

Building a provider with pulumi
```
require (
    github.com/pulumi/pulumi-terraform-bridge/v3 v3.80.0
    github.com/pulumi/pulumi/sdk/v3 v3.113.3
```
gives:
```
$ golangci-lint run --path-prefix=provider
WARN [config_reader] The configuration option `run.skip-files` is deprecated, please use `issues.exclude-files`.
provider/cmd/pulumi-tfgen-xenorchestra/main.go:18:2: could not import github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen (-: # github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen
../../../go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfgen/generate.go:184:48: not enough arguments in call to dotnetgen.GeneratePackage
	have (string, *"github.com/pulumi/pulumi/pkg/v3/codegen/schema".Package, map[string][]byte)
	want (string, *"github.com/pulumi/pulumi/pkg/v3/codegen/schema".Package, map[string][]byte, map[string]string)) (typecheck)
	"github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen"
	^
```
	

### Output of `pulumi about`

CLI
Version      3.113.2
Go Version   go1.22.2
Go Compiler  gc

Host
OS       darwin
Version  14.3.1
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
The terraform bridge and pulumi/pkg are highly version dependent. You should only be using the version of pulumi/pkg (and sdk) that match the version given in the go.mod of the terraform-bridge version you're using.

For v3.80 that's v3.112.0: https://github.com/pulumi/pulumi-terraform-bridge/blob/v3.80.0/go.mod#L206-L207

**Comment by belfhi** [comment]
Hi @Frassle,
Thanks for getting back to me. 
In that case I guess the error is not unexpected. I'll close the issue then. 👍

**Comment by Frassle** [comment]
@pulumi/providers might be worth documenting this limitation somewhere in the usage notes for TF bridge.
