### ISSUE TITLE
Allow mapping to different overlaid types for arguments and properties

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-terraform-bridge#19]
pulumi/pulumi-aws#414 brought up an interesting case where we projected AWS Tags into `{ [key: string]: string }`. This prevents using `Output<string>` as values, despite the engine being able to deal with that and it being a common use case.

We can't just change the type definition of `aws.Tags` to `{ [key: string]: Input<string> }`, because the same type is used for both the arguments object and the properties on the resource. We should add support for mapping different types for this purpose.

**Comment by lukehoban** [comment]
Closing this one out - as it has only impact one use case - and also this code generator is getting phased out.  I *believe* the new one handles this naturally - but also happy for this to be rediscovered if/when it comes up again in practice.
