### ISSUE TITLE
makeTerraformInputs converts empty strings wrong

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#1916]
### What happened?

discovered in https://github.com/pulumi/pulumi-terraform-bridge/pull/1913

We convert empty strings wrong.

### Example

```golang
func TestInputsEmptyString(t *testing.T) {
	t.Skip("Empty strings are misrepresented")
	runCreateInputCheck(t, inputTestCase{
		Resource: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"f0": {
					Type:     schema.TypeString,
					Required: true,
				},
			},
		},
		Config: tftypes.NewValue(
			tftypes.Object{
				AttributeTypes: map[string]tftypes.Type{
					"f0": tftypes.String,
				},
			},
			map[string]tftypes.Value{
				"f0": tftypes.NewValue(tftypes.String, ""),
			}),
	})
}
```

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
@VenelinMartinov How do we convert empty strings vs what they should be? Can you post a diff (what we do vs what tf does)?

**Comment by t0yv0** [comment]
I'd be curious to have some more detail here as well. I think I have an intuition about why set-nested blocks should convert as empty sets instead of null, but strings?

**Comment by VenelinMartinov** [comment]
This is what I got in `TestInputsEmptyString`:

```golang
Resource: &schema.Resource{
	Schema: map[string]*schema.Schema{
		"f0": {
			Type:     schema.TypeString,
			Required: true,
		},
	},
},
Config: tftypes.NewValue(
	tftypes.Object{
		AttributeTypes: map[string]tftypes.Type{
			"f0": tftypes.String,
		},
	},
	map[string]tftypes.Value{
		"f0": tftypes.NewValue(tftypes.String, ""),
	},
),
```

```
TF value cty.ObjectVal(map[string]cty.Value{"f0":cty.StringVal(""), "id":cty.UnknownVal(cty.String)})
PU value cty.ObjectVal(map[string]cty.Value{"f0":cty.NullVal(cty.String), "id":cty.NullVal(cty.String)})
```

We seem to use NullVal(cty.String) while TF returns cty.StringVal("")

**Comment by t0yv0** [comment]
That's under Required: true? Does it hold under `Optional: true`?

**Comment by t0yv0** [comment]
Wait hold on a second, Pulumi substitutes null for ""? That's very surprising. Might be worth double checking that we print a correct Pulumi program and it's not some kind of test harness issue.

**Comment by VenelinMartinov** [comment]
```yaml
backend:
    url: file://./data
name: project
resources:
    example:
        properties:
            f0: ""
        type: crossprovider:index:TestRes
runtime: yaml
```

```hcl
resource "crossprovider_testres" "example" {
  f0 = ""
}
```

Same thing for `Optional: true`.

I've also checked that https://github.com/pulumi/pulumi-terraform-bridge/pull/1971 fixes this so it must be UpgradeState at fault here.

**Comment by t0yv0** [comment]
I'm a little mindblown and very glad we got a fix for this.
