### ISSUE TITLE
Rewrite objectFromCtyValue function

### ISSUE THREAD

**Issue by corymhall** [pulumi/pulumi-terraform-bridge#1943]
### What happened?

We need to rewrite the [objectFromCtyValue](https://github.com/pulumi/pulumi-terraform-bridge/blob/935ad83006358781cdd9b66b85a872e296c6c0d5/pkg/tfshim/sdk-v2/instance_state.go#L69-L86) function. We will need to implement our own transform function to handle converting the cty value to a JSON map.

Currently this function performs some type checking which we do not want it to do. This leads to issues like #1932 

### Example

This can be used to reproduce the error

```go
package main

import (
	"fmt"

	"github.com/pulumi/pulumi-aws/sdk/v6/go/aws/ec2"
	"github.com/pulumi/pulumi-aws/sdk/v6/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		bucket, err := s3.NewBucket(ctx, "my-bucket", nil)
		if err != nil {
			return err
		}

		template, err := ec2.NewLaunchTemplate(ctx, "zbuchheit-launch-template", &ec2.LaunchTemplateArgs{
			ImageId: pulumi.String("dummyImageIdBecauseItIsAPreview"),
			TagSpecifications: &ec2.LaunchTemplateTagSpecificationArray{
				&ec2.LaunchTemplateTagSpecificationArgs{
					ResourceType: pulumi.String("resourceType1"),
					Tags: pulumi.StringMap{
						"Name": pulumi.Sprintf("BucketArn %s", bucket.Arn),
					},
				},
				&ec2.LaunchTemplateTagSpecificationArgs{
					ResourceType: pulumi.String("resourceType2"),
					Tags: pulumi.StringMap{
						"Name": pulumi.String("Bucket Arn"), // If you make this an output also, the panic will go away
					},
				},
			},
		},
		)
		if err != nil {
			return err
		}

		ctx.Export("bucket", bucket)
		ctx.Export("template", template)
		return nil
	})
}
```

### Output of `pulumi about`

CLI          
Version      3.111.1
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME  VERSION
aws   6.33.1
go    unknown

Host     
OS       darwin
Version  14.4.1
Arch     arm64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.22.0 darwin/arm64'

Current Stack: chall-pulumi-corp/pulumi-go-app/dev

TYPE                  URN
pulumi:pulumi:Stack   urn:pulumi:dev::pulumi-go-app::pulumi:pulumi:Stack::pulumi-go-app-dev
pulumi:providers:aws  urn:pulumi:dev::pulumi-go-app::pulumi:providers:aws::default
aws:iam/role:Role     urn:pulumi:dev::pulumi-go-app::aws:iam/role:Role::myrole

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/chall-pulumi-corp
User           chall-pulumi-corp
Organizations  chall-pulumi-corp, pulumi
Token type     personal

Dependencies:
NAME                                 VERSION
github.com/pulumi/pulumi-aws/sdk/v6  v6.33.1
github.com/pulumi/pulumi/sdk/v3      v3.115.2

Pulumi locates its logs in /var/folders/3b/6mr1jkqx7r797ff75k27jfjc0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Yeah it looks like specifically it chokes on rewriting unknowns of type other than string to the unknown sentinel. 

Thank you for picking this up @corymhall , just realizing since we shipped a workaround this is no longer an emergency, but I asked you to help with it right away delaying some other work. Much as I am excited to get this fixed, next time we should consider backlogging in these cases.
