### ISSUE TITLE
Pass PlanResourceChange through downstream tests

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#1962]
### What happened?

@t0yv0 recently suggested running PlanResourceChange through downstream tests as a short-term way to gain more confidence in it.

This should help with https://github.com/pulumi/pulumi-terraform-bridge/issues/1785

We already know about some issues (GCP bucket) but it might be useful to learn about other problematic resources

### Example

.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
This would be much appreciated since any bugs discovered here also probably affect AWS users through a handful of enrolled resources.

**Comment by VenelinMartinov** [comment]
I ran a round of downstream tests but we'd get more valuable results after https://github.com/pulumi/pulumi-terraform-bridge/issues/1849, so I'll finish that up first.

**Comment by VenelinMartinov** [comment]
Ok, biggest ones from the first run:

A bunch of panics: https://github.com/pulumi/pulumi-terraform-bridge/issues/1964 and https://github.com/pulumi/pulumi-terraform-bridge/issues/1966 maybe all root caused by https://github.com/pulumi/pulumi-terraform-bridge/issues/1916 and https://github.com/pulumi/pulumi-terraform-bridge/issues/1915

2 tfgen issues: https://github.com/pulumi/pulumi-terraform-bridge/issues/1965

A bunch of unexpected updates: https://github.com/pulumi/pulumi-terraform-bridge/issues/1967

**Comment by t0yv0** [comment]
Got https://github.com/pulumi/pulumi-aws/pull/4013 to pass AWS test suite on P/R/C.

**Comment by VenelinMartinov** [comment]
Two new issues downstream

https://github.com/pulumi/pulumi-hcloud/issues/528
https://github.com/pulumi/pulumi-terraform-bridge/issues/2079

**Comment by VenelinMartinov** [comment]
Ran downstream tests on https://github.com/pulumi/pulumi-terraform-bridge/pull/2065 with PRC enabled by default.

skipped really means failed

SKIPPED https://github.com/pulumi/pulumi-aws/pull/4053
SKIPPED https://github.com/pulumi/pulumi-gcp/pull/2071
SKIPPED https://github.com/pulumi/pulumi-auth0/pull/567
FAILURE https://github.com/pulumi/pulumi-hcloud/pull/530
SKIPPED https://github.com/pulumi/pulumi-gitlab/pull/637
SKIPPED https://github.com/pulumi/pulumi-azure/pull/2115
SKIPPED https://github.com/pulumi/pulumi-github/pull/687

---
For the AWS issues, the interesting ones are the ones about labels and these might just be overfitting on empty/null maps behaviour. Will investigate.

I believe the RDS failures here are explained in https://github.com/pulumi/pulumi-aws/pull/4013

---

I forgot to remove the debug logging and the GCP failures are incomprehensible and might be related to excessive logging. Will rerun the tests...

**Comment by t0yv0** [comment]
Confirmed, for AWS the test is not actually testing what it says in this case, there's on actual problem.

**Comment by VenelinMartinov** [comment]
https://github.com/pulumi/pulumi/pull/16146 changed the results here - a few of the dirty refreshes present before no longer show up in tests.

**Comment by VenelinMartinov** [comment]
a ci-mgmt issue means that we don't currently run tests against latest pulumi CLI: https://github.com/pulumi/ci-mgmt/pull/973

Will rerun downstream tests after that merges to see if the new refresh behaviour changes anything.

**Comment by VenelinMartinov** [comment]
Ran downstream tests without 2065 with PRC enabled by default:

SKIPPED https://github.com/pulumi/pulumi-cloudflare/pull/813 (looks like 2065 is needed here, will confirm)
UNKNOWN https://github.com/pulumi/pulumi-aws/pull/4078
SKIPPED https://github.com/pulumi/pulumi-gcp/pull/2092
SKIPPED https://github.com/pulumi/pulumi-auth0/pull/576 (fixed in https://github.com/pulumi/pulumi-auth0/pull/572)
SKIPPED https://github.com/pulumi/pulumi-hcloud/pull/538 (fixed in https://github.com/pulumi/pulumi-hcloud/pull/533)
SKIPPED https://github.com/pulumi/pulumi-pagerduty/pull/531 (unrelated fixed in https://github.com/pulumi/pulumi-pagerduty/pull/530)
SKIPPED https://github.com/pulumi/pulumi-azure/pull/2129
SKIPPED https://github.com/pulumi/pulumi-digitalocean/pull/751 (unrelated fixed in https://github.com/pulumi/pulumi-digitalocean/pull/750)
SKIPPED https://github.com/pulumi/pulumi-github/pull/696 (tests fixed in https://github.com/pulumi/pulumi-github/pull/693)

---

**Comment by VenelinMartinov** [comment]
The AWS failures are because AWS has not picked up ci-mgmt so has not picked up the new refresh from the CLI... retesting in https://github.com/pulumi/pulumi-cloudflare/pull/813, will update manually

**Comment by VenelinMartinov** [comment]
AWS and Azure are fine, just GCP left - failures in the tags tests, investigating.

**Comment by VenelinMartinov** [comment]
The GCP example is quite odd:

<details> <summary> GRPC logs </summary>

```json
{
    "method": "/pulumirpc.ResourceProvider/Read",
    "request": {
        "id": "demo-bucket-ec59f09",
        "urn": "urn:pulumi:p-it-venelins-m-labels-com-9668704a::labels-combinations-go::gcp:storage/bucket:Bucket::demo-bucket",
        "properties": {
            "__meta": "{\"e2bfb730-ecaa-11e6-8f88-34363bc7c4c0\":{\"create\":600000000000,\"read\":240000000000,\"update\":240000000000},\"schema_version\":\"1\"}",
            "autoclass": null,
            "cors": [],
            "customPlacementConfig": null,
            "defaultEventBasedHold": false,
            "effectiveLabels": {
                "y": "s"
            },
            "enableObjectRetention": false,
            "encryption": null,
            "forceDestroy": false,
            "id": "demo-bucket-ec59f09",
            "labels": {
                "x": ""
            },
            "lifecycleRules": [],
            "location": "US",
            "logging": null,
            "name": "demo-bucket-ec59f09",
            "project": "pulumi-development",
            "projectNumber": 921927215178,
            "publicAccessPrevention": "inherited",
            "pulumiLabels": {
                "y": "s"
            },
            "requesterPays": false,
            "retentionPolicy": null,
            "rpo": "DEFAULT",
            "selfLink": "https://www.googleapis.com/storage/v1/b/demo-bucket-ec59f09",
            "softDeletePolicy": {
                "effectiveTime": "2024-06-17T15:17:37.175Z",
                "retentionDurationSeconds": 604800
            },
            "storageClass": "STANDARD",
            "uniformBucketLevelAccess": false,
            "url": "gs://demo-bucket-ec59f09",
            "versioning": null,
            "website": null
        },
        "inputs": {
            "__defaults": [
                "forceDestroy",
                "name",
                "storageClass"
            ],
            "forceDestroy": false,
            "labels": {
                "x": ""
            },
            "location": "US",
            "name": "demo-bucket-ec59f09",
            "storageClass": "STANDARD"
        }
    },
    "response": {
        "id": "demo-bucket-ec59f09",
        "properties": {
            "__meta": "{\"e2bfb730-ecaa-11e6-8f88-34363bc7c4c0\":{\"create\":600000000000,\"read\":240000000000,\"update\":240000000000},\"schema_version\":\"1\"}",
            "autoclass": null,
            "cors": [],
            "customPlacementConfig": null,
            "defaultEventBasedHold": false,
            "effectiveLabels": {
                "y": "s"
            },
            "enableObjectRetention": false,
            "encryption": null,
            "forceDestroy": false,
            "id": "demo-bucket-ec59f09",
            "labels": {
                "x": ""
            },
            "lifecycleRules": [],
            "location": "US",
            "logging": null,
            "name": "demo-bucket-ec59f09",
            "project": "pulumi-development",
            "projectNumber": 921927215178,
            "publicAccessPrevention": "inherited",
            "pulumiLabels": {
                "y": "s"
            },
            "requesterPays": false,
            "retentionPolicy": null,
            "rpo": "DEFAULT",
            "selfLink": "https://www.googleapis.com/storage/v1/b/demo-bucket-ec59f09",
            "softDeletePolicy": {
                "effectiveTime": "2024-06-17T15:17:37.175Z",
                "retentionDurationSeconds": 604800
            },
            "storageClass": "STANDARD",
            "uniformBucketLevelAccess": false,
            "url": "gs://demo-bucket-ec59f09",
            "versioning": null,
            "website": null
        },
        "inputs": {
            "__defaults": [
                "forceDestroy",
                "name",
                "storageClass"
            ],
            "forceDestroy": false,
            "labels": {
                "x": ""
            },
            "location": "US",
            "name": "demo-bucket-ec59f09",
            "storageClass": "STANDARD"
        }
    },
    "metadata": {
        "kind": "resource",
        "mode": "client",
        "name": "gcp"
    }
}
{
    "method": "/pulumirpc.ResourceProvider/Diff",
    "request": {
        "id": "demo-bucket-ec59f09",
        "urn": "urn:pulumi:p-it-venelins-m-labels-com-9668704a::labels-combinations-go::gcp:storage/bucket:Bucket::demo-bucket",
        "olds": {
            "__meta": "{\"e2bfb730-ecaa-11e6-8f88-34363bc7c4c0\":{\"create\":600000000000,\"read\":240000000000,\"update\":240000000000},\"schema_version\":\"1\"}",
            "autoclass": null,
            "cors": [],
            "customPlacementConfig": null,
            "defaultEventBasedHold": false,
            "effectiveLabels": {
                "y": "s"
            },
            "enableObjectRetention": false,
            "encryption": null,
            "forceDestroy": false,
            "id": "demo-bucket-ec59f09",
            "labels": {
                "x": ""
            },
            "lifecycleRules": [],
            "location": "US",
            "logging": null,
            "name": "demo-bucket-ec59f09",
            "project": "pulumi-development",
            "projectNumber": 921927215178,
            "publicAccessPrevention": "inherited",
            "pulumiLabels": {
                "y": "s"
            },
            "requesterPays": false,
            "retentionPolicy": null,
            "rpo": "DEFAULT",
            "selfLink": "https://www.googleapis.com/storage/v1/b/demo-bucket-ec59f09",
            "softDeletePolicy": {
                "effectiveTime": "2024-06-17T15:17:37.175Z",
                "retentionDurationSeconds": 604800
            },
            "storageClass": "STANDARD",
            "uniformBucketLevelAccess": false,
            "url": "gs://demo-bucket-ec59f09",
            "versioning": null,
            "website": null
        },
        "news": {
            "__defaults": [
                "forceDestroy",
                "name",
                "storageClass"
            ],
            "forceDestroy": false,
            "labels": {
                "x": ""
            },
            "location": "US",
            "name": "demo-bucket-ec59f09",
            "storageClass": "STANDARD"
        },
        "oldInputs": {
            "__defaults": [
                "forceDestroy",
                "name",
                "storageClass"
            ],
            "forceDestroy": false,
            "labels": {
                "x": ""
            },
            "location": "US",
            "name": "demo-bucket-ec59f09",
            "storageClass": "STANDARD"
        }
    },
    "response": {
        "stables": [
            "enableObjectRetention",
            "location",
            "name",
            "project"
        ],
        "changes": "DIFF_SOME",
        "diffs": [
            "effectiveLabels",
            "pulumiLabels"
        ],
        "detailedDiff": {
            "effectiveLabels": {
                "kind": "UPDATE"
            },
            "pulumiLabels": {
                "kind": "UPDATE"
            }
        },
        "hasDetailedDiff": true
    },
    "metadata": {
        "kind": "resource",
        "mode": "client",
        "name": "gcp"
    }
}
```

</details>

The labels in the Read response is exactly the same as what was in the inputs but we return a diff.

Neither of the properties which has a diff is in olds or news, so not sure why it is being flagged up. Might be a bridge workaround, investigating...

**Comment by VenelinMartinov** [comment]
https://github.com/pulumi/pulumi-gcp/issues/2079 is now done so PRC passes all downstream tests.
