### ISSUE TITLE
PlanResourceChange undesirable updates

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#1967]
### What happened?

A bunch of providers got unexpeced diffs with PlanResourceChange.

### Example

https://github.com/pulumi/pulumi-azuread/actions/runs/9065108544/job/24905710331?pr=1050
https://github.com/pulumi/pulumi-auth0/actions/runs/9065083805/job/24904827772?pr=540
https://github.com/pulumi/pulumi-hcloud/actions/runs/9065349562/job/24906565191?pr=506
https://github.com/pulumi/pulumi-cloudflare/actions/runs/9065158604/job/24905830152?pr=774
https://github.com/pulumi/pulumi-aws/actions/runs/9065699572/job/24909556049?pr=3931

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Having a quick look, some of the AWS failures look serious but we need to go one by one.

**Comment by VenelinMartinov** [comment]
A lot of the updates are due to https://github.com/pulumi/pulumi-terraform-bridge/issues/2047

But also we have a few others:

meta -> metadata: https://github.com/pulumi/pulumi-auth0/actions/runs/9065083805/job/24904827772?pr=540

some unexpected nulls and unknowns in AWS: https://github.com/pulumi/pulumi-aws/actions/runs/9065699572/job/24909556049?pr=3931

Also some other issues with RDS instances there

**Comment by t0yv0** [comment]
Can you send me an AWS branch to debug. Thanks.

**Comment by VenelinMartinov** [comment]
I was going to ask for help here, thanks!

https://github.com/pulumi/pulumi-aws/pull/3931 is a slightly older bridge master

https://github.com/pulumi/pulumi-aws/pull/3983 is the one with the block normalizations PR, feel free to ignore this one but the errors look fairly similar at a glance

You can also run the AWS provider with `PULUMI_ENABLE_PLAN_RESOURCE_CHANGE=1` and it'll enable PlanResourceChange for all resources.

**Comment by t0yv0** [comment]
Perfect, I want the one with everything latest so 3983 sounds good. I'll take a look.

**Comment by VenelinMartinov** [comment]
Thanks!

**Comment by VenelinMartinov** [comment]
Aside from the AWS failures the others all look like https://github.com/pulumi/pulumi-terraform-bridge/issues/2047

**Comment by t0yv0** [comment]
AWS is done in https://github.com/pulumi/pulumi-aws/pull/4013

**Comment by VenelinMartinov** [comment]
last round I ran here:

FAILURE https://github.com/pulumi/pulumi-hcloud/pull/525
FAILURE https://github.com/pulumi/pulumi-auth0/pull/564
FAILURE https://github.com/pulumi/pulumi-aws/pull/4048
FAILURE https://github.com/pulumi/pulumi-fastly/pull/559

hcloud is https://github.com/pulumi/pulumi-hcloud/issues/528, present on master
auth0 and fastly need a resource enrolled in PRC: https://github.com/pulumi/pulumi-fastly/pull/556 and https://github.com/pulumi/pulumi-auth0/pull/566

AWS is explained in https://github.com/pulumi/pulumi-aws/pull/4013

**Comment by VenelinMartinov** [comment]
This was fixed with the new refresh behaviour in the CLI.
