### ISSUE TITLE
Tracking: issues with failing import 

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#2028]
Tracking issues around `pulumi import` in bridged providers.

Themes here: [Import](https://pulumi-developer-docs.readthedocs.io/en/latest/architecture/import.html?highlight=import) maps to a series of calls such as Read and Check that causes mismatch between TF and Pulumi expectations. There are several known themes of failure that may inform mitigation:

1. In TF, resources are more lax in returning data through Read that might not pass validators; Pulumi can mitigate by deploying data correction strategies either at the bridge or individual provider/resource level

2. When Pulumi invokes a language-specific code generator it has strict type safety expectations on the data that is fed into it. In practice the data is often not type-conformant (for example required fields, are missing data). Pulumi can mitigate by cleaning the data to be type conformant to err on the side of succeeding with the import.

This issue is intended to track specific instances in bridged providers before suggesting more solutions in this space.

### Examples

- https://github.com/pulumi/pulumi-aws/issues/3986
- https://github.com/pulumi/pulumi-aws/issues/2517 (patched, not fixed)
  - https://github.com/pulumi/pulumi-terraform-bridge/pull/1105
- https://github.com/pulumi/pulumi-linode/issues/373
- https://github.com/pulumi/pulumi-github/issues/642
- https://github.com/pulumi/pulumi-aws/issues/4054

### Mitigations

- https://github.com/pulumi/pulumi-terraform-bridge/pull/1948
- https://github.com/pulumi/pulumi-terraform-bridge/issues/2314
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1949

**Comment by zbuchheit** [comment]
I believe I am having this issue as well with a user that has an internal private bridge provider. I will provide details separately.

**Comment by VenelinMartinov** [comment]
@zbuchheit I'd be interested to hear about the details here, thanks!

**Comment by t0yv0** [comment]
Thanks @corymhall for making a good dent in these set of issues with bridge fixes. I think this was useful to mine for opportunities even if we didn't find the bigger wins that we hoped to find. Closing as there are no immediate plans to move this forward.
