### ISSUE TITLE
Bridge does not run TF upgrades from version 0 -> 1

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2039]
### What happened?

While working on https://github.com/pulumi/pulumi-terraform-bridge/issues/2034, it was discovered that TF runs state upgrades for a resource created with version 0 and then upgraded to 1, while we don't seem to.

I believe this is because version 0 is not written to state and we assume current version, while TF assumes 0.

### Example

.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
This is not correct, it was a result of local changes I added to debug a related issue. My bad.

**Comment by VenelinMartinov** [comment]
repro in https://github.com/pulumi/pulumi-terraform-bridge/pull/2040

**Comment by t0yv0** [comment]
Haven't had time to check if still an issue with the latest version that passed AWS tests https://github.com/pulumi/pulumi-aws/pull/4013

**Comment by VenelinMartinov** [comment]
Confirmed this is indeed still an issue.

**Comment by VenelinMartinov** [comment]
Yeah, I ran the repro with some debug logs and it looks like on the first pulumi up, everything is fine but we don't write version 0 to state.

After that when getting the state and transforming to TF state https://github.com/pulumi/pulumi-terraform-bridge/blob/3c1421d15a61cfa11f350db7b796dcd5795da200/pkg/tfbridge/schema.go#L1310

we assume empty schema version means current version, so we don't run the state upgrade.

**Comment by VenelinMartinov** [comment]
This seems to affect non-PRC too
