### ISSUE TITLE
Decide on a strategy to deal with changes to aws tagging

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-terraform-bridge#206]
This PR https://github.com/terraform-providers/terraform-provider-aws/pull/13233 introduced breaking changes to our tags

We reverted the commit in our fork but we need to come up with a strategy to mitigate the breaking changes

**Comment by mikhailshilkov** [comment]
@stack72 Given your PR today, is this task "done"?

**Comment by stack72** [comment]
@mikhailshilkov nah, there's still a doc / guidance from @lukehoban outstanding. The issue we ad to fix in my PR was that there are 3 reported cases of panics due to the code we reverted :/ So we reverted to stop people getting broken but actually broke them in a different way

We need to rectify that and continue to look at things on a case by case basis

**Comment by lukehoban** [comment]
Actually - I think this one is done.  https://github.com/pulumi/home/issues/877 is tracking a document on breaking change policy more broadly.   Is that right @stack72?

**Comment by stack72** [comment]
Oh you are correct - I didn’t see the dupe! Sorry @mikhailshilkov :)
