### ISSUE TITLE
Custom package name in C# generated SDK

### ISSUE THREAD

**Issue by smartinellimarco** [pulumi/pulumi-terraform-bridge#2064]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Is there a way to change the C# package name?
Im thinking something like:
```go
		CSharp: &tfbridge.CSharpInfo{
			RespectSchemaVersion: true,
			PackageReferences: map[string]string{
				"Pulumi": "3.*",
			},
			RootNamespace: nugetOrg,
                        PackageName: "MyPackage",
		},
```

### Affected area/feature

C# SDK

**Comment by smartinellimarco** [comment]
@guineveresaenger Hello!
I bridged our terraform provider using the boilerplate at https://github.com/pulumi/pulumi-tf-provider-boilerplate.
The `tfgen` tool uses as default the provider name for the package name.
However this customizable for the NPM and PyPi packages:
```go
		JavaScript: &tfbridge.JavaScriptInfo{
			PackageName:          "@splightplatform/pulumi-splight",
			RespectSchemaVersion: true,
			Dependencies: map[string]string{
				"@pulumi/pulumi": "^3.0.0",
			},
			DevDependencies: map[string]string{
				"@types/node": "^10.0.0", // So we can access strongly typed node definitions.
				"@types/mime": "^2.0.0",
			},
		},
		Python: &tfbridge.PythonInfo{
			PackageName:          "pulumi_splight",
			RespectSchemaVersion: true,
			Requires: map[string]string{
				"pulumi": ">=3.0.0,<4.0.0",
			},
		},

```
 But for NuGet I can not find the same parameter, and, given that our organization is called Splight, the package name ends up being Splight.Splight, which is not very descriptive.

**Comment by guineveresaenger** [comment]
Hi @smartinellimarco  - I looked into it and I think that for C#, you'll be able to use the `Namespaces` map instead?

```
Namespaces: map[string]string{
  "splight": "awesomeNewPackage",
},
```

And, in the meantime, of course PRs are always welcome - we're happy to help. :)
