### ISSUE TITLE
Upstream installation instructions: Docs Edits and Transformations

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-terraform-bridge#2078]
Part of https://github.com/pulumi/registry/issues/4749.

https://github.com/pulumi/pulumi-terraform-bridge/pull/2068 adds the ability to emit the upstream `index.md` file, where top-level provider information lives, into a `docs` folder in the Pulumi provider, which is where the registry can find the file if it exists, exactly as we are doing for third party providers today.

To emit these docs properly, the following requirements must be met before emitting this file:

- [x] Apply default doc edit rules
- [x] Convert examples
- [x] Add Hugo shortcodes to any examples so we can obtain the code chooser
- [x] Transform TF names to Pulumi names
- [x] Ability to skip irrelevant sections (e.g. terraform-specific logging, contributing) via docs edit rules
- [ ] Nice-to-have: Include `pulumi config set`... instructions
- [x] Nice-to-have: Show provider config file 
- [x] Light rewording of "Argument Reference" "block supports the following"
- [x] Include installation section
- [x] Add registry Hugo frontmatter

**Comment by guineveresaenger** [comment]
This is ready to be rolled out on select Tier 3 providers. Note that the [Akamai provider](https://registry.terraform.io/providers/akamai/akamai/latest/docs) keeps their installation docs elsewhere so we'll have to come up with an alternative.

**Comment by iwahbe** [comment]
I have created an issue to track rollout: https://github.com/pulumi/home/issues/3598

**Comment by guineveresaenger** [comment]
Rollout is complete.

This issue is done.
