### ISSUE TITLE
Wrong diff returned for removed items in TF sets

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2103]
### What happened?

In https://github.com/pulumi/pulumi-snowflake/issues/640 it was discovered that we return the wrong diff for the case where items are removed from a set.

This results in the CLI displaying the wrong number of items being removed from the set in the detailed diff display, causing confusion.

### Example

From the issue above:

<details>

```json
{
    "method": "/pulumirpc.ResourceProvider/Diff",
    "request": {
        "id": "\"SNOWFLAKE_ANALYST\"|false|false|CREATE EXTERNAL TABLE,CREATE TABLE,CREATE VIEW,CREATE TEMPORARY TABLE,USAGE|OnSchema|OnSchema|\"my_database\".\"my_custom_schema\"",
        "urn": "urn:pulumi:dev::privilege_revoke::snowflake:index/grantPrivilegesToAccountRole:GrantPrivilegesToAccountRole::snowflake-privileges",
        "olds": {
            "accountRoleName": "SNOWFLAKE_ANALYST",
            "allPrivileges": false,
            "alwaysApply": false,
            "id": "\"SNOWFLAKE_ANALYST\"|false|false|CREATE EXTERNAL TABLE,CREATE TABLE,CREATE VIEW,CREATE TEMPORARY TABLE,USAGE|OnSchema|OnSchema|\"my_database\".\"my_custom_schema\"",
            "onAccount": false,
            "onSchema": {
                "allSchemasInDatabase": "",
                "futureSchemasInDatabase": "",
                "schemaName": "my_database.my_custom_schema"
            },
            "privileges": [
                "CREATE EXTERNAL TABLE",
                "CREATE TABLE",
                "CREATE VIEW",
                "CREATE TEMPORARY TABLE",
                "USAGE"
            ],
            "withGrantOption": false
        },
        "news": {
            "__defaults": [
                "alwaysApply",
                "alwaysApplyTrigger",
                "withGrantOption"
            ],
            "accountRoleName": "SNOWFLAKE_ANALYST",
            "alwaysApply": false,
            "alwaysApplyTrigger": "",
            "onSchema": {
                "__defaults": [],
                "schemaName": "my_database.my_custom_schema"
            },
            "privileges": [
                "USAGE"
            ],
            "withGrantOption": false
        },
        "oldInputs": {
            "__defaults": [
                "alwaysApply",
                "alwaysApplyTrigger",
                "withGrantOption"
            ],
            "accountRoleName": "SNOWFLAKE_ANALYST",
            "alwaysApply": false,
            "alwaysApplyTrigger": "",
            "onSchema": {
                "__defaults": [],
                "schemaName": "my_database.my_custom_schema"
            },
            "privileges": [
                "CREATE EXTERNAL TABLE",
                "CREATE TABLE",
                "CREATE VIEW",
                "CREATE TEMPORARY TABLE",
                "USAGE"
            ],
            "withGrantOption": false
        }
    },
    "response": {
        "stables": [
            "accountRoleName",
            "onAccount",
            "onAccountObject",
            "onSchema",
            "onSchemaObject",
            "withGrantOption"
        ],
        "changes": "DIFF_SOME",
        "diffs": [
            "privileges",
            "privileges",
            "privileges",
            "privileges",
            "privileges"
        ],
        "detailedDiff": {
            "privileges": {
                "kind": "UPDATE"
            },
            "privileges[0]": {
                "kind": "DELETE"
            },
            "privileges[1]": {
                "kind": "DELETE"
            },
            "privileges[2]": {
                "kind": "DELETE"
            },
            "privileges[3]": {
                "kind": "DELETE"
            }
        },
        "hasDetailedDiff": true
    },
    "metadata": {
        "kind": "resource",
        "mode": "client",
        "name": "snowflake"
    }
}
```

</details>

Notice the repeated entry in `diffs`

### Output of `pulumi about`

CLI
Version      3.120.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME       VERSION
resource  snowflake  unknown
language  yaml       unknown

Host
OS       darwin
Version  14.1.1
Arch     arm64

This project is written in yaml

Current Stack: pulumi/privilege_revoke/dev

TYPE                                                                       URN
pulumi:pulumi:Stack                                                        urn:pulumi:dev::privilege_revoke::pulumi:pulumi:Stack::privilege_revoke-dev
pulumi:providers:snowflake                                                 urn:pulumi:dev::privilege_revoke::pulumi:providers:snowflake::default
snowflake:index/database:Database                                          urn:pulumi:dev::privilege_revoke::snowflake:index/database:Database::myDatabase
snowflake:index/role:Role                                                  urn:pulumi:dev::privilege_revoke::snowflake:index/role:Role::myRole
snowflake:index/schema:Schema                                              urn:pulumi:dev::privilege_revoke::snowflake:index/schema:Schema::mySchema
snowflake:index/grantPrivilegesToAccountRole:GrantPrivilegesToAccountRole  urn:pulumi:dev::privilege_revoke::snowflake:index/grantPrivilegesToAccountRole:GrantPrivilegesToAccountRole::snowflake-privileges

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/venelin-pulumi-corp
User           venelin-pulumi-corp
Organizations  venelin-pulumi-corp, demo, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/82/nqnqw81s1h56l5nv940f9mq00000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
More generally https://github.com/pulumi/pulumi-terraform-bridge/issues/186 and linked tickets indicate significant issues in diff support for sets. I still don't have clean solution and I suspect a clean solution would need some tweaks to the provider protocol. Happy to discuss if interesting.

**Comment by VenelinMartinov** [comment]
https://github.com/pulumi/pulumi/issues/16466 for the pu/pu bug

**Comment by t0yv0** [comment]
I'm having some doubts I understand how 2104 possibly solves the general issue here, are you confident in this or there's some follow up work?

**Comment by VenelinMartinov** [comment]
The ticket here was specifically for the issue observed in 640:

1. A collection of items in state
2. 4 out of 5 of them are removed
3. Diff displays that all 5 are removed.

This was indeed fixed in 2104.

Perhaps the issue description needs some work to specify the exact issue observed.

As for the general issue, is it not captured by https://github.com/pulumi/pulumi-terraform-bridge/issues/186?
