### ISSUE TITLE
Error converting aws.wafv2.WebAcl 

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi-terraform-bridge#2121]
Based on the "Coming soon!"s [in the Examples section of `aws.wafv2.WebAcl`](https://www.pulumi.com/registry/packages/aws/api-docs/wafv2/webacl/#example), it looks like we had some trouble converting the examples [from the source HCL](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#example-usage). We should investigate what went wrong, and if possible, set up a report that lets us know when commonly used resources like these fail to convert.

**Comment by iwahbe** [comment]
These resources are actually intentionally skipped, since they either hang or take a prohibitively long time: https://github.com/pulumi/pulumi-aws/blob/ba12162e19c67f1727000f3a528304ebdd689c36/provider/resources.go#L5952-L5958

The fix is tracked in https://github.com/pulumi/pulumi-aws/issues/2598.
