### ISSUE TITLE
Handle `types.Dynamic` when making property types

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-terraform-bridge#2127]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We currently do not have the ability to handle `types.Dynamic` when translating to the Pulumi type system. We should implement this functionality.

See also: https://github.com/pulumi/pulumi-terraform-bridge/issues/1988

**Comment by t0yv0** [comment]
Do we have any more examples of providers that use types.Dynamic, that would be helpful. I searched pulumi-aws upstream to no avail.

**Comment by dirien** [comment]
@t0yv0 https://github.com/pulumi/pulumi-terraform-bridge/issues/1988

**Comment by t0yv0** [comment]
That's already been linked thanks @dirien do we have any more?

**Comment by iwahbe** [comment]
Dynamic types show up in hashicorp/kubernetes (causing this issue: https://github.com/pulumi/pulumi-terraform-provider/issues/7).

**Comment by t0yv0** [comment]
Indeed it appears K8S models manifest. https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest

Working out the support for this now.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3371
