### ISSUE TITLE
Missed argument description in `digitalocean:index:Droplet`

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi-terraform-bridge#214]
See e.g. https://github.com/pulumi/pulumi-digitalocean/blob/729184b/sdk/dotnet/Droplet.cs#L59-L64

**Comment by jkodroff** [comment]
Verified this is still an issue.

Additional context: The urn description is including the bullet point for `name`.

Droplet docs in the Pulumi registry are likewise incorrect: https://www.pulumi.com/registry/packages/digitalocean/api-docs/droplet/#dropleturn_nodejs

Upstream docs: https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/droplet#urn
