### ISSUE TITLE
Add a -get-plugin-schema flag to dump schema.json

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-terraform-bridge#2146]
## Hello! 
 
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When testing/building providers, it's helpful to be able to get the schema.json/pulumi transformed schema quickly. It would be useful to add a `-get-plugin-schema` flag similar to the `-get-provider-info` flag to provide this information.

### Affected area/feature
Plugin binary flags

**Comment by iwahbe** [comment]
Hi @zbuchheit. We don't plan to add a feature like this because you can get the same behavior already with `pulumi`:

```console
$ pulumi package get-schema ./my-provider-binary > schema.json
```

This works with any provider (not just bridged providers, and not just local providers).

Let me know if I've misunderstood your suggestion and I'll re-open the issue.

**Comment by zbuchheit** [comment]
makes sense, I wasn't aware of that command when I opened the issue. I think that meets the user's use-case here. Thanks!
