### ISSUE TITLE
PF wrong diff for set of objects

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2170]
### What happened?

During https://github.com/pulumi/pulumi-meraki/issues/97 it was discovered that the pf bridge does not produce a diff when an element is added to set of objects.

Seems like this happens only if all of the properties of the object are Computed + Optional

### Example

https://github.com/pulumi/pulumi-terraform-bridge/pull/2168

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Removing the `Computed` from one of the attributes of the object prevents the issue:

```golang
"vlan_names": schema.SetNestedAttribute{
		MarkdownDescription: `An array of named VLANs`,
		Optional:            true,
		NestedObject: schema.NestedAttributeObject{
			Attributes: map[string]schema.Attribute{
				"name": schema.StringAttribute{
					MarkdownDescription: `Name of the VLAN, string length must be from 1 to 32 characters`,
					// Computed:            true,
					Optional:            true,
				},
				"vlan_id": schema.StringAttribute{
					MarkdownDescription: `VLAN ID`,
					Computed:            true,
					Optional:            true,
				},
			},
		},
	},
```

**Comment by VenelinMartinov** [comment]
We seem to get the wrong value from the TF plan in https://github.com/pulumi/pulumi-terraform-bridge/blob/18db7c57211af0eb7dfa26a70b145edc4d33a88f/pf/tfbridge/provider_diff.go#L81

However this does seem to repro in TF, so they are likely doing something different with the plan parameters.

**Comment by VenelinMartinov** [comment]
Possibly related: https://github.com/pulumi/pulumi-terraform-bridge/pull/703 - this specifically calls out recursive Optional + Computed as a likely issue

**Comment by VenelinMartinov** [comment]
We recently updated our ProposedNew copy in SDKV2: https://github.com/pulumi/pulumi-terraform-bridge/pull/2060

Could be that the PF re-implementation is based on the old TF version

**Comment by VenelinMartinov** [comment]
Seems like we didn't re-use that as it works off the cty types instead of the pf tftypes and instead opted to re-implement it on our side.

**Comment by VenelinMartinov** [comment]
Some relevant-looking changes upstream, likely related: https://github.com/opentofu/opentofu/commit/d49e991c3c33c10b26c120465466d41f96e073de

a few others too https://github.com/opentofu/opentofu/commits/main/internal/plans/objchange

**Comment by VenelinMartinov** [comment]
Verified the issue indeed happens during the joining of the prior state and new config here: https://github.com/pulumi/pulumi-terraform-bridge/blob/18db7c57211af0eb7dfa26a70b145edc4d33a88f/pf/internal/pfutils/proposed_new.go#L107

Join incorrectly returns the old state of the set with a single element for the test above.

**Comment by VenelinMartinov** [comment]
Think I might have found the culprit:

https://github.com/pulumi/pulumi-terraform-bridge/blob/18db7c57211af0eb7dfa26a70b145edc4d33a88f/pf/internal/pfutils/proposed_new.go#L64-L67

We have an override for Set equality which replaces all Computed attributes with nulls - this prob means that if a set contains only entirely computed elements, they'd get wrongly equated.

**Comment by VenelinMartinov** [comment]
I've opened https://github.com/pulumi/pulumi-terraform-bridge/issues/2172 as a follow up for potentially updating our adaptation of objchange.

Also opened https://github.com/pulumi/pulumi-terraform-bridge/issues/2171 for investigating support for PlanModifiers as it doesn't look as if these get used anywhere. This might have been the original cause of the above change for set equality.

**Comment by t0yv0** [comment]
There's a chance it might be addressed by https://github.com/pulumi/pulumi-terraform-bridge/pull/2188 but will need to confirm explicitly

**Comment by VenelinMartinov** [comment]
I don't think #2188 addresses this - the reason this is happening is https://github.com/pulumi/pulumi-terraform-bridge/issues/2170#issuecomment-2220435287

We consider elements with all properties computed (+optional) equal, no matter their values.

**Comment by t0yv0** [comment]
Can you elaborate? 2188 literally deletes the code you reference in that comment.

**Comment by VenelinMartinov** [comment]
Okay, fair, didn't realise that - good chance it fixes it then!
