### ISSUE TITLE
PF investigate support for PlanModifiers

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2171]
### What happened?

Looking at the code around PF Diff it doesn't look like PlanModifiers are used in ProposedNew anywhere - does that mean we ignore these?

### Example

```
"vlan_id": schema.StringAttribute{
	MarkdownDescription: `VLAN ID`,
	Computed:            true,
	Optional:            true,
	PlanModifiers: []planmodifier.String{
		stringplanmodifier.UseStateForUnknown(),
	},
},
```

This should yield a different plan then when the PlanModifier is missing.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
I expect plan modifiers to fully work, curious if you find a counter-example.

**Comment by corymhall** [comment]
I think that https://github.com/pulumi/pulumi-aws/issues/4273 is an example of this in `pulumi-aws`

**Comment by VenelinMartinov** [comment]
I think I have a repro: https://github.com/pulumi/pulumi-terraform-bridge/pull/2217

I'm assuming this is connected to https://github.com/pulumi/pulumi-terraform-bridge/issues/2218 and will investigate as part of that.

**Comment by VenelinMartinov** [comment]
Not 100% sure about this anymore - tried to repro in pulumi-random:

<details>

```python
"""A Python Pulumi program"""

import pulumi
import pulumi_random as random


resNumeric = random.RandomString(
    "str1",
    length=10,
    numeric=False,
)

resNumber = random.RandomString(
    "str2",
    length=10,
    number=False,
)

pulumi.export("number val 1", resNumeric.number)
pulumi.export("numeric val 1", resNumeric.numeric)

pulumi.export("number val 2", resNumber.number)
pulumi.export("numeric val 2", resNumber.numeric)

```

</details>

These properties have plan modifiers and they seem to be working: https://github.com/hashicorp/terraform-provider-random/blame/455294a2038f3cf39a31f8eda231b95f190df250/internal/provider/resource_string.go#L453

**Comment by corymhall** [comment]
I can't reproduce the AWS issue anymore either if I use the latest bridge@master so something must have been fixed

**Comment by VenelinMartinov** [comment]
This turned out to be a red herring - the test was set up wrong - plan modifiers are applied fine as long as the provider is implemented correctly to apply the plan, not the config:

https://github.com/pulumi/pulumi-terraform-bridge/pull/2217
