### ISSUE TITLE
Acceptance tests do not run on community PRs

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2179]
### What happened?

https://github.com/pulumi/pulumi-terraform-bridge/pull/2174

Acceptance tests do not seem to run on community PRs even after member approval.

### Example

.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
The /run-acceptance-tests comment actually worked but it took a while: https://github.com/pulumi/pulumi-dnsimple/actions/runs/10142262748 but the "approve tests" didn't.

Sorry for the noise, I was a bit hasty here.

**Comment by VenelinMartinov** [comment]
We still can't merge community PRs, reopening this.

**Comment by VenelinMartinov** [comment]
The acceptance test ran but the PR is still not mergable: https://github.com/pulumi/pulumi-dnsimple/pull/467

**Comment by iwahbe** [comment]
@VenelinMartinov This issue AFAIK only applied to the bridge, not to our providers. CI for providers is managed in pulumi/ci-mgmt. If we have the same problem in a provider, please open another issue in ci-mgmt.
