### ISSUE TITLE
PF Computed Set does not trigger diff when an element is removed

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2192]
### What happened?

During https://github.com/pulumi/pulumi-meraki/issues/116 it was discovered that Computed + Optional Sets do not trigger a diff when an element is removed.

Possibly related to https://github.com/pulumi/pulumi-terraform-bridge/issues/2170

Note that the properties of the elements in the set here are not all computed.

### Example

Repro in https://github.com/pulumi/pulumi-terraform-bridge/pull/2193

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Hopefully can be addressed by something like https://github.com/pulumi/pulumi-terraform-bridge/pull/2188 but will need to confirm.

**Comment by t0yv0** [comment]
I'll take it together with 2188.

**Comment by VenelinMartinov** [comment]
@t0yv0 was this fixed in #2188 ? Should we merge a regression test for this and https://github.com/pulumi/pulumi-terraform-bridge/issues/2192

**Comment by VenelinMartinov** [comment]
Updated the 2192 regression test in https://github.com/pulumi/pulumi-terraform-bridge/pull/2273

Also updated the 2170 repro in https://github.com/pulumi/pulumi-terraform-bridge/pull/2168

**Comment by t0yv0** [comment]
In my understanding yes, it got fixed. Appreciate help getting the regression test in! 🙏
