### ISSUE TITLE
Installation instructions: Apply default doc edit rules and edit certain headers

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-terraform-bridge#2208]
In https://github.com/pulumi/pulumi-terraform-bridge/pull/2068, we added the ability to emit `docs/` files to the provider that contain the registry's expected top-level installation doc files (`_index.md` and `installation-configuration.md`), as provided by the upstream `index.md` file. 
Since these installation docs are generated separately from the other registry docs, the [default edit rules](https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfgen/edit_rules.go#L26) are not applied via the usual docsgen process. Additionally, we need a few more replaces:
- h/Hashicorp and t/Terraform --> p/Pulumi
- `The following arguments are supported` --> `The following configuration inputs are supported`
- `Argument Reference` --> `Configuration Reference`
- `The foo block contains the following arguments` --> `The foo input has the following nested fields`

Overall, these aim to present a minimal lightweight docs edit pass to make the doc make sense in a Pulumi context.

**Comment by iwahbe** [comment]
@guineveresaenger Can you add a bit more detail here? I know what's going on from this issue, but I don't think someone unfamiliar with #2087 and it's implementation would know.

**Comment by guineveresaenger** [comment]
@iwahbe - these are actually meant to be baked in to the process. We'll add maintainer-provided docs edit rules in another PR.
