### ISSUE TITLE
RenameResourceWithAlias and RenameDataSource should support modern upstream docs structure

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-terraform-bridge#2228]
The update for https://github.com/pulumi/pulumi-mongodbatlas/issues/536 fails `tfgen` with the message 

```
error: failed to gather package metadata: problem gathering data sources: 1 error occurred:
	* could not find docs for data source 'mongodbatlas_x509_authentication_database_user' (aliased or renamed). Override the Docs property in the data source mapping. See type tfbridge.DocInfo for details.
```

But the [upstream doc exists](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/docs/data-sources/x509_authentication_database_user.md), and the `renames` section in `bridge-metadata.json` [was deprecated](https://github.com/pulumi/pulumi-terraform-bridge/pull/1698). Edited to clarify: this was meant to say the bridge metadata's `renames` section does not affect docs discovery.

But then I looked at the release notes and noticed [upstream migrated to new docs structure](https://github.com/mongodb/terraform-provider-mongodbatlas/pull/2425).

It turns out that we [do not support the new docs formate](https://github.com/pulumi/pulumi-terraform-bridge/blob/18db7c57211af0eb7dfa26a70b145edc4d33a88f/pkg/tfbridge/info/rename.go#L90) when finding assigning the docs source for legacy docs.

So what happened with pulumi-mongodbatlas was the following:
1. Upstream renamed docs to end in `.md`
2. Data source `mongodbatlas_x509_authentication_database_user` had been renamed on our end (see entry in bridge-metadata.json)
3. Renames only look for docs sources ending in `.html.markdown` if docs source is nil
4. => Bridge cannot find docs for renamed resources that have docs ending in `.md`.

The workaround for the upgrade is to explicitly name the docs source. However, this means a manual entry in `resources.go` and it also means manual intervention in the upgrade itself. The bridge should handle both docs formats.

**Comment by t0yv0** [comment]
For my 2c, AFAIK "renames" section in bridge-metadata.json has no interaction with documentation processing.
