### ISSUE TITLE
Detailed diff empty collection diffs not shown

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2233]
### What happened?

When an empty collection is added/removed we don't detect a change.

### Example

https://github.com/pulumi/pulumi-terraform-bridge/pull/2159/files

`list added empty` for an example

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Interesting. AS written does not sound particularly troublesome. This behavior can be on the edge of how the user expects this to work. We can prioritize fixes here if we detect some more user impact, or if we have time to pursue completeness and match the ground truth of TF behavior. If we go after it there's likely a distinction to be had on whether the property in question is an Attribute or Block.

I've been able to reproduce here in AWS with a List-nested block:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const config = new pulumi.Config();

const step = config.requireNumber("step");

const lt = new aws.ec2.LaunchTemplate("lt", step === 0 ? {} : {
    blockDeviceMappings: [],
});

export const ltId = lt.id;
```

This doesn't show changes when going from step=0 to step=1.

pulumi about:

```
CLI          
Version      3.124.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.45.0
resource  awsx    2.13.0
resource  docker  4.5.4
resource  docker  3.6.1
language  nodejs  unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in nodejs: executable='/Users/anton/bin/node' version='v18.18.2'

Current Stack: anton-pulumi-corp/pulumi-terraform-bridge-2234/dev

TYPE                                   URN
pulumi:pulumi:Stack                    urn:pulumi:dev::pulumi-terraform-bridge-2234::pulumi:pulumi:Stack::pulumi-terraform-bridge-2234-dev
pulumi:providers:aws                   urn:pulumi:dev::pulumi-terraform-bridge-2234::pulumi:providers:aws::default_6_45_0
aws:ec2/launchTemplate:LaunchTemplate  urn:pulumi:dev::pulumi-terraform-bridge-2234::aws:ec2/launchTemplate:LaunchTemplate::lt


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/anton-pulumi-corp
User           anton-pulumi-corp
Organizations  anton-pulumi-corp, moolumi, demo, pulumi
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/aws     6.45.0
@pulumi/awsx    2.13.0
@pulumi/pulumi  3.126.0
@types/node     18.19.41
typescript      5.5.4

Pulumi locates its logs in /var/folders/gd/3ncjb1lj5ljgk8xl5ssn_gvc0000gn/T/com.apple.shortcuts.mac-helper// by default
```

**Comment by VenelinMartinov** [comment]
The issue here seems to be that not specifying a list/set property still makes pulumi save an empty list to the state.

For blocks this is entirely expected, as TF has no way to represent nil vs empty blocks but for properties we should be able to distinguish the two.

**Comment by VenelinMartinov** [comment]
Added cross-tests here: https://github.com/pulumi/pulumi-terraform-bridge/pull/2405/commits/c8aa486c26f8056ca59f9cb4b96aa2431920a9fc

This seems to be working the same as in terraform, will close as intended behaviour.
