### ISSUE TITLE
Detailed diff duplicated collection diffs

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2234]
### What happened?

Diffs when a non-empty collection is added/removed seem to be duplicated in the detailed diff output.

```
  ~ prov:index/test:Test: (update)
      [id=newid]
      [urn=urn:pulumi:test::test::prov:index/test:Test::mainRes]
    + listProps: [
    +     [0]: "val"
      ]
    + listProps: [
    +     [0]: "val"
      ]
```

### Example

https://github.com/pulumi/pulumi-terraform-bridge/pull/2159/files

`list added` for an example

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Can we construct an AWS-based test case here? I can help.

**Comment by VenelinMartinov** [comment]
Two things:
1. In the test case what happens is the property is changed from null to non-empty, not from empty to non-empty.
2. Had a look at the LaunchTemplate example and I believe this depends on the implementation of Create - if the create returns an empty list when the property is unspecified, the issue does not repro:


```json
{
    "method": "/pulumirpc.ResourceProvider/Create",
    "request": {
        "urn": "urn:pulumi:dev::bridge_2234_aws::aws:ec2/launchTemplate:LaunchTemplate::lt",
        "properties": {
            "__defaults": [
                "name"
            ],
            "name": "lt-da69eeb"
        }
    },
    "response": {
        "id": "lt-015036d7e87cf914d",
        "properties": {
            "arn": "arn:aws:ec2:us-east-1:616138583583:launch-template/lt-015036d7e87cf914d",
            "blockDeviceMappings": [],
            "capacityReservationSpecification": null,
            "cpuOptions": null,
            "defaultVersion": 1,
            "description": "",
            "disableApiStop": false,
            "disableApiTermination": false,
            "ebsOptimized": "",
            "elasticGpuSpecifications": [],
            "elasticInferenceAccelerator": null,
            "enclaveOptions": null,
            "hibernationOptions": null,
            "iamInstanceProfile": null,
            "id": "lt-015036d7e87cf914d",
            "imageId": "",
            "instanceInitiatedShutdownBehavior": "",
            "instanceMarketOptions": null,
            "instanceRequirements": null,
            "instanceType": "",
            "kernelId": "",
            "keyName": "",
            "latestVersion": 1,
            "licenseSpecifications": [],
            "maintenanceOptions": null,
            "metadataOptions": null,
            "monitoring": null,
            "name": "lt-da69eeb",
            "namePrefix": "",
            "networkInterfaces": [],
            "placement": null,
            "privateDnsNameOptions": null,
            "ramDiskId": "",
            "securityGroupNames": [],
            "tagSpecifications": [],
            "userData": "",
            "vpcSecurityGroupIds": []
        }
    },
    "metadata": {
        "kind": "resource",
        "mode": "client",
        "name": "aws"
    }
}
```

This is what happens with LaunchTemplate.

**Comment by VenelinMartinov** [comment]
The issue seems to be fixed in https://github.com/pulumi/pulumi-terraform-bridge/pull/2379 - looks like we are duplicating the diff in the response to the engine in https://github.com/pulumi/pulumi-terraform-bridge/blob/cf59a2592ae7257786c441bf1a85bddad0246940/pkg/tfbridge/provider.go#L1159

**Comment by VenelinMartinov** [comment]
Removed from https://github.com/pulumi/pulumi-terraform-bridge/pull/2379 as out of scope, will revisit later.

**Comment by VenelinMartinov** [comment]
It turns out https://github.com/pulumi/pulumi-terraform-bridge/issues/2294 is not quite enough here.

This fixes lists and sets but we seem to be mishandling maps in MakeTerraformResult: https://github.com/pulumi/pulumi-terraform-bridge/blob/6b95c60de71a628bf0d2dbed288198c9d91474f2/pkg/tfbridge/schema.go#L1011

See test in https://github.com/pulumi/pulumi-terraform-bridge/pull/2405/commits/51dd086ea50354006ac7e202cfb5cdcf8ccea354#diff-5ecbec35cb8a03b89c5be410138532ea2da5904bfd52fdcb604d3b75414a6044R978

Nil and empty maps are both represented as an empty map by MakeTerraformResult. Should be fixable.

**Comment by VenelinMartinov** [comment]
Actually it turns out the nullness of maps is lost by PlanResourceChange here: https://github.com/pulumi/pulumi-terraform-bridge/blob/95cc5de467928c28a88d921f7b2e1ed1ce2a6adb/pkg/tfshim/sdk-v2/provider2.go#L278

both prop and cfg there contain `cty.NullVal(cty.Map(cty.String))` but PRC returns `"map_prop":cty.MapValEmpty(cty.String)`

**Comment by VenelinMartinov** [comment]
this is all sidestepped if we only return the bottom-most property which has a diff, instead of all the properties in the tree - this works so much better.
