### ISSUE TITLE
pulumi-openstack panics in provider config: cty.GetRawConfig returns cty.NullVal

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-terraform-bridge#2259]
### What happened?

Terraform provider openstack [uses cty.ResourceData.GetRawConfig()](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/82c7804c30b5272ed2c1223c7809c327c792565b/openstack/util.go#L333) to look up config (and other) keys.

This causes the pulumi-openstack provider to [panic on Configure.](https://github.com/pulumi/pulumi-openstack/issues/654)

### Example

See https://github.com/pulumi/pulumi-openstack/issues/654.

Try to `pulumi up` with any resource.

### Output of `pulumi about`

```
CLI          
Version      3.126.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME       VERSION
language  nodejs     unknown
resource  openstack  4.0.0-alpha.0+dev

Host     
OS       darwin
Version  13.5
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v21.6.0'

Current Stack: guinevere-pulumi-corp/openstack-654/dev

TYPE                        URN
pulumi:pulumi:Stack         urn:pulumi:dev::openstack-654::pulumi:pulumi:Stack::openstack-654-dev
pulumi:providers:openstack  urn:pulumi:dev::openstack-654::pulumi:providers:openstack::default_4_0_0_alpha_0_dev


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/guinevere-pulumi-corp
User           guinevere-pulumi-corp
Organizations  guinevere-pulumi-corp, pulumi
Token type     personal

Dependencies:
NAME               VERSION
@pulumi/openstack  4.1.0
@pulumi/pulumi     3.127.0
@types/node        18.19.42
typescript         5.5.4
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Closing in favour of https://github.com/pulumi/pulumi-terraform-bridge/issues/2262
