### ISSUE TITLE
Disentangle deciding DiffResponse from detailedDiff

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#2293]
This interaction between detailedDiff and DiffResponse needs to be removed:

https://github.com/pulumi/pulumi-terraform-bridge/blob/46d7e984a47432157ca5476a043269266a18015c/pkg/tfbridge/provider.go#L1122

Resolves: https://github.com/pulumi/pulumi-terraform-bridge/issues/1501

This will undo: https://github.com/pulumi/pulumi-terraform-bridge/pull/1502

Assumes PlanResourceChange is enabled for roll-out. This change should be flagged together with the other changes for the accurate preview work.

Undoing the change risks regressing two important customer-visible behaviors, epic will have tasks to follow up so we have solutions for these:

- https://github.com/pulumi/pulumi-aws/pull/2944 - do not ignore adding an empty tag in AWS
- https://github.com/pulumi/pulumi-gcp/issues/1275 - issues with adding/removing GCP labels

Out of scope:

- markWronglyTypedMaxItemsOneStateDiff continues to edit diff results for now; this is out of scope as it does not
  interact with detailedDiff https://github.com/pulumi/pulumi-aws/issues/3092

- similarly this code may remain:
  https://github.com/pulumi/pulumi-terraform-bridge/blob/46d7e984a47432157ca5476a043269266a18015c/pkg/tfbridge/provider.go#L1177

**Comment by VenelinMartinov** [comment]
I've hit this in pulumi-azure while rolling out PRC: https://github.com/pulumi/pulumi-azure/issues/2322#issuecomment-2297073944

One of the tests produces a diff due to https://github.com/pulumi/pulumi-terraform-bridge/blob/46d7e984a47432157ca5476a043269266a18015c/pkg/tfbridge/provider.go#L1122

The diff has no details and no explanation and should not be there as the stack has had no changes.

**Comment by VenelinMartinov** [comment]
The diff decision referring to the detailed diff was introduced here: https://github.com/pulumi/pulumi-terraform-bridge/pull/1502

The related provider issues are:
- https://github.com/pulumi/pulumi-gcp/pull/1309, issue: https://github.com/pulumi/pulumi-terraform-bridge/issues/1491
- https://github.com/pulumi/pulumi-aws/pull/2944

**Comment by VenelinMartinov** [comment]
fixed in https://github.com/pulumi/pulumi-terraform-bridge/pull/2379
