### ISSUE TITLE
Test: confirm AWS does not regress on adding empty tags

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#2302]
Per https://github.com/pulumi/pulumi-terraform-bridge/issues/2293 this may undo functionality AWS relies on. Confirm that that the bridged providers have a solution here that does not regress.

**Comment by VenelinMartinov** [comment]
Ran the existing test suite with the latest bridge Accurate Preview enabled and have confirmed this also works as expected.
