### ISSUE TITLE
Test: confirm GCP does not regress on handling labels

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#2303]
Per https://github.com/pulumi/pulumi-terraform-bridge/issues/2293 the epic may regress handling GCP labels. Task to confirm that we have a solution here that does not degrade the GCP behavior.

**Comment by VenelinMartinov** [comment]
Ran the existing test suite with the latest bridge Accurate Preview enabled and have confirmed this works as expected.
