### ISSUE TITLE
pulumi import emits type checking warnings "Unexpected type at field "tags.__defaults"

### ISSUE THREAD

**Issue by Zaid-Ajaj** [pulumi/pulumi-terraform-bridge#2308]
### What happened?

When importing AWS using `pulumi import`, resources are imported into the state, however they emit type check warnings:
```
  aws:ec2:RouteTable (...):
    warning: Type checking failed: 
    warning: Unexpected type at field "tags.__defaults":
               expected string type, got [] type
```
This happens for many resources. It looks like we shouldn't type check _internal_ properties that start with `__` 

### Example

N/A

### Output of `pulumi about`

Pulumi v3.128.0

### Additional context

Issue reported by user of the pulumi importer tool https://github.com/Zaid-Ajaj/pulumi-tool-importer/issues/2#issuecomment-2284794698

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Similarly when importing AWS lambda function:
```
  aws:lambda:Function (EnrichmentLambda3D6CE785):
    warning: Type checking failed: 
    warning: Unexpected type at field "environment.variables.__defaults":
               expected string type, got [] type
```

**Comment by iwahbe** [comment]
This looks like https://github.com/pulumi/pulumi-terraform-bridge/issues/2096. @Zaid-Ajaj What version of AWS are you using?
