### ISSUE TITLE
Type checking failure -- "skipMetadataApiCheck"

### ISSUE THREAD

**Issue by AshTharappel** [pulumi/pulumi-terraform-bridge#2339]
### What happened?

getting this warning. the argument passed in is a boolean type, but the check thinks its a string

this is on the `AWS.Provider` resource

```
    warning: Type checking failed:
    warning: Unexpected type at field "skipMetadataApiCheck":
               expected boolean type, got string type
    warning: Type checking is still experimental. If you believe that a warning is incorrect,
    please let us know by creating an issue at https://github.com/pulumi/pulumi-terraform-bridge/issues.
    This will become a hard error in the future. 
```

### Example

here is the code block we are using to create the provider

```ts
  const provider = new Provider(accountName, {
    region: 'us-east-1',
    assumeRole: {
      roleArn: `arn:aws:iam::${accountId}:role/${roleName}`,
      sessionName: `${accountName}-session`,
    },
    skipCredentialsValidation: true,
    skipMetadataApiCheck: true,
    skipRegionValidation: true,
    skipRequestingAccountId: true,
  });
```

### Output of `pulumi about`

```
CLI
Version      3.129.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.50.0
language  nodejs  unknown
resource  random  4.16.3

Host
OS       darwin
Version  14.5
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v22.6.0'

Backend
Name           mm-tharappela3
URL            s3://rs-pulumi-state-852480429243
User           ashwin.tharappel
Organizations
Token type     personal

Dependencies:
NAME                VERSION
@pulumi/aws         6.50.0
@pulumi/pulumi      3.129.0
@rs-crossguard/aws  0.1.7
@rs-pulumi/aws      1.1.3
@ws-pulumi/aws      0.0.21
rs-accounts         1.1.1
@types/jest         29.5.12
@types/node         22.5.0
gts                 5.3.1
jest                29.7.0
ts-jest             29.2.4
typescript          5.5.4

Pulumi locates its logs in /var/folders/0n/0llmscvn1z7b6h4cq2qr31d40000gq/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @AshTharappel. Thanks for raising the issue. We will take a look shortly.

---

I have been able to reproduce with this program:

```ts
import * as aws from "@pulumi/aws";

new aws.Provider("test", { skipMetadataApiCheck: true })
```

**Comment by iwahbe** [comment]
Some [investigation](https://pulumi.slack.com/archives/C02FXTZEZ6W/p1726821174978319) suggests that this is caused by JSON encoding config values. We need to move the type checker to *after* we decode incoming config values.

**Comment by iwahbe** [comment]
@guineveresaenger I know that you have made some progress diagnosing the issue. Can you share that here?

**Comment by guineveresaenger** [comment]
I'm still digging but:

- This warning pops up on Typescript code but not YAML. This indicates a potential issue with JSON Config Encoding. It also means we can't use YAML-based tests for this bug.
- A GRPC log output of `/pulumirpc.ResourceProvider/Configure` looks _identical_ for both YAML and Typescript, which frustratingly seems to mean we _also_ can't use replay-based tests for this bug(?)
- I've bisected the change and tracked it down to [this commit](https://github.com/pulumi/pulumi-terraform-bridge/pull/2310/files#diff-e64befd9e6de5ec01f7f5eac9b8ad568054c4a7a31e40de7a98ad37cefc1e62f). A few of the breadcrumb links in that PR have gone stale, and that particular code seems to have been moved around since then, living in `typechecker.go` I belive.

I'm still not entirely clear what the mismatch is so if anyone has insights or hints on where to look next, please share.

Here's some debugs from various inputs:

`p. info.Config` (maps TF name to pulumi schema information) - the "boolean" type is set in the AWS provider.
```
"skip_metadata_api_check": &info.Schema{
               Name:                     "",
               CSharpName:               "",
               Type:                     "boolean",
               OmitType:                 false,
               AltTypes:                 nil,
               NestedType:               "",
               Transform:                info.Transformer {...},
               Elem:                     (*info.Schema)(nil),
               Fields:                   {},
               Asset:                    (*info.AssetTranslation)(nil),
               Default:                  (*info.Default)(nil),
               Stable:                   (*bool)(nil),
               MaxItemsOne:              (*bool)(nil),
               SuppressEmptyMapElements: (*bool)(nil),
               MarkAsComputedOnly:       (*bool)(nil),
               MarkAsOptional:           (*bool)(nil),
               DeprecationMessage:       "",
               ForceNew:                 (*bool)(nil),
               ForcesProviderReplace:    (*bool)(nil),
               Removed:                  false,
               Omit:                     false,
               Secret:                   (*bool)(nil),
               TypeName:                 (*string)(nil),
           },
```

`news` after unmarshaling:
```
       news=resource.PropertyMap{
           "region": {
               V:  "us-west-2",
           },
           "skipCredentialsValidation": {},
           "skipMetadataApiCheck":      {
               V:  "true",
           },
           "skipRegionValidation": {
               V:  bool(true),
           },
           "version": {
               V:  "6.0.0-alpha.0+dev",
           },
       }
```

Configure method JSON:

```
{
  "method": "/pulumirpc.ResourceProvider/Configure",
  "request": {
    "variables": {
      "aws:config:region": "us-west-2",
      "aws:config:skipCredentialsValidation": "false",
      "aws:config:skipMetadataApiCheck": "true",
      "aws:config:skipRegionValidation": "true"
    },
    "args": {
      "region": "us-west-2",
      "skipCredentialsValidation": "false",
      "skipMetadataApiCheck": "true",
      "skipRegionValidation": "true",
      "version": "6.0.0-alpha.0+dev"
    },
    "acceptSecrets": true,
    "acceptResources": true,
    "sendsOldInputs": true,
    "sendsOldInputsToDelete": true
  },
  "errors": [
    "rpc error: code = Canceled desc = grpc: the client connection is closing"
  ],
  "metadata": {
    "kind": "resource",
    "mode": "client",
    "name": "aws"
  }
}
```
(minus the `version` field, this is identical to running the program with YAML)

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/pull/2310/files#diff-e64befd9e6de5ec01f7f5eac9b8ad568054c4a7a31e40de7a98ad37cefc1e62f commit fixed a bug that didn't used to check boolean types at all, but is now checking them. Looks like it uncovered a latent bug? Reverting that puts https://github.com/pulumi/pulumi-aws/issues/4342 back on the table which would be unfortunate.

**Comment by guineveresaenger** [comment]
addendum:

`news` with a YAML program after unmarshaling:

```
news=resource.PropertyMap{
 "skipMetadataApiCheck": {
     V:  bool(true),
 },
}
```

`news` with a TypeScript program after unmarshaling:
```
news=resource.PropertyMap{
           "region": {
               V:  "us-west-2",
           },
           "skipCredentialsValidation": {},
           "skipMetadataApiCheck":      {
               V:  "true",
           },
           "skipRegionValidation": {
               V:  bool(true),
           },
           "version": {
               V:  "6.0.0-alpha.0+dev",
           },
       }
```

This points to the unmarshaling being the issue. => JSON Config Encoding if I'm not mistaken.
It's odd that the other fields are not set at all - how much special treatment is this config field getting?

**Comment by t0yv0** [comment]
Yeah JSON Config Encoding does not respect type overrides.

**Comment by t0yv0** [comment]
That seems to be the problem here. It consults config shim.SchemaMap over here:

```
https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfbridge/config_encoding.go#L45
```

And it decides it's dealing with a string type. It is ignoring the type override from `configInfos map[string]*SchemaInfo`.

I am still working on removing the need for config-encoding from the product, so instead of a comprehensive fix we may opt for fixing this problem for booleans only and backlogging the rest, until config-encoding can be completely removed.

**Comment by guineveresaenger** [comment]
What makes `skipMetadataApiCheck` special though? It seems a very localized issue.

**Comment by t0yv0** [comment]
This is the rare case of using info.Schema{Type: "boolean"} flag to make an intentional change between the type in TF and the type in Pulumi.
