### ISSUE TITLE
Schema contains non-converted tf example

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi-terraform-bridge#235]
The schema for a resource in the alicloud package in the branch [`go-examples-2`](https://github.com/pulumi/pulumi-alicloud/blob/go-examples-2/provider/cmd/pulumi-resource-alicloud/schema.json) seems to have somehow gotten the raw TF example included in its resource description. This was tripping up the examples parsing code in the resource docs for which pulumi/pulumi#4950 was opened and fixed with pulumi/pulumi#5002.

Here's the resource description that is the source of the panic reported in 4950:

`
The topic is the basic unit of Datahub data source and is used to define one kind of data or stream. It contains a set of subscriptions. You can manage the datahub source of an application by using topics. [Refer to details](https://help.aliyun.com/document_detail/47440.html).\n\n{{% examples %}}\n## Example Usage\n\nBasic Usage\n\n- BLob Topic\n\n  ```\nresource \"alicloud_datahub_topic\" \"example\" {\n  name         = \"tf_datahub_topic\"\n  project_name = \"tf_datahub_project\"\n  record_type  = \"BLOB\"\n  shard_count  = 3\n  life_cycle   = 7\n  comment      = \"created by terraform\"\n}\n  ```\n- Tuple Topic\n\n  ```\nresource \"alicloud_datahub_topic\" \"example\" {\n  name         = \"tf_datahub_topic\"\n  project_name = \"tf_datahub_project\"\n  record_type  = \"TUPLE\"\n  record_schema = {\n    bigint_field    = \"BIGINT\"\n    timestamp_field = \"TIMESTAMP\"\n    string_field    = \"STRING\"\n    double_field    = \"DOUBLE\"\n    boolean_field   = \"BOOLEAN\"\n  }\n  shard_count = 3\n  life_cycle  = 7\n  comment     = \"created by terraform\"\n}\n  ```\n{{% /examples %}}
`

The exact line that caused the panic is right after the second new-line character after `- Tulpe Topic`, i.e. a whitespace character just before the code fence.

**Comment by lukehoban** [comment]
@praneetloke Is this still an issue?  I'm unclear how to verify it - is there a link to the malformed docs on www.pulumi.com?

**Comment by praneetloke** [comment]
The root issue was that the unconverted example caused a panic as described in https://github.com/pulumi/pulumi/issues/4950. That was addressed with the PR I linked in the issue description. I opened this issue to track the core problem of the unconverted example.

**Comment by lukehoban** [comment]
I do not see that malformed example in `master`, and I'm honestly not sure what the linked branch represents (is that some work that is still in progress somewhere)?  Sounds like we can close this?

**Comment by praneetloke** [comment]
Yeah I don't have any other instances of this problem. It also appears that the resource that had this problem in the `alicloud` package no longer has the `description` property in the schema. Not sure what happened there. Since there are no other reports of this problem, I am fine with closing it.
