### ISSUE TITLE
Cannot use lists of empty objects in cross-tests

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2365]
### What happened?

Due to a limitation in https://github.com/hashicorp/terraform-plugin-go, `tftypes` can not represent types with empty objects, like list of empty object.

This is due to https://github.com/hashicorp/terraform-plugin-go/blob/2749aa5cd6408d893abbb38c5ace1fb7d8b7c522/tftypes/object.go#L76

```go
...	
    if v.AttributeTypes == nil || o.AttributeTypes == nil {
		// when doing exact comparisons, we can't compare types that
		// don't have attribute types set, so we just consider them not
		// equal
		return false
	}
...
```

This prevents us from testing useful things in cross-tests, like testing collection-only diffs: https://github.com/pulumi/pulumi-terraform-bridge/blob/4c5493a410cb50563cd22fdfe0b6a95112c00c72/pkg/tfbridge/diff_test.go#L2125

We should consider forking the library for use in cross-tests. We can use it with a different name to limit the scope of its usage to just the assertion code.

### Example

```go
tftypes.NewValue(
	tftypes.List{ElementType: tftypes.Object{}},
	[]tftypes.Value{
		tftypes.NewValue(
			tftypes.Object{},
			map[string]tftypes.Value{},
		),
	},
)
```

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
@VenelinMartinov We now write cross-tests with `cty.Value`s, which can represent an empty object. Can we close this issue?

**Comment by VenelinMartinov** [comment]
@iwahbe yeah, should be fine now
