### ISSUE TITLE
Updating provider config across terraform-bridge providers

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform-bridge#239]
We have had a few interrelated issues related to how provider configuration is managed in state - generally in these buckets:
* Sensitive values from the environment can get picked up and stored in the state file in plain text
* Transient configuration can get stored in the state and attempt to be used in a distant future `destroy` or `refresh`
* We have added `DiffConfig` support to allow for marking provider configuration as requiring replacement, and need to be clear on exactly when it is appropriate to do so.

To address these concerns holistically, we are proposing the following changes to how we map config for terraform-providers:
* By default, for new providers, we will not add any entries to the `Config` block in the `ProviderInfo`.  This will mean that environment variables won't be picked up as explicit inputs to provider config (and thus won't be stored in state), and also won't populate the corresponding `prov.config.setting` values accessible from the program.  Values passed explicitly as provider configuration (not implicitly via environment variables) will still be stored in config and be available via `.config.`.  Additionally, it will still be possible to use environment variables for implicit configuration in all the same ways, and will be documented in the same places.
* If the property is truly part of the identity of all resources manageable by the provider (like AWS `region` or Azure `environment`) we will keep it in the `Config` block, it will get stored in the state file, it will be used by future `destroy`/`refresh`, and we will mark as forcing replacement in the `DiffConfig` implementation
* For existing providers, we will keep things in the `Config` section if they are already there *unless* they are "transient" (the values can change between deployments for example on different machines in common usage, such as an API key or an AWS profile).  For such properties, we will remove them from the `Config` section, which will avoid these values being stored in state by future updates if set via environment variables.  This will also be a very slight breaking change in that the values of `.config.xyz` properties will no longer be populated from environment variables.  We will note this change in CHANGELOGs, but believe it is low enough impact and critical enough for security and correctness to not require a major version bump.

**Comment by stack72** [comment]
Closing this out as it was fixed a long time ago
