### ISSUE TITLE
MaxItems == 1 schema types aren't optional

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-terraform-bridge#24]
We project set schemas with MaxItems == 1 as scalars. If all properties of such a set schema are optional, however, we do not project that scalar as optional. I believe we should.

The `viewerCertificate` property on AWS's `cloudfront.Distribution` type is a prime example.

**Comment by lukehoban** [comment]
This hasn't come up again and has had surprisingly small impact in practice.  Closing out until/unless we hit again to bump the priority.
