### ISSUE TITLE
Detailed diff shows diff on __defaults when number of elements changes

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2400]
### What happened?

When adding/removing elements from a block type we seem to display a diff on the `__defaults`:

```
  ~ prov:index/test:Test: (update)
      [id=newid]
      [urn=urn:pulumi:test::test::prov:index/test:Test::mainRes]
    ~ listBlocks: [
        ~ [0]: {
                + __defaults: []
                  prop      : "val1"
              }
        ~ [1]: {
                + __defaults: []
                  prop      : "val2"
              }
        + [2]: {
                + prop      : "val3"
              }
      ]
```

### Example

https://github.com/pulumi/pulumi-terraform-bridge/pull/2398
`list block element added back`

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
This one is not an issue with the detailed diff calculation:

```
detailedDiff=map[string]*pulumirpc.PropertyDiff{
           "maxItemsOneBlock": &pulumirpc.PropertyDiff{
               state:         impl.MessageState{},
               sizeCache:     0,
               unknownFields: nil,
               Kind:          4,
               InputDiff:     false,
           },
           "maxItemsOneBlock.prop": &pulumirpc.PropertyDiff{
               state:         impl.MessageState{},
               sizeCache:     0,
               unknownFields: nil,
               Kind:          4,
               InputDiff:     false,
           },
       }
```

There is no __defaults marked here - instead this seems to be an issue with the news - the block object contains the __defaults key when it looks like  there is no reason for that: https://github.com/pulumi/pulumi-terraform-bridge/blob/6b95c60de71a628bf0d2dbed288198c9d91474f2/pkg/tfbridge/schema.go#L131

Non-top level defaults don't seem to get used anywhere.

Also: https://github.com/pulumi/pulumi-terraform-bridge/blob/6b95c60de71a628bf0d2dbed288198c9d91474f2/pkg/tfbridge/schema.go#L1749 suggests the __defaults are not necessary.

**Comment by VenelinMartinov** [comment]
Perhaps we can remove all empty nested defaults arrays.

**Comment by VenelinMartinov** [comment]
this is all sidestepped if we only return the bottom-most property which has a diff, instead of all the properties in the tree - this works so much better.

**Comment by t0yv0** [comment]
__defaults is a special property used by the bridge and it should never be presented in the diffs AFAIK. It's "about" some other properties. Whether they were populated from a default value or not.
