### ISSUE TITLE
Set up CI for feature flags

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2432]
### What happened?

We roll out bridge features under feature flags and these tend to take a while. We'd like to make sure that new development in the repo does not break these, so we should run CI for each feature flag.

Had some issues with this during https://github.com/pulumi/pulumi-terraform-bridge/issues/1785

### Example

.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Specifically we'd like to run CI on https://github.com/pulumi/home/issues/3560

**Comment by iwahbe** [comment]
We would presumably need to run CI on all permutations of feature flags, since if we run CI with all flags on but our releases don't have all flags on, we would have untested code being released.

**Comment by VenelinMartinov** [comment]
Yeah, all permutations is the plan, or at least the meaningful ones
