### ISSUE TITLE
Run the test suite under a feature flag matrix

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#2434]
One learning from flagged roll-outs like PlanResourceChange is that we should run unit tests under various combinations of flags. This helps make sure that we take full advantage of the tests in this repo. Suggest adding this toward qualifying AccurateBridgePreviews flag.

**Comment by t0yv0** [comment]
@VenelinMartinov sounds like you were planning this already.

**Comment by VenelinMartinov** [comment]
Yeah: https://github.com/pulumi/pulumi-terraform-bridge/issues/2432
