### ISSUE TITLE
panic: can't convert "x86" to cty.Value

### ISSUE THREAD

**Issue by eBeyond** [pulumi/pulumi-terraform-bridge#2445]
### What happened?

When updating the hcloud-provider from 1.19.1 to 1.19.2 this panic occurs:  panic: can't convert "x86" to cty.Value
This error still exists until 1.20.3 and makes it impossible to progress working with it.
As the stacktrace shows the errors to be related to terraform-plugin-sdk and pulumi-terraform-bridge I think that's better located here.
The string "x86" isn't provided by the sourcecode. That means that this value has been provided by pulumi or by some plugins/bridges etc.

### Example

> pulumi preview
Previewing update (main)

                        View in Browser (Ctrl+O): https://app.pulumi.com/eBeyond/sys/main/previews/fc08b5bb-def1-4d4e-9373-039e1c38df70

     Type                                                  Name           Plan       Info
     pulumi:pulumi:Stack                                   sys-main                  32 messages
 ~   ├─ cloudflare:index:ZeroTrustTunnelCloudflaredConfig  tunnel-fw-ext  update     [diff: ~config]
     └─ hcloud:index:Network                               dev                       1 error

Diagnostics:
  pulumi:pulumi:Stack (sys-main):
    panic: can't convert "x86" to cty.Value
    goroutine 46 [running]:
    github.com/hashicorp/terraform-plugin-sdk/v2/internal/configs/hcl2shim.HCL2ValueFromConfigValue({0x10500d6e0?, 0x1052cf880?})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240520223432-0c0bf0d65f10/internal/configs/hcl2shim/values.go:231 +0x31c
    github.com/hashicorp/terraform-plugin-sdk/v2/internal/configs/hcl2shim.HCL2ValueFromConfigValue({0x105091be0?, 0x14000412180?})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240520223432-0c0bf0d65f10/internal/configs/hcl2shim/values.go:225 +0x354
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.HCL2ValueFromConfigValue(...)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240520223432-0c0bf0d65f10/helper/schema/exports.go:15
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.makeResourceRawConfigClassic(0x1400071f288?, 0x105091be0?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.87.0/pkg/tfshim/sdk-v2/cty.go:57 +0x34
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.makeResourceRawConfig(0x140003fd4a0, 0x1400042c8d0?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.87.0/pkg/tfshim/sdk-v2/cty.go:50 +0xf4
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.ReadDataDiff({0x14000161e60?, {0x1400007ca20?, 0x0?, 0xffffffffffffffff?}}, {0x1052e37e8, 0x14000257380}, {0x104cd0d3b, 0xc}, {0x1052d3ce0?, 0x140003fd4a0})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.87.0/pkg/tfshim/sdk-v2/provider.go:171 +0x9c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Invoke(0x14000027980, {0x1052e37e8?, 0x140002568d0?}, 0x140003ff240)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.87.0/pkg/tfbridge/provider.go:1680 +0x868
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Invoke(0x140005dd920, {0x1052e37e8, 0x140002568d0}, 0x140003ff240)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:342 +0x120
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler.func1({0x1052e37e8, 0x140002568d0}, {0x1051b6c60?, 0x140003ff240})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.124.0/proto/go/provider_grpc.pb.go:558 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x1052e37e8, 0x14000256660}, {0x1051b6c60, 0x140003ff240}, 0x14000434200, 0x140006f63c0)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler({0x10528fc00?, 0x140005dd920}, {0x1052e37e8, 0x14000256660}, 0x14000822980, 0x14000554de0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.124.0/proto/go/provider_grpc.pb.go:560 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x1400020fc00, {0x1052e37e8, 0x140002565d0}, {0x1052ee980, 0x140001e8a80}, 0x140006fe000, 0x14000693530, 0x105d6ef98, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xba0
    google.golang.org/grpc.(*Server).handleStream(0x1400020fc00, {0x1052ee980, 0x140001e8a80}, 0x140006fe000)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0xc80
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8c
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 55
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x150

  hcloud:index:Network (dev):
    error: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59049: connect: connection refused"

### Output of `pulumi about`

`
> pulumi about
CLI
Version      3.134.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  cloudflare  5.39.0
resource  command     1.0.1
resource  github      6.3.0
resource  gitlab      8.4.0
resource  hcloud      1.19.2
language  python      3.134.0
resource  vault       6.3.0

Host
OS       darwin
Version  15.0
Arch     arm64

This project is written in python: executable='/Users/mende/_Privat/infra_sys/infra/sys/.venv/bin/python' version='3.12.6'

Current Stack: eBeyond/sys/main

TYPE                                                                                URN
pulumi:pulumi:Stack                                                                 urn:pulumi:main::sys::pulumi:pulumi:Stack::sys-main
pulumi:providers:cloudflare                                                         urn:pulumi:main::sys::pulumi:providers:cloudflare::default_5_39_0
cloudflare:index/record:Record                                                      urn:pulumi:main::sys::cloudflare:index/record:Record::fw-ext-de
pulumi:providers:hcloud                                                             urn:pulumi:main::sys::pulumi:providers:hcloud::default_1_19_1
hcloud:index/network:Network                                                        urn:pulumi:main::sys::hcloud:index/network:Network::dev
hcloud:index/network:Network                                                        urn:pulumi:main::sys::hcloud:index/network:Network::prod
hcloud:index/network:Network                                                        urn:pulumi:main::sys::hcloud:index/network:Network::core
cloudflare:index/zeroTrustTunnelCloudflaredConfig:ZeroTrustTunnelCloudflaredConfig  urn:pulumi:main::sys::cloudflare:index/zeroTrustTunnelCloudflaredConfig:ZeroTrustTunnelCloudflaredConfig::tunnel-fw-ext
hcloud:index/server:Server                                                          urn:pulumi:main::sys::hcloud:index/server:Server::fw
pulumi:providers:vault                                                              urn:pulumi:main::sys::pulumi:providers:vault::default_6_3_0
vault:jwt/authBackend:AuthBackend                                                   urn:pulumi:main::sys::vault:jwt/authBackend:AuthBackend::gitlab
vault:index/policy:Policy                                                           urn:pulumi:main::sys::vault:index/policy:Policy::vault-policy-cluster-core
vault:index/authBackend:AuthBackend                                                 urn:pulumi:main::sys::vault:index/authBackend:AuthBackend::k8s_prod
hcloud:index/server:Server                                                          urn:pulumi:main::sys::hcloud:index/server:Server::mail-gw
vault:index/policy:Policy                                                           urn:pulumi:main::sys::vault:index/policy:Policy::cert-manager
hcloud:index/server:Server                                                          urn:pulumi:main::sys::hcloud:index/server:Server::srv01
vault:index/authBackend:AuthBackend                                                 urn:pulumi:main::sys::vault:index/authBackend:AuthBackend::approle
hcloud:index/serverNetwork:ServerNetwork                                            urn:pulumi:main::sys::hcloud:index/serverNetwork:ServerNetwork::fw_dev
hcloud:index/serverNetwork:ServerNetwork                                            urn:pulumi:main::sys::hcloud:index/serverNetwork:ServerNetwork::fw_prod
hcloud:index/serverNetwork:ServerNetwork                                            urn:pulumi:main::sys::hcloud:index/serverNetwork:ServerNetwork::fw_core
hcloud:index/serverNetwork:ServerNetwork                                            urn:pulumi:main::sys::hcloud:index/serverNetwork:ServerNetwork::mail-gw_core
hcloud:index/serverNetwork:ServerNetwork                                            urn:pulumi:main::sys::hcloud:index/serverNetwork:ServerNetwork::srv01_core
vault:appRole/authBackendRole:AuthBackendRole                                       urn:pulumi:main::sys::vault:appRole/authBackendRole:AuthBackendRole::vault-backend-auth-role-core-srv01

Found no pending operations associated with main

Backend
Name           pulumi.com
URL            https://app.pulumi.com/xy
User           xy
Organizations  xy, yz
Token type     personal

Dependencies:
NAME               VERSION
pip                24.2
pulumi_cloudflare  5.39.0
pulumi_command     1.0.1
pulumi_github      6.3.0
pulumi_gitlab      8.4.0
pulumi_hcloud      1.19.2
pulumi_vault       6.3.0
pydantic           2.9.2
python-gitlab      4.11.1
setuptools         75.1.0

Pulumi locates its logs in /var/folders/2c/lc6pbx5s5ys5nxsdj9qbkrrr0000gn/T/ by default
`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
hi @eBeyond, thank you for opening this issue. We're sorry you're running into trouble.

Please provide us with a complete, runnable sample program that reproduces this behavior so we can root cause this behavior and provide you with a solution. We'd also need the steps you took in

It looks like this is a duplicate of https://github.com/pulumi/pulumi-hcloud/issues/575, and we'd struggled reproducing the panic on our end. It sounded like a `pulumi refresh` had resolved your immediate issues. Nonetheless, we'd like to not show a panic of course.

Could you additionally clarify for us:

- does this panic happen while trying to upgrade? Or does it happen when you're trying to provision a Network on hcloud v1.20? Any other scenarios?

**Comment by eBeyond** [comment]
Ok, I've debugged on my own, as it was not possible to create a code which reproduces it. But I think it will be possible now. And I think it's not an issue with the bridge. As such I'll close it now and reopen (if possible) or create a new one on the hcloud provider.
