### ISSUE TITLE
terraform-plugin-sdk/v2

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-terraform-bridge#245]
The V2 of the terraform-plugin-sdk needs to be supported so that we can upgrade to v3.2.0 of the AWS Terraform Provider

There are some breaking changes in this version of the SDK so we need to run this as a branch alongside master for now

**Comment by pgavlin** [comment]
The current plan is to shim out the functionality that is needed from the TF plugin SDK, then implement the shim for both the v1 and v2 SDKs. Implementing the v2 SDK will require copying and pasting some code from the plugin SDK itself, as the implementation requires code that the SDK does not publicly expose. The primary challenge with respect to the shim is updating the dependent components, including tf2pulumi.

In the longer term, we should consider reimplementing the shimmed functionality on top of the TF gRPC plugin API itself, which should better insulate us from taking dependencies on internal libraries.
