### ISSUE TITLE
Specific field isnt triggering update endpoint or showing diffs.

### ISSUE THREAD

**Issue by KnockOutEZ** [pulumi/pulumi-terraform-bridge#2454]
Hey everyone,

I've encountered an issue with a Pulumi provider I built using pulumi-terraform-bridge. The provider isn't showing diffs for changes in a specific field when I try to update using `pulumi up`. This is happening despite the underlying Terraform provider working correctly.

The field in question is a list of nested attributes called "nodes" in my database resource. Here's a simplified version of the schema:

```go
"nodes": schema.ListNestedAttribute{
    Computed: true,
    Optional: true,
    NestedObject: schema.NestedAttributeObject{
        Attributes: map[string]schema.Attribute{
            "name": schema.StringAttribute{
                Computed: true,
                Optional: true,
            },
            // ... other nested attributes ...
        },
    },
},
```

Normally, adding or removing an item like `{name: "new_node"}` in this array should trigger an update. However, the Pulumi provider doesn't seem to detect any changes to the "nodes" field at all.

I've confirmed that the nodes are being saved correctly, but Pulumi isn't recognizing the changes. I'm using terraform-plugin-framework to build my Terraform provider.

A couple of questions:

1. Could this be related to the use of custom plan modifiers like `conditionalUseStateForUnknownModifier`?
2. Does pulumi-terraform-bridge support custom plan modifiers from terraform-plugin-framework?

Has anyone encountered similar issues or have suggestions on how to troubleshoot this? Any insights would be greatly appreciated!

**Comment by KnockOutEZ** [comment]
This is the full portion for the nodes resource schema:
```
 "nodes": schema.ListNestedAttribute{
                 Description: "List of nodes in the database.",
                 Computed:    true,
                 Optional:    true,
                 NestedObject: schema.NestedAttributeObject{
                     Attributes: map[string]schema.Attribute{
                         "name": schema.StringAttribute{
                             Computed: true,
                             Optional: true,
                         },
                         "connection": schema.SingleNestedAttribute{
                             Computed: true,
                             PlanModifiers: []planmodifier.Object{
                                 objectplanmodifier.UseStateForUnknown(),
                             },
                             Attributes: map[string]schema.Attribute{
                                 "database":            schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "host":                schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "password":            schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "port":                schema.Int64Attribute{Computed: true, PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
                                 "username":            schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "external_ip_address": schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "internal_ip_address": schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "internal_host":       schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                             },
                         },
                         "location": schema.SingleNestedAttribute{
                             Computed: true,
                             PlanModifiers: []planmodifier.Object{
                                 objectplanmodifier.UseStateForUnknown(),
                             },
                             Attributes: map[string]schema.Attribute{
                                 "code":        schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "country":     schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "latitude":    schema.Float64Attribute{Computed: true, PlanModifiers: []planmodifier.Float64{float64planmodifier.UseStateForUnknown()}},
                                 "longitude":   schema.Float64Attribute{Computed: true, PlanModifiers: []planmodifier.Float64{float64planmodifier.UseStateForUnknown()}},
                                 "name":        schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "region":      schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "region_code": schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "timezone":    schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "postal_code": schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "metro_code":  schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "city":        schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                             },
                         },
                         "region": schema.SingleNestedAttribute{
                             Computed: true,
                             PlanModifiers: []planmodifier.Object{
                                 objectplanmodifier.UseStateForUnknown(),
                             },
                             Attributes: map[string]schema.Attribute{
                                 "active":             schema.BoolAttribute{Computed: true, PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()}},
                                 "availability_zones": schema.ListAttribute{Computed: true, ElementType: types.StringType, PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()}},
                                 "cloud":              schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "code":               schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "name":               schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                                 "parent":             schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
                             },
                         },
                         "extensions": schema.SingleNestedAttribute{
                             Computed: true,
                             PlanModifiers: []planmodifier.Object{
                                 conditionalUseStateForUnknownModifier{},
                             },
                             Attributes: map[string]schema.Attribute{
                                 "errors":    schema.MapAttribute{Computed: true, ElementType: types.StringType, PlanModifiers: []planmodifier.Map{mapplanmodifier.UseStateForUnknown()}},
                                 "installed": schema.ListAttribute{Computed: true, ElementType: types.StringType, PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()}},
                             },
                         },
                     },
                 },
             },
 ```


The Terraform provider is in github.com/pgEdge/terraform-provider-pgedge
And the pulumi provider is in github.com/pgEdge/pulumi-pgedge. (sync-v007 branch)

**Comment by VenelinMartinov** [comment]
Hi @KnockOutEZ, thanks for reporting and sorry you've hit this. I'll investigate and get back to you.
The bridge should fully support PlanModifiers AFAIK, this behaviour is not expected.

**Comment by KnockOutEZ** [comment]
> Hi [@KnockOutEZ](https://github.com/KnockOutEZ), thanks for reporting and sorry you've hit this. I'll investigate and get back to you. The bridge should fully support PlanModifiers AFAIK, this behaviour is not expected.

Hey @VenelinMartinov . I did some experiment for fixing this but couldnt sort out the issue. I removed the custom plamodifier but still faced the same thing. So its probably not the planmodifier that caused this issue. I had to move to an object data structure from array to solve this (Which made the overall configuration look very weird as our API isnt designed for the `nodes` to be an array). Let me know if I can further assist on this issue by providing more context or something.

Another thing I want to add that is completely irrelevant to this issue but would be too small to create a new issue for itself. Is there any way to steamline development for the pulumi provider without cutting a release for each change? I had to go through quite some iterations of releases on the Terraform end to fix small stuffs that works just fine with the Terraform provider but breaks for Pulumi. I understand the `pulumi-terraform-bridge` is quite new so these sorta small bugs are expected but cutting a release for each change in Terraform > Updating shim and provider go module > generating new schema and sdk > updating my test project all these steps takes like 20-30+ mins. Opting out the first step will easily boost 10 mins there so if there is a  way to do so please let me know.

Overall quite great development experience so far (Apart from the confusing documentation 😅). Kudos to the development team.

**Comment by VenelinMartinov** [comment]
Thanks for the update @KnockOutEZ 

If I understand correctly, you are asking about the development loop on pulumi providers? There is a way to run a provider without having to go through the release process - if you have the local provider binary on the PATH it will get used by your pulumi program, for example: 
```
PATH=~/code/pulumi-gcp/bin:$PATH pulumi up --yes
```
is what I use for developing the pulumi-gcp provider.

As for the SDK loop, there are ways to use a local SDK, see https://github.com/pulumi/pulumi-gcp/blob/b26ac8aca3908cf193f13268cab41f925d60e8cd/Makefile#L115 for example but you can also use YAML for testing as that does not have an SDK.

We also have a provider testing library, which might be helpful here: https://github.com/pulumi/providertest/tree/main/pulumitest


I hope that's useful and that I've understood you correctly, LMK if that's not the case.

**Comment by VenelinMartinov** [comment]
Hey @KnockOutEZ, I was not able to reproduce the problem so far. In my testing the provider seemed to correctly pick up the changes and updated my resource.

Could you please include GRPC logs of the incorrect run? You can get this by prefixing `PULUMI_DEBUG_GRPC="grpc.json"` to you `pulumi preview` command, like so:

```
PULUMI_DEBUG_GRPC="grpc.json" pulumi preview
```

Thanks!

**Comment by KnockOutEZ** [comment]
Hey @VenelinMartinov we moved to a hashmap structure as the array wasnt working and it fixed the issue. The pulumi version of the transition isnt committed but the terraform version is. This is the commit: https://github.com/pgEdge/terraform-provider-pgedge/commit/3c4c9536bd000a28470ca5c1fd4ea5dc5b7c3109

**Comment by VenelinMartinov** [comment]
Glad to hear you've resolved it @KnockOutEZ. Please let us know if you run into any more issues here.

Also, you might be interested in the community slack: https://slack.pulumi.com/ - there is a `package-authoring` channel, where you might also find help with questions around authoring providers.
