### ISSUE TITLE
Unable to build provider in Github Actions

### ISSUE THREAD

**Issue by smartinellimarco** [pulumi/pulumi-terraform-bridge#2457]
### What happened?

Hey everyone, we encountered an issue while building our bridged provider locally and in GH Actions.

Error: 
```
Error: ../../../../go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfshim/sdk-v2/cty.go:160:14: math.MaxInt64 (untyped int constant 9223372036854775807) overflows uint

Error: The process '/opt/hostedtoolcache/goreleaser-action/2.3.2/x64/goreleaser' failed with exit code 1
```

### Example

https://github.com/splightplatform/pulumi-splight/actions/runs/11129055769/job/30925254910

### Output of `pulumi about`

CLI          
Version      3.134.1
Go Version   go1.23.1
Go Compiler  gc

Host     
OS       darwin
Version  14.6.1
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Hey @smartinellimarco, thanks for reporting and sorry you've hit this.

Are you building on a 32 bit system?
