### ISSUE TITLE
Expose tfgen debugging messages

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi-terraform-bridge#249]
The tfgen code is full of helpful debugging messages e.g. https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfgen/docs.go#L509 but it is unclear how to expose them via the CLI. It's either broken or undocumented and should be fixed accordingly.

**Comment by jkodroff** [comment]
Marking fixed: This has probably been address by previous improvements. Unfortunately, the line Komal is referring to has likely changed number due to other changes to this file.
