### ISSUE TITLE
Strip Output and secret types from detailed diff input

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2526]
The detailed diff algorithm in the bridge does not need to care about secrets as it can not expose these. We should make sure that these are not passed in.

Currently the bridge uses a flag to the engine to say that both Secrets and Outputs are not supported but this might change with https://github.com/pulumi/pulumi-terraform-bridge/issues/1506

**Comment by t0yv0** [comment]
Thank you for logging this. I think it is not a problem as of today (AFAIK), but will become one with https://github.com/pulumi/pulumi-terraform-bridge/issues/1506 so that would be something we need to account for if doing that.

**Comment by VenelinMartinov** [comment]
Turns out this is necessary for PF support, working on a fix in https://github.com/pulumi/pulumi-terraform-bridge/pull/2643
