### ISSUE TITLE
Set element changes in elements with Computed properties don't display correctly

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2528]
Set elements which are objects with computed properties might produce the wrong diff as we can't correctly match the planned state value to the input due to the computed property being added.

related to https://github.com/pulumi/pulumi-terraform-bridge/issues/2281

Example: https://github.com/pulumi/pulumi-terraform-bridge/blob/fae92cbdb980bb32571b1787db3df6f48bdd6e09/pkg/tests/detailed_diff_set_test.go#L2456

Here the resource has an Optional property and an Optional + Computed property.

We initially create it with 
```
{"nested": "a", "computed": "b"}
```

We then preview the change:
```
{"nested": "a"},
{"nested": "a", "computed": "b"},
```

and the output is wrong:

```
    ~ prov:index/test:Test: (update)
        [id=id]
        [urn=urn:pulumi:test::test::prov:index/test:Test::mainRes]
      ~ tests: [
          + [1]: {
                  + computed  : "b"
                  + nested    : "a"
                }
        ]
```

instead of

```
    ~ prov:index/test:Test: (update)
        [id=id]
        [urn=urn:pulumi:test::test::prov:index/test:Test::mainRes]
      ~ tests: [
          + [0]: {
                  + nested    : "a"
                }
        ]
```

**Comment by VenelinMartinov** [comment]
We can try to do better by attempting to hash the elements even if they have computed properties.

Additionally we can attempt to match elements like TF does: https://github.com/opentofu/opentofu/blob/cb2e9119aa75eeb8e1fa175e2b7a205a4fef129f/internal/plans/objchange/objchange.go#L433

**Comment by t0yv0** [comment]
This issue needs an example of what's expected vs what's actual, ideally from a real provider, that'd be very helpful to gauge priority. We discussed this a few times but it still is unclear to me how this manifests. We can keep it around until we find more real examples in providers to cross-link.

**Comment by VenelinMartinov** [comment]
There's a synthetic test in the bridge which shows the problem: https://github.com/pulumi/pulumi-terraform-bridge/blob/fae92cbdb980bb32571b1787db3df6f48bdd6e09/pkg/tests/detailed_diff_set_test.go#L2456

I'll add this to the description.

**Comment by t0yv0** [comment]
This sounds like a blocker to me. This is not at all correct. 

I expect that there are two cases:

1. In the average case, the provider does not actually touch the Computed properties but they are copied from inputs to outputs; in this case we must have this work correctly. 

2. In the (hopefully unusual) case, the provider edits Computed properties and the index lookup fails to find an index to return to the engine. In this case we must fail over to logging what is being added or removed to the logging system instead of rendering it in the detailed diff. 

Can this be achieved?

**Comment by VenelinMartinov** [comment]
Yeah, I'd like to revisit the `match on Pulumi exact value match` strategy. I've observed that the planning process can distort the shape of the values sometimes so this is a bit tricky but it might be easier than recalculating the hash given https://github.com/pulumi/pulumi-terraform-bridge/issues/2609

**Comment by t0yv0** [comment]
The point here is that when we fail to compute an index that will display the correct value in the diff by the engine we should give up rather than sending an incorrect index. We can spill over to info logging I think. Yeah.
