### ISSUE TITLE
Exclude portions of the bridge that don't need test from codecov

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-terraform-bridge#2581]
We currently measure all directories in pulumi-terraform-bridge with codecov but there are several places it doesn't make sense:
- We're including our testing mocks themselves
- There's a few very old/deprecated APIs (eg. pkg/tfshim/tfplugin5) that we don't use and don't plan to test (possibly some of these we should actually delete!)
- We temporarily have 2 copies of the pf code after consolidating go.mod files.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3657
