### ISSUE TITLE
Use the info.DisplayName for the title of the generated installation docs

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-terraform-bridge#2586]
Some providers like https://www.pulumi.com/registry/packages/oci/ or https://www.pulumi.com/registry/packages/junipermist/ don't have a terribly obvious `info.Name` so we'd rather use `info.DisplayName` for things like the title of the installation/configuration pages in the registry.

**Comment by guineveresaenger** [comment]
A point of clarification: `info.Name` should _never_ be used here since it refers to the upstream terraform name.
