### ISSUE TITLE
Go acronyms as down-cased not all caps `Vpc` vs. `VPC`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform-bridge#26]
From @jen20:

> In the Go SDK, all of the acronyms are downcased (e.g. `Vpc`, `Ec2`) - the idiomatic thing in Go is to spell acronyms out in all caps. Was this a conscious decision to match other SDKs or just an artifact of how the provider SDK gets generated?

We should likely use a Go-specific Pascal-casing routine that matches idiomatic Go naming patterns.

**Comment by iwahbe** [comment]
This issue should live in Go's codegen in pulumi/pulumi. I believe that is has been addressed in any case.
