### ISSUE TITLE
Automatically run pulumi refresh after each step

### ISSUE THREAD

**Issue by KnockOutEZ** [pulumi/pulumi-terraform-bridge#2613]
Hey, I'm using the pulumi-terraform-bridge provider in my Pulumi project, and I'm looking for a way to automatically run pulumi refresh after each step, similar to how Terraform automatically refreshes the state.
In Terraform, when you apply changes, it automatically runs terraform refresh to ensure the state file accurately reflects the current infrastructure. This is a helpful behavior that ensures the state is always in sync.
I'd like to see if there's a way to achieve the same behavior in the pulumi-terraform-bridge provider. Is there an option or configuration I can use to automatically run pulumi refresh after each pulumi up or pulumi destroy step?
Alternatively, would it be possible to add this as a feature in a future release of the pulumi-terraform-bridge provider? Having the ability to automatically refresh the state would greatly improve the workflow and help prevent any state drift issues.
Please let me know if you have any suggestions or insights on how I can achieve this. I'm happy to provide more context or work with the team to implement a solution.

**Comment by KnockOutEZ** [comment]
Hey @VenelinMartinov thanks for the reply! Is there any way to enforce this programmatically into the provider so even if the customers dont run `pulumi --refresh` it will still refresh the state by itself.

**Comment by VenelinMartinov** [comment]
Hey, no, we currently have no way to specify that a provider should refresh by default. What is the use case you have for this? Why does the provider you are bridging require --refresh?

**Comment by mjeffryes** [comment]
You could kind of fake it by making a read of the cloud state in check or diff, but it would be hacky since the refreshed state would not be stored. I think ultimately, this just boils down to an ask for: [Consider automatically refreshing on preview/update/destroy· pulumi/2247](https://github.com/pulumi/pulumi/issues/2247), since to do this correctly, it has to be don in the engine
