### ISSUE TITLE
AWS Exclusive Management Resource documentation fails to parse

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#2633]
### What happened?

Checking on some new AWS resources. Markdown files such as this one:

https://github.com/hashicorp/terraform-provider-aws/blob/7a8669e827e3fbe32f436e93ef77a4c58a199751/website/docs/r/iam_role_policy_attachments_exclusive.html.markdown?plain=1#L1

fail to parse quietly.

Debugging I found that:

getDocsForResource

Somewhere around `	doc, err := parseTFMarkdown(g, info, kind, markdownBytes, markdownFileName, rawname) `

We get `doc.Description==""`.

Therefore we only index the import section.

Notably I think we also do not get a build warning about this.

### Example

See above.

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
> Due to the tricky nature of taking over docs from upstream providers, we have a (fairly blanket) policy of eliding content that contains the word "Terraform" which this document does.

Does this emit build-time warnings to track? Is there a way to find the scope of the problem, how many docs pages we are missing in `pulumi-aws`?

**Comment by guineveresaenger** [comment]
Sure does!

For example:
`warning: Found <elided> in description for [aws_iam_role_policy_attachments_exclusive]. The description and any examples will be dropped in the Pulumi provider.`

You can set ` COVERAGE_OUTPUT_DIR` as well, but I'm not sure the logic on those stats is current.

We should definitely reconsider this behavior; we lose a _lot_ of docs this way.

**Comment by t0yv0** [comment]
Appears by design but I'd love if we could fix this systematically and improve documentation yield.
