### ISSUE TITLE
MustTraverseProperties not working as expected when attempting to override plural array fields

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-terraform-bridge#2637]
### What happened?

When attempting to leverage `MustTraverseProperties` to override some behavior that is causing fields to be singularized when I don't want them to be, it doesn't appear it actually works.

For example, I have the expectation that the following should allow me to disable type aware naming.
```
	tfbridge.MustTraverseProperties(&prov, "disable-type-aware-naming",
		func(info tfbridge.PropertyVisitInfo) (tfbridge.PropertyVisitResult, error) {
			p := info.SchemaPath()
			step, ok := p[len(p)-1].(walk.GetAttrStep)
			if !ok {
				return tfbridge.PropertyVisitResult{}, nil
			}

			sInfo := info.SchemaInfo()
			if sInfo.Name != "" {
				return tfbridge.PropertyVisitResult{}, nil
			}
			sInfo.Name = tfbridge.TerraformToPulumiNameV2(step.Name, nil, nil)
			return tfbridge.PropertyVisitResult{HasEffect: true}, nil
		})
```

In practice, this doesn't seem to work as expected. I have several complex nested types that are still being singularized by the bridge when I don't want them to be (ex. ipRanges gets turned to ipRange)

This is related to https://github.com/pulumi/pulumi-terraform-bridge/issues/2606

### Example

See above

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
This is almost certainly related to this call to `inflector.Singularize`:

https://github.com/pulumi/pulumi-terraform-bridge/blob/3561cab8550b2f42fbceceaf8833a6db365f704d/pkg/tfgen/generate_schema.go#L197-L200

This function **should not** be called outside of `tfbridge.TerraformToPulumiNameV2`.

**Comment by iwahbe** [comment]
The underlying issue here is that setting `.Name` does work as designed, in that it fully controls property names. It does not (and is not designed to) control the types associated with property names (which are _based_ on property names).

https://github.com/pulumi/pulumi-terraform-bridge/issues/2606 tracks the underlying problem: type name singularization.
