### ISSUE TITLE
The SDKv2 Bridge swallows resource init errors when run under PlanResourceChange

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2696]
### What happened?

Under PlanResourceChange, the SDKv2 bridge incorrectly returns just an error to the engine in cases where the resource has been partially initialized. It should instead return both the error and the partial state, including the ID so that the engine can save the resource and re-attempt to update it on the next `up`.

References:

PRC:
https://github.com/pulumi/pulumi-terraform-bridge/blob/03b9498b5b9d2ddf743903c8eef9de3436fcae2f/pkg/tfshim/sdk-v2/provider2.go#L350

non-PRC:
https://github.com/pulumi/pulumi-terraform-bridge/blob/180b924b27838e3484a0f867e31fda835fb3ed09/pkg/tfshim/sdk-v2/provider.go#L130

Discovered in https://github.com/pulumi/pulumi-gcp/issues/2700

### Example

Discovered in https://github.com/pulumi/pulumi-gcp/issues/2700

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
This change had to be reverted.
