### ISSUE TITLE
Mongodbatlas provider fails to upgrade to latest bridge with compiler issue about duplicate types

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#2784]
### What happened?

The mongodbatlas pulumi provider fails to upgrade to the latest bridge with the following error:

```
panic: gob: registering duplicate types for "*tfdiags.rpcFriendlyDiag": *tfdiags.rpcFriendlyDiag != *tfdiags.rpcFriendlyDiag

goroutine 1 [running]:
encoding/gob.RegisterName({0x27f939f, 0x18}, {0x2c72760, 0x0})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.linux-amd64/src/encoding/gob/type.go:847 +0x3f4
encoding/gob.Register({0x2c72760, 0x0})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.linux-amd64/src/encoding/gob/type.go:901 +0x1ba
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/vendored/opentofu/tfdiags.init.0()
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.98.1-0.20241223162608-daafe0d49c40/pkg/vendored/opentofu/tfdiags/rpc_friendly.go:69 +0x1c
make: *** [Makefile:257: .make/schema] Error 2
```

This looks related to an old TF plugin sdk issue https://github.com/hashicorp/terraform-plugin-sdk/issues/268

### Example

https://github.com/pulumi/pulumi-mongodbatlas/actions/runs/12470203941/job/34804887453

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Indeed there seems to be a conflict between these two definitions that are getting linked in:

https://github.com/pulumi/terraform-plugin-sdk/blob/4f60ee4e2975c25b88b392e69c87551bb0e26dfc/internal/tfdiags/rpc_friendly.go#L3

and

https://github.com/pulumi/pulumi-terraform-bridge/blob/7917cbd3083d4d759481b80cb2b4f7ac585e251e/pkg/vendored/opentofu/tfdiags/rpc_friendly.go#L70

I wonder if renaming or removing this vendored file from the bridge can move us forward. Checking.
