### ISSUE TITLE
Check runtime types against Terraform schema (JavaScript and Python)

### ISSUE THREAD

**Issue by mmdriley** [pulumi/pulumi-terraform-bridge#28]
See https://github.com/pulumi/pulumi-terraform/issues/38#issuecomment-381775469.

Using plain Javascript (instead of Typescript), users can create resources that violate the Terraform schema but still produce some result.

```javascript
let x = new aws.ec2.SecurityGroup("test1", {
    tags: [
        {
            One: "1",
            Two: "2",
            ThreeFourAndFive: "345",
        },
        {
            Six: "6",
        },
    ],
});
```

Here, `tags` should be an object instead of an array of objects.

We should have enough type information in, e.g., `MakeTerraformInputs` to check that the `PropertyMap` we receive matches the resource schema and to raise an error if it doesn't.

**Comment by ericrudder** [comment]
bumped a tiny bit since it bit james

**Comment by iwahbe** [comment]
The bridge correctly errors on unexpected fields/types.

**Comment by t0yv0** [comment]
@iwahbe can you show some confirmation what is the current bridge behavior? I don't believe this is addressed as yet but seems fairly similar to and perhaps another couple of instances of https://github.com/pulumi/pulumi-terraform-bridge/issues/1328

**Comment by t0yv0** [comment]
Should be addressed by https://github.com/pulumi/pulumi-terraform-bridge/issues/1328 - please open a repro if still an issue. Appreciated!
