### ISSUE TITLE
Incorrect doccomment for BucketArgs.bucket

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi-terraform-bridge#29]
The doccomment text in Pulumi AWS is incorrect for BucketArgs.bucket, though the "sourced from" URL is correct.

Doccomment:

```typescript
    /**
     * The ARN of the S3 bucket where you want Amazon S3 to store replicas of the object identified by the rule.
     *
     * Sourced from https://www.terraform.io/docs/providers/aws/r/s3_bucket.html#bucket.
     */
```

In Terraform doc:
```
bucket - (Optional, Forces new resource) The name of the bucket. If omitted, Terraform will assign a random, unique name.
```

**Comment by stack72** [comment]
ok, this is a duplicate of #15 

Basically, there is another instance of the parameter `bucket` found. We are actually taking that and using it in this case

https://www.terraform.io/docs/providers/aws/r/s3_bucket.html#destination

Going to close this so we can track in #15
