### ISSUE TITLE
Create a way to indicate that a map's names should be transformed

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-terraform-bridge#30]
It'd be nice if there was a way to indicate that a map's names should be transformed.

## Motivation:

In https://github.com/pulumi/pulumi-github, there is a `configuration` arg field [that is typed as `TypeMap` in the schema](https://github.com/terraform-providers/terraform-provider-github/blob/f53121756325396b688a66568b5932619ba167f0/github/resource_github_repository_webhook.go#L48-L51):

```go
"configuration": {
    Type:     schema.TypeMap,
    Optional: true,
},
```

Instead of having this as `{[key: string]: any}` in the TypeScript projection, we've strongly typed it as:

```typescript
export interface WebhookConfiguration {
    readonly url: string;
    readonly content_type?: ContentType;
    readonly secret?: string;
    readonly insecure_ssl?: string;
}
```

We'd like `content_type` and `insecure_ssl` to be named `contentType` and `insecureSsl` to match the casing we use everywhere else, but GitHub expects the names to be `content_type` and `insecure_ssl` and we don't currently do a transformation from `contentType` and `insecureSsl` to `content_type` and `insecure_ssl`.

This work item is to add a way to indicate that a map's names should be transformed.

Once we have that, we can change `content_type` and `insecure_ssl` in https://github.com/pulumi/pulumi-github to the preferred names: `contentType` and `insecureSsl`.

For more details, see the discussion here: https://github.com/pulumi/pulumi-github/pull/4#discussion_r163716270

**Comment by lukehoban** [comment]
This hasn't come up again in the last 2 years, and we are redesigning several pieces of the code generation machinery here - so I'm going to close this out for now - and we can revisit when needed.
