### ISSUE TITLE
schema: Go language data is not set

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-terraform-bridge#320]
We should populate the `importBasePath` field at the very least.

See https://github.com/pulumi/pulumi-kubernetes/blob/eaf7026c7f8c41908d1978210eb3cf227d3d7681/provider/pkg/gen/schema.go#L262-L266 for an example.

**Comment by iwahbe** [comment]
It looks like this is fixed with @viveklak's changes. @lblackstone is that correct?

**Comment by lblackstone** [comment]
Yeah, looks like it
