### ISSUE TITLE
TF bridge code uses non-existent methods from TF SDK v2

### ISSUE THREAD

**Issue by mvuksano** [pulumi/pulumi-terraform-bridge#333]
When using boilerplate code (https://github.com/pulumi/pulumi-tf-provider-boilerplate) as a starting point for pulumi provider the code cannot be compiled. The issue is that some methods that are referenced (schema.UpgradeFlatmapState, schema.UpgradeJSONState, schema.RemoveAttributes, schema.NormalizeObjectFromLegacySDK) are not public but private in TF SDK. This change was introduced in commit `cd840ee Update to the latest sdk-v2 fork. (#313)` 

## Expected behavior
The code can be compiled with no errors

## Current behavior
Errors during compile phase:

```
# github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2
../../../../pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.18.1/pkg/tfshim/sdk-v2/upgrade_state.go:38:24: undefined: schema.UpgradeFlatmapState
../../../../pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.18.1/pkg/tfshim/sdk-v2/upgrade_state.go:44:14: undefined: schema.UpgradeJSONState
../../../../pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.18.1/pkg/tfshim/sdk-v2/upgrade_state.go:52:2: undefined: schema.RemoveAttributes
../../../../pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.18.1/pkg/tfshim/sdk-v2/upgrade_state.go:69:6: undefined: schema.NormalizeObjectFromLegacySDK
```

**Comment by stack72** [comment]
Hi @mvuksano 

So you will need to add a replace in the mod as follows:

```
github.com/hashicorp/terraform-plugin-sdk/v2 => github.com/pulumi/terraform-plugin-sdk/v2 v2.0.0-20201218231525-9cca98608a5e
```

that will fix you up - this is only required when a provider is using v2 of the plugin sdk

P.

**Comment by stack72** [comment]
Hi @mvuksano 

Did this help?

Paul

**Comment by yarinm** [comment]
@stack72 I just had the same issue and it worked for me, thanks!

**Comment by stack72** [comment]
Hi @mvuksano 

I've not heard back from you here but this has been confirmed as the correct fix by @yarinm 

I am going to close this out - we WILL be investing in new documentation in this area soon:tm:

Paul
