### ISSUE TITLE
Lambda Alias AdditionalVersionWeights not set correctly

### ISSUE THREAD

**Issue by pintonunes** [pulumi/pulumi-terraform-bridge#335]
According to your example (https://www.pulumi.com/docs/reference/pkg/aws/lambda/alias/) the AdditionalVersionWeights should be a float64 between 0 and 1 to set the percentage we want to send to a different lambda version.

But the input value for the weight is not set correctly. 

Example code:
![image](https://user-images.githubusercontent.com/37883272/111038247-e1147900-841f-11eb-93ee-6999491d7ba3.png)

State file:
![image](https://user-images.githubusercontent.com/37883272/111038318-30f34000-8420-11eb-9d6b-f7ad9d2de28e.png)

Logs:
![image](https://user-images.githubusercontent.com/37883272/111038369-6ac44680-8420-11eb-80d3-e75e4e349d1d.png)

Seems that when the value is converted to input, the decimal part is stripped.

When I set the value to 1 the value applied is 1. But when the value is between 0 and 1 the value applied is always 0. So this seems to be a type conversation issue.

**Comment by pintonunes** [comment]
@viveklak any news on this? We're kind of blocked using pulumi for lambda canary deployments.

**Comment by jkodroff** [comment]
Adding needs repro tag since this may have since been fixed (we're now on bridge v3).
