### ISSUE TITLE
Support for more recent versions of terraform plugin SDK?

### ISSUE THREAD

**Issue by cprice404-aws** [pulumi/pulumi-terraform-bridge#338]
I have used the bridge to create a pulumi provider for an existing open-source terraform provider, and it works very well.

However, since the point in time when I created the bridge, the upstream terraform provider has had several new releases, and they are using a newer version of the terraform plugin sdk (v2.4.x) than the version that this bridge seems to support (v2.0.x).

As best I can tell, this bridge relies on a pulumi fork of the terraform plugin SDK (https://github.com/pulumi/terraform-plugin-sdk), which hasn't been updated in about a year.  Are there plans to update this for compatibility with the upstream v2.4.x terraform plugin SDK?

**Comment by stack72** [comment]
Hi @cprice404-aws 

So the fork actually supports up until 2.4 - and there's a PR for 2.5

the branch you need to look for is `pulumi-master` as that's where all the recent commits went into (for some reason)

Please let me know if that answers / solves your issue

Paul

**Comment by cprice404-aws** [comment]
Aha, thanks!  Will look into that.  Feel free to close, I can re-open or file a new issue if necessary.

**Comment by stack72** [comment]
Thanks @cprice404-aws 

FWIW, I use the following replace in `pulumi-aws`

```
github.com/hashicorp/terraform-plugin-sdk/v2 => github.com/pulumi/terraform-plugin-sdk/v2 v2.0.0-20210402103405-f5979773e8ba
```

And that's v2.5.0 of the SDK
