### ISSUE TITLE
ID attributes need to respect providers that expect numerical IDs

### ISSUE THREAD

**Issue by infin8x** [pulumi/pulumi-terraform-bridge#352]
Based on:

- https://github.com/pulumi/pulumi-linode/issues/140
- https://github.com/pulumi/pulumi-digitalocean/issues/218
- https://github.com/pulumi/pulumi-digitalocean/issues/244
- https://github.com/pulumi/pulumi-digitalocean/issues/248
- https://github.com/pulumi/pulumi/issues/4173

**Comment by sudhanshuraheja** [comment]
I'm getting the same issue with JavaScript as well.

If I try this `dropletId: parseInt(dropletThree.id),`, on running pulumi up, it shows this change `~ dropletId: 1.92662022e+08 => -9.223372036854776e+18`

Is there a workaround available for Javascript?

**Comment by solarsoft0** [comment]
for anyone looking to implement in Go

```Go
	dropletId := droplet.ID().ApplyT(func(dropletId interface{}) int {
		return dropletId.(int)
	}).(pulumi.IntInput)
`

**Comment by solarsoft0** [comment]
```Go 

// convert dropletId from pulumi.ID to pulumi.IntInput
	dropletId := droplet.ID().ToStringOutput().ApplyT(func(id string) int {
		var idInt int
		idInt, err := strconv.Atoi(id)
		if err != nil {
			fmt.Println(err)
			return idInt
		}
		return idInt
	}).(pulumi.IntInput)

**Comment by ssboisen** [comment]
is this issue being worked on? 

while it can be solved when passing dropletId's on to other resources (like firewall) by using apply it causes problems when modifying a droplet causing a replace, one example would be to modify userData due to cloudinit changes but simply modifying any of the inputs for a droplet causes a panic.

**Comment by mkatrenik** [comment]
@iglu-sebastian nah, it doesn't

**Comment by t0yv0** [comment]
Per conversation with @iwahbe today, it is now possible to customize the bridge mapping to get acceptable behavior out of the providers, which is being rolled out to Pulumi-managed providers. @iwahbe can we link a few examples, a playbook how to do this for community providers, and close?
