### ISSUE TITLE
Overriding TF Provider Resource Examples

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-terraform-bridge#364]
We need a way of being able to inject Pulumi curated examples for a specific resource into the provider resources.go. This will give us the ability to create examples where no terraform examples exist or that examples do not play nicely with our codegen

Currently, our resources.go allow us to do the following:

```
			"azurerm_application_insights_web_test": {
				Tok: azureResource(azureAppInsights, "WebTest"),
				Docs: &tfbridge.DocInfo{
					Source: "application_insights_webtests.html.markdown",
				},
			},
```

This means we have some level of control over the documentation but we don't have a way of being able to pass in a set of examples. Our tfgen process currently requires these examples to be written in hcl so that they can be converted to all languages. 

-> Question for @infin8x here - do we want to continue this being the state of the world or do we need to allow these docs to be in another format that is predefined?

By allow this resource example override, we are then in a situation where we can accept pull requests to add new and more feature rich examples to our documentation

**Comment by infin8x** [comment]
@stack72 thanks for filing this!

> do we want to continue this being the state of the world or do we need to allow these docs to be in another format that is predefined?

This sounds similar to a question we had about authoring multi-language components a while back - it'd also be nice to author examples for those in one language and then be able to convert them to all the rest. From a requirements perspective, I think it is valuable to "have a single format where Pulumians and community members can author examples of how to use a Pulumi Package (whether that package is a bridged provider, a native provider, or a component) in a single, common format and make those examples available to users of all Pulumi languages." I will defer to engineering as to what the best "single, common format" is.
