### ISSUE TITLE
Add the ability for a mapping to be skipped

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-terraform-bridge#428]
In some less common use cases, we need the ability to indicate to tfgen that a skipped resource/data source mapping is intentional. One example is the AliCloud provider, where misspelled resources/data sources were fixed by adding an additional resource/data source with the correct spelling.

An intentionally skipped mapping should not fail the build, regardless of the value of `PULUMI_PROVIDER_MAP_ERROR`.

**Comment by stack72** [comment]
Closed via #439
