### ISSUE TITLE
Only throw errors if PULUMI_PROVIDER_MAP_ERROR is truth-y

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-terraform-bridge#436]
We currently set the behavior to fail tfgen upon a missing mapping if there is _any_ value for `PULUMI_PROVIDER_MAP_ERROR`:

```go
_, failBuildOnProviderMapError := os.LookupEnv("PULUMI_PROVIDER_MAP_ERROR")
```

In order to allow us to be more explicit about the desired behavior (IOW, set the env var explicitly to a false-y value), we should only throw an error if the value coalesces to `true`, depending on how feasible this is to do in Go.

**Comment by stack72** [comment]
Closed via #427 439
