### ISSUE TITLE
Generated schema.json includes hardcoded pulumi github org reference

### ISSUE THREAD

**Issue by itay** [pulumi/pulumi-terraform-bridge#462]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When generating the schema file for a bridged module, there is a hardcoded reference to the `pulumi` GitHub org (and general code structure), specifically here:

https://github.com/pulumi/pulumi-terraform-bridge/blob/a44e7a3730a6aa7582348b1b10deeacbf7222103/pkg/tfgen/docs.go#L366

You can reproduce this by using the boilerplate repo and generate a new package, and see that even if you update the GitHub org, the schema.json file will still be generated with incorrect links.

### Steps to reproduce

See above.

**Comment by stack72** [comment]
Ah great spot - thanks @itay - I'll get this taken care of!

**Comment by itay** [comment]
Thanks! I found this by searching for `pulumi/` after replacing everything when using the terraform boilerplate.

**Comment by ringods** [comment]
@stack72 there are still more hardcoded `pulumi` names:

* NodeJS SDK package name can be set in `JavaScriptInfo` (https://github.com/pulumiverse/pulumi-unifi/blob/main/provider/resources.go#L141) but this isn't universally used for code generation. The examples in `schema.json` still point to `@pulumi/<provider>`
* Python package name is `pulumi_<provider>`, while I would like to have it `pulumiverse_<provider>`
* .NET Package id prefix & code namespace is hardcoded to `Pulumi.`, while I want to use `Pulumiverse.`. I also want my project file to be named `Pulumiverse.Unifi.csproj`
* The Go examples have import statements listing `"github.com/pulumi/pulumi-unifi/sdk/go/unifi"` while I expect these to be `"github.com/pulumiverse/pulumi-unifi/sdk/go/unifi"`

Context: https://github.com/pulumiverse/pulumi-unifi/

**Comment by ringods** [comment]
I created #508 to allow a custom package name to be set for the generated Python SDK.

**Comment by stack72** [comment]
I created #509 for the dotnet root namespace changes
