### ISSUE TITLE
Terraform -> Pulumi nodejs SDK required fields

### ISSUE THREAD

**Issue by williamsbdev** [pulumi/pulumi-terraform-bridge#476]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Pulumi does not properly create an inline policy on a role when the `name` attribute is omitted. It will show during a `preview` that policy is to be added, NOT error during an `up`, and the Role does not have the inline policy created/applied.

Pulumi does not require the `name` attribute of an inline policy on a Role:

https://www.pulumi.com/registry/packages/aws/api-docs/iam/role/#roleinlinepolicy

Which is defined in the [file](https://raw.githubusercontent.com/pulumi/pulumi-aws/bfe20d4078ce1afa41e8c6df4fc6978623356e3d/sdk/nodejs/types/input.ts) as such:

```typescript
    export interface RoleInlinePolicy {
        /**
         * Name of the role policy.
         */
        name?: pulumi.Input<string>;
        /**
         * Policy document as a JSON formatted string.
         */
        policy?: pulumi.Input<string>;
    }
```

When I look at the Terraform configuration, I see that the `name` and `policy` are both required:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role#inline_policy

I would expect that bridge code would translate that and make those required (remove the `?`).

### Steps to reproduce

1. Create a `Role` with an inline policy but missing the `name` parameter
2. Run the `preview` command (showing that the policy would be added)
3. Run the `up` command (does not error)
4. Run the `preview` command (showing again that the policy would be added) 

Expected: It should error saying the field is required
Actual: It does not error and does not properly apply the resource

**Comment by stack72** [comment]
Hi @williamsbdev 

Apologies for the issue here - Pulumi is derived from the Terraform schema (the schema doesn't always reflect the docs). I can see from the Terraform schema that `name` and `policy` are marked as `Optional: true` and thus why Pulumi is showing as such

https://github.com/hashicorp/terraform-provider-aws/blob/v3.74.3/internal/service/iam/role.go#L47

I am not sure what we should do here based on this...

Paul

**Comment by williamsbdev** [comment]
@stack72 - Gotcha! Thanks for pointing that out. That is very odd that they have those as optional but then are marked required in the docs. :( I think you're right that there isn't anything we can do, unless we have a way to override certain things when doing the bridge.

If there is no override/customization that can be done when bridging, then I'll close this issue. Thanks for looking into this and teaching me how to find the schema in the Terraform code (I've referenced the Terraform docs more than a handful of times when working with Pulumi).
