### ISSUE TITLE
Added `__defaults` key after refresh

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi-terraform-bridge#490]
A user reports that after a `pulumi refresh`, AWS resources have diffs that indicate that a `__defaults` key was added:

```
        aws:ec2:SecurityGroup sg-default  [diff: +__defaults]
        kubernetes:rbac.authorization.k8s.io/v1:Role admin
        aws:ec2:SecurityGroupRule sg-default-internal-ingress  [diff: +__defaults]
        kubernetes:rbac.authorization.k8s.io/v1:RoleBinding admin-ias
        aws:ec2:SecurityGroupRule sg-default-internal-egress  [diff: +__defaults]
        aws:ec2:SecurityGroupRule sg-cluster-dns-egress-udp  [diff: +__defaults]
        aws:ec2:SecurityGroupRule sg-cluster-dns-egress-tcp  [diff: +__defaults]
        aws:ec2:SecurityGroupRule sg-cluster-apiserver-ingress  [diff: +__defaults]
        kubernetes:vpcresources.k8s.aws/v1beta1:SecurityGroupPolicy sg-policy
```

This should be innocuous, but it is certainly unexpected.

**Comment by pgavlin** [comment]
The user is using version 4.38.1 of the AWS provider.

**Comment by phillipedwards** [comment]
Below is a simple go aws repro.

Pulumi details:
CLI: 3.26.1
AWS: 5.1.0
OS: ubuntu

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/secretsmanager"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		secret, err := secretsmanager.NewSecret(ctx, "my-secret", &secretsmanager.SecretArgs{
			Name: pulumi.String("my-string"),
		})

		if err != nil {
			return err
		}

		_, err = secretsmanager.NewSecretVersion(ctx, "version", &secretsmanager.SecretVersionArgs{
			SecretId:     secret.ID(),
			SecretString: pulumi.String("super-secret"),
		})

		if err != nil {
			return err
		}

		return nil
	})
}

```

![image](https://user-images.githubusercontent.com/25461821/162280549-cb55b8bc-fc93-499b-88f6-f3884ba97a27.png)

**Comment by pgavlin** [comment]
I tried to repro this with the following TS equivalent and the same version of the AWS provider, but could not:

```typescript
import * as aws from "@pulumi/aws";

const s = new aws.secretsmanager.Secret('my-secret', {
    name: "my-string-2",
});

new aws.secretsmanager.SecretVersion('version', {
    secretId: s.id,
    secretString: "super-secret-2",
});
```

Next, I'll try the original Go program.

**Comment by phillipedwards** [comment]
@pgavlin I was able to repro using the TS example above, although refresh is required. Eg- `pulumi up --refresh`

**Comment by pgavlin** [comment]
> @pgavlin I was able to repro using the TS example above, although refresh is required. Eg- pulumi up --refresh

Okay, this is fascinating. This _does not_ repro with `pulumi up && pulumi refresh`, but _does_ repro with `pulumi up && pulumi up --refresh`. Thanks for the exact command here!

**Comment by pgavlin** [comment]
The tfbridge part of this is done, and will be available next time the bridge is rolled out to its consumers.
