### ISSUE TITLE
Ensure Superfluous id fields are omitted as part of codegen

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-terraform-bridge#504]
The Terraform Plugin SDK adds an "id" to the TF schema when `d.SetID` is used. When the TF schema already has an "id" parameter defined, it ignores the extra id. BUT when Pulumi calls tfgen, we get a second id added to our code that causes a compilation failure in python

```
      SyntaxError: duplicate argument 'id' in function definition
      error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

Currently, we will run a fork of the provider, change the schema and use the fork but this is not scalable

**Comment by jkodroff** [comment]
Some affected provider issues:
- https://github.com/pulumi/pulumi-tls/issues/120
- https://github.com/pulumi/pulumi-rke/pull/28
