### ISSUE TITLE
Broken links to terraform-provider-google docs

### ISSUE THREAD

**Issue by eddies** [pulumi/pulumi-terraform-bridge#52]
File: [docs/reference/pkg/nodejs/pulumi/gcp/projects/_index.md](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/projects/)

The following sections link to Terraform documentation:

* https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/projects/#Service
* https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/projects/#Services

but the links are broken. In both cases, the links are missing a "google_" prefix, i.e.:

* https://github.com/terraform-providers/terraform-provider-google/blob/master/website/docs/r/project_service.html.markdown should be: https://github.com/terraform-providers/terraform-provider-google/blob/master/website/docs/r/google_project_service.html.markdown
* https://github.com/terraform-providers/terraform-provider-google/blob/master/website/docs/r/project_services.html.markdown should be https://github.com/terraform-providers/terraform-provider-google/blob/master/website/docs/r/google_project_services.html.markdown

I hope you'll take the following in the spirit intended (constructive feedback from a user's perspective): it requires way too much investment from a user to make a simple documentation PR (in this case, fixing what amounts to a typo). For myself, I thought I'd just clone the repo, edit the markdown file (content/docs/reference/pkg/nodejs/pulumi/gcp/projects/_index.md) and make a PR. Frankly, this is probably already too much work for some but I think it's acceptable. Then I saw the notice at the head of the file that it was a generated file (to which, I asked myself, then why are generated files under source control?). Then I followed the link to https://github.com/pulumi/docs/tree/master/tools/tscdocgen which didn't help. Then I read CONTRIBUTING.md and README.md (yes, I should have started here, but I thought I was just making an edit to a simple markdown file), saw the required install and build steps (I've used Jekyll and Gatsby but never Hugo) and gave up in despair.

**Comment by justinvp** [comment]
@eddies, apologies for the frustrating experience here and thank you for raising the issue!

> any idea why the broken link checker didn't catch these?

@pgavlin there are so many broken links coming from the source TF provider docs that we explicitly [excluded](https://github.com/pulumi/docs/blob/3fe08afe2c60e6d2fe1b0df9f5b7e17bf1329ea1/Makefile#L52) that URL path from the broken link checker when we originally added it. It would be nice to remove the broad exclusion and get more granular to keep green areas green and have a better idea how much work is involved in fixing broken links for each of the providers.

**Comment by ekrengel** [comment]
Looking into this issue, it appears this has been resolved. I am going to close this, but feel free to comment if its still an issue and we can reopen this.
