### ISSUE TITLE
Spike: Move logging out of Generator in tfgen

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-terraform-bridge#526]
Make an attempt (8 hours timeboxed) at moving logging out of `Generator` and into a popular logging library, e.g. logrus:

* Consider which logging library we should use
* Consider whether we should add a facade on top of the logging library for an easy swap (if this is idiomatic in Go)
* Logging levels should be passed via the command line with standard nomenclature and semantics: FATAL, ERROR, WARN, INFO, DEBUG, TRACE, etc.
* Consider whether we can use structured logs internally (with friendly messages printed to our human end users) to aggregate summary counts of events. This would potentially replace both the optional detailed JSON output and the global counts for HCL conversions and other issues generating bridged providers.

**Comment by t0yv0** [comment]
@jkodroff I think I'm going to close this as won't fix as my team currently has no plans to do this.

The codebase currently does have a bit of a confused story, but we're getting by:

- glog - works everywhere (tfgen, runtime -> stderr -> engine -> cli), nobody particularly loves it but it's present 
- for PF we integrate the TF logging framework

I think if the platform core moves to something else than glog we'll try to follow suit, for now just continue with what we got.
