### ISSUE TITLE
Let the user know if a TF provider repo is not found during docs generation

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-terraform-bridge#528]
If e.g. `GitHubOrg` is missing, all entity docs will not be found, but there's no feedback to the user that the entire repo was not found. (See `tfgen.getRepoPath` for details.)

By default, we should return an error indicating that the repo path cannot be found and therefore no docs will be found for anything. The user should ensure that the following values are correct in `tfbridge.ProviderInfo`:

- `Name`
- `GitHubOrg`
- `TFProviderModuleVersion` (if the TF provider has a Go module version > 1)

And less commonly:

- `GitHubHost` if not github.com

Also, show the exact path we searched on disk.

This behavior can continue to be controlled `PULUMI_MISSING_DOCS_ERROR` because if this flag is true, we not only want a detailed message that a particular entity's docs can be found, but also that the entire repo cannot be found.

**Comment by iwahbe** [comment]
We do this now. The warning for a missing provider repo prints out what the user needs to set so the repo can be found.
