### ISSUE TITLE
Nested properties that share the same name get overwritten

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi-terraform-bridge#529]
Example: https://www.pulumi.com/registry/packages/aws/api-docs/cloudfront/distribution/

Both `DistributionDefaultCacheBehaviorLambdaFunctionAssociation` and `DistributionDefaultCacheBehaviorFunctionAssociation` have `EventType` as a property.

`DistributionDefaultCacheBehaviorFunctionAssociation.EventType` should read:

> The specific event to trigger this function. Valid values: viewer-request or viewer-response

`DistributionDefaultCacheBehaviorLambdaFunctionAssociation.EventType` should read:

> The specific event to trigger this function. Valid values: viewer-request, origin-request, viewer-response, origin-response

Known issues caused by this bug (will require an update to the bridge and re-release to fix):

* https://github.com/pulumi/pulumi-aws/issues/1993
* https://github.com/pulumi/pulumi-aws/issues/1879
* https://github.com/pulumi/pulumi-aws/issues/1994
* https://github.com/pulumi/pulumi-gcp/issues/784
* https://github.com/pulumi/pulumi-aws/issues/1992
* https://github.com/pulumi/pulumi-gcp/issues/852
* https://github.com/pulumi/pulumi-aws/issues/2050
* https://github.com/pulumi/pulumi-aws/issues/1315
* https://github.com/pulumi/pulumi-aws/issues/2119
* https://github.com/pulumi/pulumi-aws/issues/2163
* https://github.com/pulumi/pulumi-aws/issues/2164
* https://github.com/pulumi/pulumi-aws/issues/1616
* https://github.com/pulumi/pulumi-aws/issues/1603
* https://github.com/pulumi/pulumi-aws/issues/2253

**Comment by BrooksPatton** [comment]
The Distribution documentation caused me a lot of confusion today. Do we think it would be possible to have a way to easily add to the documentation? This would allow us to have better descriptions for properties and methods than just the ones from Terraform.
