### ISSUE TITLE
Notes are dropped from nested attributes in docs

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-terraform-bridge#530]
In <https://github.com/pulumi/pulumi-aws/issues/1969>, the notes toward the bottom of <https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#instance_refresh> ("A refresh is started any of the following...") are dropped which is causing confusion for our users.

(We still need to find the root cause and determine the effort to fix.)

**Comment by guineveresaenger** [comment]
Hi @jkodroff - have you seen any recent instances of notes missing entirely?

You're right that ideally, these notes should be associated with the top-level GroupInstanceRefresh. That is a slightly different bug unfortunately, one that is related to the brittle way we do docs discovery. I'll file a separate issue for this, but my feeling is that that would best be addressed by rethinking how we transform our docs in the first place.

**Comment by jkodroff** [comment]
They're definitely not dropped, so I think that it's reasonable to close this issue.

FWIW, IME the notes displaying under `triggers` instead of afterwards is a minor usability issue.

I can't close b/c I don't have perms to add a resolution tag, but ok to close.

**Comment by guineveresaenger** [comment]
I'm closing this issue as fixed. Notes are no longer dropped, but they are misaligned.

I filed #2086 to track the misalignment of Note sections.
