### ISSUE TITLE
OCI Devops module for python is not valid as per the documentation

### ISSUE THREAD

**Issue by RahulMR42** [pulumi/pulumi-terraform-bridge#531]
### What happened?

OCI Documentation - 
```
import pulumi
import pulumi_oci as oci

test_project = oci.dev_ops.Project("testProject",
```

And its coming out with an error as 

```
 AttributeError: module 'pulumi_oci' has no attribute 'dev_ops'

```

### Steps to reproduce

https://www.pulumi.com/registry/packages/oci/api-docs/devops/project/ 

### Expected Behavior

Create a devops project

### Actual Behavior

Failing to create the DevOps project.

the actual module name is devops not dev_ops 

```
>>> oci.devops
<module 'pulumi_oci.devops' from '/Users/rahulmr_in/Oracle Content - Accounts/Oracle Content/code/pulumi_oci_devops/venv/lib/python3.8/site-packages/pulumi_oci/devops/__init__.py'>
>>> 

```

### Versions used

(venv) rahulmr_in@rahulmr_in-mac pulumi_oci_devops % pulumi about
CLI          
Version      3.33.1
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME    VERSION
oci     0.1.1
python  unknown

Host     
OS       darwin
Version  11.6.3
Arch     x86_64

This project is written in python (/Users/rahulmr_in/Oracle Content - Accounts/Oracle Content/code/pulumi_oci_devops/venv/bin/python3 v3.8.9)

Current Stack: oci-devops-oke

TYPE                                                   URN
pulumi:pulumi:Stack                                    urn:pulumi:oci-devops-oke::pulumi-python-oci-devops-oke::pulumi:pulumi:Stack::pulumi-python-oci-devops-oke-oci-devops-oke
pulumi:providers:oci                                   urn:pulumi:oci-devops-oke::pulumi-python-oci-devops-oke::pulumi:providers:oci::default_0_1_1
oci:Artifacts/containerRepository:ContainerRepository  urn:pulumi:oci-devops-oke::pulumi-python-oci-devops-oke::oci:Artifacts/containerRepository:ContainerRepository::testContainerRepository
oci:DevOps/project:Project                             urn:pulumi:oci-devops-oke::pulumi-python-oci-devops-oke::oci:DevOps/project:Project::test_project

Found no pending operations associated with oci-devops-oke

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/RahulMR42
User           RahulMR42
Organizations  RahulMR42

NAME        VERSION
pip         22.1.1
pulumi-oci  0.1.1
setuptools  62.3.2
wheel       0.37.1

Pulumi locates its logs in /var/folders/hn/2m651xss3vngsxk53znm1r680000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
We need to ensure that we use the correct casing in the exampels - `Core is not correct `core` is etc.

**Comment by guineveresaenger** [comment]
It turns out this is a programgen bug. Closing in favor of https://github.com/pulumi/pulumi/issues/16514.
