### ISSUE TITLE
Arguments duplicate second line of source content

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-terraform-bridge#553]
For some arguments whose descriptions are multi-line in the source docs, we are repeating the second line (and possibly subsequent lines - haven't found a >2 line example yet) of the content.

Example:

In [the Pulumi docs](https://www.pulumi.com/registry/packages/aws/api-docs/appmesh/route/#httpretryevents_nodejs):

> List of HTTP retry events. Valid values: client-error (HTTP status code 409), gateway-error (HTTP status codes 502, 503, and 504), server-error (HTTP status codes 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, and 511), stream-error (retry on refused stream). Valid values: client-error (HTTP status code 409), gateway-error (HTTP status codes 502, 503, and 504), server-error (HTTP status codes 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, and 511), stream-error (retry on refused stream).

But in [the TF docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appmesh_route#http_retry_events):

> List of HTTP retry events. Valid values: client-error (HTTP status code 409), gateway-error (HTTP status codes 502, 503, and 504), server-error (HTTP status codes 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, and 511), stream-error (retry on refused stream).

**Comment by iwahbe** [comment]
This has been fixed in our docs.

I'm not 100% sure what PR fixed it.
