### ISSUE TITLE
Improve detection of naming collisions for singular/plural resource names

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-terraform-bridge#573]
A [customer reported an issue with a nested resource in the pulumi-opsgenie provider](https://github.com/pulumi/pulumi-opsgenie/issues/56).

I was at first confused why this was still an issue, as per [a previous issue](https://github.com/pulumi/pulumi-opsgenie/issues/52) that I believed I had fixed via [explicit naming](https://github.com/pulumi/pulumi-opsgenie/pull/53).

We [identified the problem as a naming collision](https://github.com/pulumi/pulumi-opsgenie/issues/57) where the upstream-singular nested resource was dropped entirely by `tfgen` in favor of the upstream-plural resource being converted into an array of pulumi-singular. This resulted in incorrect docs and missing features.

The true problem here is:
- we were unaware of this naming collision, 
- the schema tool did not detect any problem because the schema had always been missing the upstream-singular resource
- and thus this quiet failure was allowed to continue until users made us aware of missing functionality.

The Opsgenie provider is likely not the only one at risk for such accidental collisions.

The Terraform bridge should detect naming collisions during `make tfgen` and fail with an error. We will [likely have to overwrite the resource names](https://github.com/pulumi/pulumi-opsgenie/pull/58), as pluralization in the English language is not always consistent, and solutions may vary. (See also [MaxItemsOne](https://github.com/pulumi/platform-providers-team/blob/main/playbooks/maxitemsone.md) for a somewhat related concern).

**Comment by iwahbe** [comment]
We do this now, as introduced in https://github.com/pulumi/pulumi-terraform-bridge/pull/775.
