### ISSUE TITLE
Defaults should not be set if ConflictsWith

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-terraform-bridge#577]
Given an object in a collection with a `DefaultValue` and `ConflictsWith`, the bridge incorrectly assigns the `DefaultValue`, which erroneously triggers the `ConflictsWith`.

`tfbridge.applyDefaults` in the bridge is where the code needs to change.

This was pointed out by @ringods on #559.

### Downstream issues
- https://github.com/pulumi/pulumi-aws/issues/1184
- https://github.com/pulumi/pulumi-auth0/issues/158

### Downstream fork edits
- https://github.com/pulumi/pulumi-azuredevops/issues/52 (fork: https://github.com/pulumi/pulumi-azuredevops/pull/109)
- https://github.com/pulumi/pulumi-azure/pull/1328#pullrequestreview-1573187737

**Comment by t0yv0** [comment]
This was fixed in https://github.com/pulumi/pulumi-terraform-bridge/pull/1583
