### ISSUE TITLE
tfplugindocs generates schema that cannot be parsed

### ISSUE THREAD

**Issue by Yantrio** [pulumi/pulumi-terraform-bridge#580]
### What happened?

The latest version of terraform-plugin-docs introduces a PR that changes attribute names in schema from a **strong** markdown element to a `code` element.

https://github.com/hashicorp/terraform-plugin-docs/pull/59

This means that document generation will fail when pointed at a repo that uses the latest version of tfplugindocs.

### Steps to reproduce

Try and generate documentation from a repo when it uses the latest version of terraform-plugin-docs. 

### Expected Behavior

Should parse the documentation

### Actual Behavior

Fails to parse with the following error message:

```warning: error: Failure in parsing resource name: *RESOURCE*, subsection: ## Schema```

### Versions used

Latest version of this repo at the time of writing: https://github.com/pulumi/pulumi-terraform-bridge/tree/184df4b22591f1300bc953a979ef9a713dd853e0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Yantrio** [comment]
I'll work on a fix for this now and should have a PR up soon

**Comment by stack72** [comment]
Closed via 7719459
