### ISSUE TITLE
Cannot find vendor directory?

### ISSUE THREAD

**Issue by bellcprimer** [pulumi/pulumi-terraform-bridge#583]
### What happened?

Should be an easy answer, the guide says to clone and go into the vendor directory, can I get a clear explanation what or where this is

### Steps to reproduce

none

### Expected Behavior

none

### Actual Behavior

none

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
My apologies here @bellcprimer - the wasn't updated since we moved away from vendoring dependencies directly. I will update that line now :/
