### ISSUE TITLE
Support for terraform-plugin-framework

### ISSUE THREAD

**Issue by masonyc** [pulumi/pulumi-terraform-bridge#590]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Hi, by reading through the readme, it seems like this only supports TF providers written in Terraform Plugin SDK. Just wondering are there any support for providers written in [terraform-plugin-framework](https://github.com/hashicorp/terraform-plugin-framework)? I think this is the one TF is suggesting moving forward with.

**Comment by lblackstone** [comment]
@stack72 Do you know?

**Comment by t0yv0** [comment]
Folks there is some progress toward this and it is now tracked in https://github.com/pulumi/pulumi-terraform-bridge/issues/744 ; as of today we have simple providers working but there's some work happening in Q1 to finish supporting all the necessary features.

**Comment by t0yv0** [comment]
We are closing this issue today. 

There is a new Go module [pf/v0.13.0](https://github.com/pulumi/pulumi-terraform-bridge/releases/tag/pf%2Fv0.13.0) implementing support for Plugin Framework, complete with a [README](https://github.com/pulumi/pulumi-terraform-bridge/tree/master/pf#pulumi-bridge-for-terraform-plugin-framework).

Pulumi Providers using Plugin Framework upstream include:

- [x] [Random](https://github.com/pulumi/pulumi-random)
- [x] [CloudFlare](https://github.com/pulumi/pulumi-cloudflare)
- [x] [Gitlab](https://github.com/pulumi/pulumi-gitlab)
- [x] [Linode](https://github.com/pulumi/pulumi-linode)
- [x] [Artifactory](https://github.com/pulumi/pulumi-artifactory)
- [x] [Datadog](https://github.com/pulumi/pulumi-datadog)
- [x] [GCP](https://github.com/pulumi/pulumi-gcp)
- [ ] [AWS](https://github.com/pulumi/pulumi-aws) will utilize Plugin Framework bridge in the soon-coming v6
- [ ] [TLS](https://github.com/pulumi/pulumi-tls) will utilize Plugin Framework bridge as soon as upstream releases a new version

There is also a number of community providers:

- [pulumi-fly](https://github.com/dirien/pulumi-fly)
- [pulumi-mssql](https://github.com/pulumiverse/pulumi-mssql)

Support continues using the tracker in this repository, there is an [area/plugin-framework](https://github.com/pulumi/pulumi-terraform-bridge/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fplugin-framework) tag to track enhancements and bug fixes.
