### ISSUE TITLE
Inclusion of a `/` in a datasources module name produces incorrect tokens in `schema.json` for children properties

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-terraform-bridge#611]
### What happened?

In `resources.go` when a datasource's module name includes a 2 parts separated by a `/` the resulting token, in `schema.json`, is correctly produced for the corresponding `get` function, however, the tokens for the function's children properties are incorrectly produced, if the properties are non-primitives.

For example, the datasource `aws_iam_policy_document` when given a module name of `x/iam` gets a corresponding token in `schema.json` of `aws:x/iam/getPolicyDocument:getPolicyDocument`. This is correct, however, if you examine the `statements` property, which is a non-primitive,  you'll notice the token is missing the `iam` portion of the module. Eg- `aws:x/getPolicyDocumentStatement:getPolicyDocumentStatement`.

### Steps to reproduce

1. `git clone git@github.com:phillipedwards/pulumi-aws.git`
2. `cd pulumi-aws`
3. `make tfgen`
4. Open `schema.json` and examine the get function `aws:x/iam/getPolicyDocument:getPolicyDocument` note: we've introduced the `x/` to detail the function is experimental.
5. `make build_python`
6. Open `sdk/python/pulumi_aws/x/iam/get_policy_document.py` and go to line 105. 
7. The `def statements...` function references a non-existent type of `_x.outputs.GetPolicyDocumentStatement`

### Expected Behavior

1. In `schema.json` the tokens for the non-primitive children of `getPolicyDocument` should have tokens that begin with `aws:x/iam/...`. Eg- `aws:x/iam/getPolicyDocumentStatement:getPolicyDocumentStatement`
2. The generated python sdk function `pulumi_aws.x.iam.get_policy_document.py` should be referencing `GetPolicyDocumentStatementResult` as the return type for `def statements...`

### Actual Behavior

1. The non-primitive children tokens incorrectly start with `aws:x/....`. See, `#/types/aws:x/getPolicyDocumentStatement:getPolicyDocumentStatement`.
2. The statements function signature is `def statements(self) -> Optional[Sequence['_x.outputs.GetPolicyDocumentStatement']]:`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
There is an underlying codegen bug here. https://github.com/pulumi/pulumi/pull/10935 makes codegen generate the right type reference (GetPolicyDocumentStatementResult).
