### ISSUE TITLE
Remove duplicate schema-tools code

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-terraform-bridge#618]
Now that https://github.com/pulumi/schema-tools/pull/5 is merged, and schema-tools has a pkg that can be consumed by other repos, we should remove the duplicate code from https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfgen/metrics.go

(It was copy/pasted because prior to https://github.com/pulumi/schema-tools/pull/5, schema-tools was cmd only.)

**Comment by jkodroff** [comment]
I'm happy to take this on as it'll take me all of 10 minutes or so. Might need a little help cutting a release for schema-tools for lack of permissions.

**Comment by lblackstone** [comment]
Thanks Josh -- I'm happy to help shepherd this through if you can make this change.
