### ISSUE TITLE
Investigate support for Terraform provisioners

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform-bridge#63]
We are tracking adding a first-class mechanism for running custom code in the resource lifecycle in https://github.com/pulumi/pulumi/issues/1691.

We should also consider direct support for Terraform provisioners.  This would allow bridged Pulumi providers to use the existing provisioners associated with the corresponding resources, using the same provisioners available to the underlying Terraform resources.

This is complementary to first-class support for custom code in the resource lifecycle, but has a few benefits for some use cases:
1. It can map 1:1 with existing Terraform code
2. It provides immediate access to some higher-level provisioning capabilities like `remote-exec`, `chef`, `puppet`.  While these could be re-built on top of a native Pulumi capability, it would be nice to have access to these as is.

**Comment by pgavlin** [comment]
Provisioners are not a feature of the TF plugin SDK--they are a feature of TF itself--so while we could probablystill do this in TF-based resource providers without too much trouble, it isn't as simple as we may have hoped.

**Comment by iwahbe** [comment]
Closing as wont-fix, since pulumi-command already fulfills this niche for Pulumi.
