### ISSUE TITLE
Intellisense docs missing for resource types

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-terraform-bridge#7]
We had this problem in Kubernetes too. The culprit seems to be these [`__init__.py` files](https://github.com/pulumi/pulumi-aws/blob/d42f7d16700e2cd9b68264cd4135b7de6f37af25/sdk/python/pulumi_aws/cloudfront/__init__.py). We're doing something like this:

```python
# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Kubernetes codegen tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

# Export this package's modules as members:
from .DaemonSet import *
from .Deployment import *
```

but we should be doing something like this:

```python
# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Kubernetes codegen tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

# Export this package's modules as members:
from .DaemonSet import (DaemonSet)
from .Deployment import (Deployment)
```

cc @lukehoban @stack72 @jen20 also see our fix here https://github.com/pulumi/pulumi-kubernetes/pull/635

**Comment by stack72** [comment]
Hi @hausdorff 

So I have been looking at this issue to try and solve it. I have managed go get the following diff:

```
diff --git a/sdk/python/pulumi_aws/acm/__init__.py b/sdk/python/pulumi_aws/acm/__init__.py
index 13427994..ad307745 100644
--- a/sdk/python/pulumi_aws/acm/__init__.py
+++ b/sdk/python/pulumi_aws/acm/__init__.py
@@ -3,6 +3,6 @@
 # *** Do not edit by hand unless you're certain you know what you are doing! ***

 # Export this package's modules as members:
-from .certificate import *
-from .certificate_validation import *
-from .get_certificate import *
+from .certificate import Certificate
+from .certificate_validation import CertificateValidation
+from .get_certificate import get_certificate
```

As you can see, we are actually importing real classes now. 

Certificate is a class in certificate.py that looks as follows:

```
class Certificate(pulumi.CustomResource):
```

CertificateValidation is a class in certificate_validation.py:

```
class CertificateValidation(pulumi.CustomResource):
```

Those 2 are easy and should be correct. But the last one, get_certificate.py. This file has the following:

```
class GetCertificateResult:

class AwaitableGetCertificateResult(GetCertificateResult):

def get_certificate(domain=None,key_types=None,most_recent=None,statuses=None,types=None,opts=None):
```

as you can see, the name of the def is correct and is included here. The big question I have is, should the other 2 classes be imported to the __init__.py file as well? Or do we not need to care about those?

**Comment by hausdorff** [comment]
@stack72 I'm definitely not an expert on these APIs, but: my _guess_ is that these do need to be imported, as autocomplete is still useful for property access.

BTW, I can't tell from your message whether  those classes are empty in the source, or whether you omitted them, though—but even if they're always empty I believe you still need to export them to get the class name, which itself is still useful.
