### ISSUE TITLE
[Plugin Framework] Support Tuple type

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#730]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Terraform Plugin Framework allows providers to specify types of properties as a Tuple (known length, known element types). Bridged Pulumi providers should support working with such properties.

**Comment by iwahbe** [comment]
Given the Plugin Framework's lack of support for tuples (https://github.com/hashicorp/terraform-plugin-framework/issues/54) and the inability of the PF to even support an end to end test, tuple support is probably not worth adding at this time. 

If any user encounters PF Tuples in the wild, we can reconsider.

**Comment by t0yv0** [comment]
Good call, bottom of backlog for now. I'll remove it from the epic.

**Comment by t0yv0** [comment]
IT still remains the case that it's a rarely used feature.. But it turns out Ian's implementation was close enough and touches on Custom Type which is a customer request, so we now have a PR passing review and will just check it in, only to revisit if when there's actual usage.
