### ISSUE TITLE
Error when trying to set VpcId for ClusterVpcConfigArgs.

### ISSUE THREAD

**Issue by guitarrapc** [pulumi/pulumi-terraform-bridge#74]
## Summary

When trying to set ClusterVpcConfigArgs.VpcId following error happens on `pulumi up`.

```
"vpc_config.0.vpc_id": this field cannot be set
```

I think it's proper error because terraform vpc_config not accept vpc_id.

> https://www.terraform.io/docs/providers/aws/r/eks_cluster.html#endpoint_private_access

However current `ClusterVpcConfigArgs` expose `VpcId` as public, so intellisence indicate me VpcId is settable.

> https://github.com/pulumi/pulumi-aws/blob/a113b17652528591ccee845ea27058de57265066/sdk/dotnet/Eks/Cluster.cs#L381

![image](https://user-images.githubusercontent.com/3856350/69126251-1e4a4e80-0aeb-11ea-9e33-eb9e726f46ab.png)

## Expected behavior

stop expose `VpcId` on `ClusterVpcConfigArgs` class.

## Actual behavior

`VpcId` is exposed as public and settable on `ClusterVpcConfigArgs` class.

## Reproduce step

```csharp
new Pulumi.Aws.Eks.Cluster(cluster_name, new Pulumi.Aws.Eks.ClusterArgs
{
    Name = cluster_name,
    RoleArn = role.Arn,
    Version = "1.14",
    VpcConfig = new ClusterVpcConfigArgs
    {
        VpcId = vpc.Id,
        SecurityGroupIds = sg.Select(x => x.Id).ToArray(),
        SubnetIds = sn.Select(x => x.Id).ToArray(),
    },
    Tags = parameter.Tags,
});
```

## Workaround

don't set VpcId.

```csharp
new Pulumi.Aws.Eks.Cluster(cluster_name, new Pulumi.Aws.Eks.ClusterArgs
{
    Name = cluster_name,
    RoleArn = role.Arn,
    Version = "1.14",
    VpcConfig = new ClusterVpcConfigArgs
    {
        SecurityGroupIds = sg.Select(x => x.Id).ToArray(),
        SubnetIds = sn.Select(x => x.Id).ToArray(),
    },
    Tags = parameter.Tags,
});
```

## Output

```shell
$ pulumi up
Previewing update (dev):
     Type                 Name        Plan     Info
     pulumi:pulumi:Stack  pulumi-dev           'dotnet build -nologo .' completed successfully

     Type                         Name                                   Plan       Info
     pulumi:pulumi:Stack          pulumi-dev
     ├─ pkg:component:ekscluster  sandbox
 +   │  └─ pkg:component:eks      sandbox-eks                            create
     └─ aws:eks:Cluster           my-cluster                                        1 error

Diagnostics:
  aws:eks:Cluster (my-cluster):
    error: aws:eks/cluster:Cluster resource 'my-cluster' has a problem: "vpc_config.0.vpc_id": this field cannot be set
```

## Version

```shell
$ pulumi version
v1.5.2
$ pulumi plugin ls
NAME  KIND      VERSION  SIZE    INSTALLED   LAST USED
aws   resource  1.8.0    220 MB  6 days ago  6 days ago
```

**Comment by benswinburne** [comment]
Also seeing this on `aws.lambda.CallbackFunction`

> error: aws:lambda/function:Function resource 'conversation-data-to-postgres' has a problem: "vpc_config.0.vpc_id": this field cannot be set.

```
const sendToPostgresLambda = new aws.lambda.CallbackFunction(
  'conversation-data-to-postgres',
  {
    vpcConfig: {
      // vpcId: vpc.id,
      securityGroupIds: rds.vpcSecurityGroupIds,
      subnetIds: vpc.publicSubnetIds,
    },
...
```

**Comment by jeanlescure** [comment]
Having the same problem with `aws.lambda.CallbackFunction` that @benswinburne is having

**Comment by nimrodolev** [comment]
Same here, hitting this error while trying to set up `aws.lambda.CallbackFunction`

**Comment by kaman86** [comment]
Is there an ETA on this? 

"Error when trying to set VpcId for ClusterVpcConfigArgs"

**Comment by logston** [comment]
Same issue.

**Comment by minaibrahimsaid** [comment]
same issue

**Comment by minaibrahimsaid** [comment]
@benswinburne 
Thanks 
I just comment ```vpcId``` and it works fine

**Comment by leezen** [comment]
Apologies for the confusion on this.

For those coming to this issue: as others have noted, you should omit `vpcId` from the configuration as it's not expected. In the upstream provider, it's a computed field that is only present as an output (and not something one would set). However, there is a bug in how the code is generated such that this field is included as part of the overall `VpcConfig` field type as an input.

**Comment by shinebayar-g** [comment]
[clusterSecurityGroupId](https://www.pulumi.com/docs/reference/pkg/aws/eks/cluster/#clustersecuritygroupid_nodejs) is also not expected as Input.

**Comment by dokuboyejo** [comment]
This is still happening in `Pulumi v3.11.0`

**Comment by gf3** [comment]
> Apologies for the confusion on this.
> 
> For those coming to this issue: as others have noted, you should omit `vpcId` from the configuration as it's not expected. In the upstream provider, it's a computed field that is only present as an output (and not something one would set). However, there is a bug in how the code is generated such that this field is included as part of the overall `VpcConfig` field type as an input.

how can we ensure that the EKS cluster is created in the correct VPC (i.e. **not** the default VPC)?

**Comment by guitarrapc** [comment]
Your subnet and subnet must be belong to desired VPC.

**Comment by iwahbe** [comment]
I believe that this has been resolved. If the you still encounter this issue, please open a new issue [here](https://github.com/pulumi/pulumi/issues/new?assignees=&labels=kind%2Fbug%2Cneeds-triage&projects=&template=bug.yaml).
