### ISSUE TITLE
Deprecation message uses terraform property name

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi-terraform-bridge#77]
For example: ```warning: urn:pulumi:support::vault::vault:kubernetes/authBackendRole:AuthBackendRole::default verification warning: "policies": [DEPRECATED] use `token_policies` instead```

**Comment by jkodroff** [comment]
Based on #442 (where another user is noting that the warning does not include the attribute name), I believe the error message no longer prints the attribute name. Propose closing.

**Comment by guineveresaenger** [comment]
Closing as dupe of #6
