### ISSUE TITLE
Bridged providers panic when passed an incorrectly typed set element

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#787]
### What happened?

Noticing that when not-well-typed Pulumi programs send `Set<String>` data into `Set<Int>` properties, the bridge panics unhelpfully instead of producing a nice error message explaining how to fix this. 

We cannot expect Pulumi programs to always pass the type-checker because Pulumi supports JavaScript and Python programs where users may not want to use types intentionally.

### Expected Behavior

Nice error message produced.

### Steps to reproduce

https://github.com/pulumi/pulumi-terraform-bridge/issues/765 has a great example that reproduces the issue. 

The program as written intuitively should work, because the underlying Linode provider has integer IDs for resources.

However because of https://github.com/pulumi/pulumi-terraform-bridge/issues/352 , the integer IDs are projected as Strings into Pulumi. When connecting resources, the user then needs to convert strings to IDs, but without a type system to guide them this is error-prone. 

### Output of `pulumi about`

N/A

### Additional context

It's more important to fix https://github.com/pulumi/pulumi-terraform-bridge/issues/352  but anything we can do to improve the error presentation in this case specifically is also helpful.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
CC @aq17

**Comment by t0yv0** [comment]
Likely fixed by https://github.com/pulumi/pulumi-terraform-bridge/issues/1328 but need to confirm.

**Comment by VenelinMartinov** [comment]
Tested, we now implicitly convert the type and the repro above passes without issues.

I believe this was fixed in https://github.com/pulumi/pulumi-terraform-bridge/pull/1896 or https://github.com/pulumi/pulumi-terraform-bridge/pull/1945
