### ISSUE TITLE
Complications with mapping plural and singular field names when both are present in the terraform provider

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi-terraform-bridge#790]
### What happened?

When updating pulumi/pulumi-azure using the latest v3.39.1 version of pulumi/pulumi-terraform-bridge, we're encountering failing test runs for previously passing test cases and with no upstream changes to the module/schema.

The failing test run can be found here:
https://github.com/pulumi/pulumi-azure/actions/runs/4078132838/jobs/7048043503

I suspect it's due to [these lines in this commit.](https://github.com/pulumi/pulumi-terraform-bridge/commit/73af678061a1d59e46ffab0f8457f28f0b3e95dc#diff-66c3717b48d905ff185f71bced19b4c7558c24390b75e01a0d81c764e9c9f989R47-R49)

### Expected Behavior

Tests should have passed and `pulumi up/preview` should not error.

### Steps to reproduce

Run the example test case in https://github.com/pulumi/pulumi-azure/pull/1203 which is built using v3.39.1 version of pulumi/pulumi-terraform-bridge.

### Output of `pulumi about`

CLI          
Version      3.51.0
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME    VERSION
azure   5.32.0
nodejs  unknown
random  4.10.0

Host     
OS       darwin
Version  13.2
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v19.6.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ramon
User           ramon
Organizations  ramon, pulumi

Dependencies:
NAME            VERSION
@pulumi/azure   5.32.0
@pulumi/random  4.10.0
@types/node     10.17.60

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Problem is that we were keeping a field singular, because there was another field that had the plural name. The plural field was manually remapped, so it was actually safe to pluralize. Because we stoped pluralizing, this was a breaking change.

**Comment by t0yv0** [comment]
Apologies for the disruption @rquitales  - this escaped our testing. Please use v3.39.1 that should fix the problem.
