### ISSUE TITLE
Strings passed to asset/archive properties should be interpreted as paths

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi-terraform-bridge#8]
It would be nice if instead of this:

```
// Create a bucket object with the contents of a folder.
const obj = new aws.s3.BucketObject("archive", {
    bucket: bucket.id,
    source: new pulumi.asset.FileArchive("./content"),
});
```

I could write this:
```
// Create a bucket object with the contents of a folder.
const obj = new aws.s3.BucketObject("archive", {
    bucket: bucket.id,
    source: "./content",
});
```

This should be doable by having `Check` interpret a string that is passed to a property with an asset transformation as a path. There is a little bit of subtlety involved in making sure that this transformation is _only_ done during `Check`, but otherwise this seems straightforward.

**Comment by iwahbe** [comment]
This doesn't fit into our schema based world. Individual target languages might do this, but the bridge would not.
