### ISSUE TITLE
Input type documentation is missing

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-terraform-bridge#80]
There are cases when input types are missing documentation. For example, https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/types/output/#DeploymentConfigTrafficRoutingConfig. Based on the source provider, this should be:

```
The traffic_routing_config block supports the following:

* `type` - (Optional) Type of traffic routing config. One of TimeBasedCanary, TimeBasedLinear, AllAtOnce.
* `time_based_canary` - (Optional) The time based canary configuration information. If type is TimeBasedLinear, use time_based_linear instead.
* `time_based_linear` - (Optional) The time based linear configuration information. If type is TimeBasedCanary, use time_based_canary instead.
```

with proper name mangling.

**Comment by ekrengel** [comment]
@joeduffy I believe this is fixed now. Feel free to re-open if I am missing something :)

![image](https://user-images.githubusercontent.com/8304499/78915148-59b8cb80-7a40-11ea-8241-9527317915d2.png)
