### ISSUE TITLE
[Plugin Framework] Issues with output strings

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#812]
### What happened?

```
error: Preview failed: objectEncoder failed on property "url": Expected a string, got: {&{{[http://vm-4liajfa3.staging.azure.tetrate.com/}}}](http://vm-4liajfa3.staging.azure.tetrate.com/%7D%7D%7D)
```

```
pulumi.output(args.endpoint).apply(
                    (endpoint) =>
                        new checkmate.HttpHealth(
                            `${this.pulumiName}-check-endpoint`,
                            {
                                timeout: 1000 * 60 * 10, // 10 min, to allow for DNS to propagate (2 x TTL)
                                interval: 1000 * 2, // 2s
                                consecutiveSuccesses: 100,
                                url: endpoint,
                            },
                            { dependsOn: this.resources },
                        ).id,
                )
```

```
endpoint: pulumi.interpolate`vm-${vmPrefix}.${standaloneCluster.dnsDomain}
```

Courtesy of Rob Martens.

### Expected Behavior

Program succeeds

### Steps to reproduce

N/A

### Output of `pulumi about`

tf framework version v1.1.1, and pf bridge version [github.com/pulumi/pulumi-terraform-bridge/pkg/tfpfbridge](http://github.com/pulumi/pulumi-terraform-bridge/pkg/tfpfbridge) v0.0.0-20230120143314-6ffb2faf051e

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Reproduces on pf/v0.2.1 also

**Comment by jordanbinskin** [comment]
Can reproduce when trying to interpolate more than one value into the name string using `RandomString` from `@pulumi/random` (v4.11.1)

**Comment by t0yv0** [comment]
@tmeckel you were kindly looking to reproduce this, is there any success? This would really help.

**Comment by tmeckel** [comment]
@t0yv0 Sorry for the delay. I applied the change using `pulumi up -r`.

**Preview**

![image](https://user-images.githubusercontent.com/14177833/223848469-d706a7f8-b59a-4b01-86c8-4a408212aa3d.png)

**Output**

![image](https://user-images.githubusercontent.com/14177833/223848711-621ef0fd-6772-4535-9c1d-fc6df10541a8.png)

Issue is that everywhere in the output you'll find the illegal default value (-1). 

Much more problematic is the fact that I know have the following error, while staring an additional `pulumi up -r`. Either this is an issue with the default values, or the used provider version 5.36.0 has a bug here. Or simply the error is completely unrelated and the stack got corrupted. Doesn't have the time yet for further investigations. I'll getting back on this tomorrow for sure.

![image](https://user-images.githubusercontent.com/14177833/223849403-1aac7608-ed26-4d69-aaf0-72554d938313.png)

**Comment by t0yv0** [comment]
Yeah that'd work! Any kind of program that I can run on my machine that hits the issue would be perfect. I can debug and root-cause it from there.

**Comment by t0yv0** [comment]
Reproduces with this:

```
import * as pulumi from "@pulumi/pulumi";
import * as random from "@pulumi/random";

export const pw = new random.RandomPassword("pw1", {length: 8})
export const pet = new random.RandomPet("pet", {separator: pw.result});
```

```
    error: objectEncoder failed on property "separator": Expected a string, got: {&{{BbAXG:}h}}}
```

Turns out the issue is data with secret bits is coming in as first-class secrets on the wire, such as this:

```
{
        "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
        "value": "supersecret"
}
```

But it confuses the objectEncoder when translating to TF.

**Comment by t0yv0** [comment]
Big thanks to  Rob Martens to helping out to pin this down --^ looking at a fix.
