### ISSUE TITLE
ReadResource return EOF!!!!!!!

### ISSUE THREAD

**Issue by LixvYang** [pulumi/pulumi-terraform-bridge#835]
### What happened?

My program wants to read the apikey data through the provider. When I pass in the parameters, it returns EOF that should not be returned.
After I debugged, I found that the code error appeared here.
[pulumi/pulumi-terraform-bridge/](https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfshim/tfplugin5/proto/tfplugin5.pb.go#L3036)

The newState in the structure returned by this function is nil AND

resp.Diagnostics is "EOF"

I don't know what happened after this grpc service call, I just know that this is not the result I should get, so what should I do to get the correct result?

### Expected Behavior

I'm expecting normal feedback results like
```


{
  "api_keys": [ 
    {
      "id": "VuaCfGcBCdbkQm-e5aOx", 
      "name": "my-api-key", 
      "creation": 1548550550158, 
      "expiration": 1548551550158, 
      "invalidated": false, 
      "username": "myuser", 
      "realm": "native1", 
      "metadata": { 
        "application": "myapp"
      },
      "role_descriptors": { }, 
      "limited_by": [  
        {
          "role-power-user": {
            "cluster": [
              "monitor"
            ],
            "indices": [
              {
                "names": [
                  "*"
                ],
                "privileges": [
                  "read"
                ],
                "allow_restricted_indices": false
              }
            ],
            "applications": [ ],
            "run_as": [ ],
            "metadata": { },
            "transient_metadata": {
              "enabled": true
            }
          }
        }
      ]
    }
  ]
}


```

### Steps to reproduce

```go
        resource := x.provider.ResourcesMap().Get(resourceName)
	state, err := resource.InstanceState(id, objectMap, meta)
	if err != nil {
		return schema.NewDiagnostics().AddError(err)
	}
	newState, err := x.provider.Refresh(resourceName, state)
	if err != nil {
		return schema.NewDiagnostics().AddError(err)
	}
````

My resource is normal. State is also a normal field, but when I call provider.Refresh, an error occurs, and the wrong return is EOF, which leads me to have no idea what happened behind it. So I expect get answers here

### Output of `pulumi about`

nil

### Additional context

nil

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Hey @LixvYang, thanks for reporting this. Which provider are you using (e.g.: AWS) and are you using the bridge directly, through Pulumi, or something else?

**Comment by mikhailshilkov** [comment]
Since we haven't heard back, I'll go ahead and close this issue as stale. Please open a new issue if the problem still persists and provide the details for us to reproduce it. Thank you!
