### ISSUE TITLE
Language chooser missing from examples

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-terraform-bridge#846]
### Problem description

The language chooser is missing for the examples on the GCP resource docs. Instead all examples are shown without indication of the language.

Examples:
- https://www.pulumi.com/docs/reference/pkg/gcp/iot/registry/
- https://www.pulumi.com/docs/reference/pkg/gcp/sql/database/

![image](https://user-images.githubusercontent.com/293763/84424663-48717400-abd5-11ea-814c-b2ac4136063d.png)

### Suggestions for a fix

Show the language chooser like other providers.

**Comment by jkodroff** [comment]
Possibly related: https://github.com/pulumi/registry/issues/2006

Would recommend checking the generated schema output for aws.ec2.Vpc when fixing this issue.

**Comment by jkodroff** [comment]
This issue also affects either some or all of the GCP IAM* resources:

https://www.pulumi.com/registry/packages/gcp/api-docs/bigquery/connectioniambinding/
https://www.pulumi.com/registry/packages/gcp/api-docs/storage/bucketiampolicy/

etc.

**Comment by lukehoban** [comment]
The original two reported issues are mostly fixed now - but still exhibit the (much less serious) issue noted in #847. 

There are several other reports of issues as well in comments, some of which are fixed, some of which are the same as #847.  I’m going to close this out - and if there are any pages that still exhibit the issue in this report - we should open new issues to track those.
