### ISSUE TITLE
aws.ec2.vpc: Examples are missing headings

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-terraform-bridge#847]
### What happened?

The VPC examples render weird in the registry.

https://www.pulumi.com/registry/packages/aws/api-docs/ec2/vpc/

VPC renders like this:

<img width="835" alt="image" src="https://user-images.githubusercontent.com/410614/215877598-b674bb54-17d2-43e5-bff9-983638b3692e.png">

But other resources render like this:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/410614/215877668-96fadc5e-fd98-422f-84ba-d68fc36986fc.png">

### Expected Behavior

n/a

### Steps to reproduce

n/a

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jazzyfresh** [comment]
pulumi-aws upgraded to tfbridge v3.40.0 on Feb 13

pulumi-aws upgraded tfbridge dependency to https://github.com/pulumi/pulumi-terraform-bridge/commit/d55a6d77f8d1 on Jan 23, just before this was originally reported ([pulumi-aws commit](https://github.com/pulumi/pulumi-aws/commit/5e7adbf5c6dfa8bb10f86e63c9f2903455da1fa4#diff-0301265a2d4321ca487bbd7ba523f69633171cef680c0114e7ca8d2c34176b73R10)):
> Override docs repo path resolution [#728](https://github.com/pulumi/pulumi-terraform-bridge/pull/728)

just a quick glance at the PR, this seems related. however this bug could have been around longer, at least we know that it was from tfbridge v3.38.1 at this sha or earlier. (disclaimer: go modules is a bit wacky, so technically this could even be from a hotfix branch off v3.38.0)

**Comment by susanev** [comment]
similar issue reported in https://github.com/pulumi/pulumi-terraform-bridge/issues/926

**Comment by lukehoban** [comment]
> similar issue reported in https://github.com/pulumi/pulumi-terraform-bridge/issues/926

Note that there do appear to be two different issues here:
1. In #847 there is a language chooser, and only the chosen language is displayed, but the language chooser is incorrectly rendered outside of the examples, instead of inside each example independently.  This is not so severe - but it inconsistent.
2. In #926 there is no language chooser at all, and all languages are shown at once, taking up lots of space and looking very broken/bad.  This is quite severe.

**Comment by iwahbe** [comment]
Fixed along with https://github.com/pulumi/pulumi-terraform-bridge/issues/926.
