### ISSUE TITLE
Downstream tests are broken, failing because of a gradle update

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-terraform-bridge#853]
### What happened?

See https://github.com/pulumi/pulumi-terraform-bridge/actions/runs/4313102089/jobs/7524480384 as an example.

### Expected Behavior

Downstream tests fail if and *only* if the bridge has a problem.

### Steps to reproduce

Look at any PR in the period.

### Output of `pulumi about`

NA

### Additional context

We should consider changing downstream tests to test known good providers, or at least known good versions of t1 providers.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Two possible fixes, pin gradle to 7.6 in the runner or update the respective providers to latest pulumi-java.
