### ISSUE TITLE
Deprecated note from terraform are lost

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi-terraform-bridge#86]
### Problem description

- I saw a product documentation issue on the following URL: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/azure/keyvault/#KeyVaultArgs-sku

The `sku` description is: 
> ) A `sku` block as described below.

On [terraform documentation](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/website/docs/r/key_vault.html.markdown#argument-reference), the `sku` description is:
> (Optional Deprecated)) A sku block as described below.

=> The deprecated note is lost
=> The extra `)` is fine because it's in terraform doc

### Affected product version(s)

latest one: 1.6.1

**Comment by justinvp** [comment]
This looks like an issue with tfgen (transferring the issue there). We don't appear to be doing anything special with the schema's `Deprecated` property.

https://github.com/terraform-providers/terraform-provider-azurerm/blob/adcea34a24de175b9e34b1e20ebc597dcfbbb3ae/azurerm/resource_arm_key_vault.go#L72

Ideally, for these, we'd also emit `@deprecated` doc comments.

@stack72, mind taking a further look?
