### ISSUE TITLE
Docsgen/Programgen: Improper Capitalization

### ISSUE THREAD

**Issue by julien-skillcorner** [pulumi/pulumi-terraform-bridge#896]
There is currently a bug in python doc generation where the inner _ is not escaped, see: https://github.com/pulumi/pulumi-aws/pull/2347#discussion_r1095157137

For an example, check out this error: There is a typo in Python example using lambda attribute instead of lambda_

File: [themes/default/content/registry/packages/aws/api-docs/lambda/getfunction/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/lambda/getfunction/)

**Comment by Frassle** [comment]
Testing the raw python schemagen and programgen I can't reproduce these issues so it looks like this is specific to the fixups tfgen does to schemas per-language.
