### ISSUE TITLE
Creating resources calls Diff with nil InstanceState causing behavior divergent from Terraform

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#911]
### What happened?

Original issue: https://github.com/pulumi/pulumi-aiven/issues/274

In `func (p *Provider) Create` Pulumi  performs this call, notice the nil:

```go
	diff, err := p.tf.Diff(res.TFName, nil, config)
```

The call ultimately resolves to a method in terraform-plugin-sdk/v2, which is similar to what happens in Terraform.

```
func (r *Resource) SimpleDiff(
	ctx context.Context,
	s *terraform.InstanceState,
	c *terraform.ResourceConfig,
	meta interface{}) (*terraform.InstanceDiff, error) {
```

Unfortunately there is a discrepancy: in Terraform `s` is populated, even on Create, in particular  s.RawConfig, s.RawState, and s.RawPlan are populated, while in Pulumi s is `nil`.

The code responsible for populating this is the PlanResourceChange method, which backs both Create and Update changes in TF:

https://github.com/pulumi/terraform-plugin-sdk/blob/430f685de305a148a5a79d1c3959ecf109986675/helper/schema/grpc_provider.go#L662-#L662

Now the discrepancy means that CustomizeDiff functions do not see the right data, and may even panic as is the case of aiven bug in https://github.com/pulumi/pulumi-aiven/issues/274, and generally this might result in diff behavior that's different from what Terraform intends to do and therefore confusing.

We already have some feature-flagged (DiffStrategy=PlanState) work that tries to adjust the way bridged Pulumi providers compute Diffs to bring it more in line with Terraform PlanResourceChange behavior, but turning this feature on currently does not resolve the problem. It appears that the fix to this issue logically belongs to DiffStrategy=PlanState and should go out under the same flag.

### Expected Behavior

CustomizeDiff behaves similarly to Terraform.

### Steps to reproduce

See https://github.com/pulumi/pulumi-aiven/issues/274

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Fixed with PlanResourceChange
