### ISSUE TITLE
PluginFramework providers don't implement the mapping system

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi-terraform-bridge#915]
Noticed this with the random provider.

Since moving to the plugin framework the random provider no longer implements -get-provider-info (legacy system used by tfconvert) or GetMapping (new system used by pulumi convert).

We're working around this with manual mapping overrides that the new system supports and an old copy of the provider info from 4.10, but this is not a good experience for end users.

**Comment by t0yv0** [comment]
Closing as duplicate. https://github.com/pulumi/pulumi-terraform-bridge/issues/819
