### ISSUE TITLE
[Plugin Framework] IgnoreChanges only applies to Diff

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-terraform-bridge#920]
### What happened?

I noticed that `ignoreChanges` only applies for diffs. Once an `update` is desired, `ignoreChanges` no longer takes effect.

### Expected Behavior

We should see the following

Initial:
```ts
import * as pulumi from "@pulumi/pulumi";
import * as random from "@pulumi/random";

const a = new random.RandomInteger(
    "ri",
    {min: 1, max: 10},
    {ignoreChanges: ["min"]}
)
```
With state `{min: 1, max: 10}`

---

Transition 1:
```ts
import * as pulumi from "@pulumi/pulumi";
import * as random from "@pulumi/random";

const a = new random.RandomInteger(
    "ri",
    {min: 2, max: 10},
    {ignoreChanges: ["min"]}
)
```
With state: `{min: 1, max: 10}` (no change)

---

Transition 2:
```ts
import * as pulumi from "@pulumi/pulumi";
import * as random from "@pulumi/random";

const a = new random.RandomInteger(
    "ri",
    {min: 2, max: 20},
    {ignoreChanges: ["min"]}
)
```
With state: `{min: 1, max: 20}`

### Steps to reproduce

What we actually get is a final state (see Expected Behavior) of `{min: 2, max: 20}`. This is wrong. 

### Output of `pulumi about`

Bridge version v3.42.1 (pf version [v0.6.0](https://github.com/pulumi/pulumi-terraform-bridge/releases/tag/pf%2Fv0.6.0))

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Thank you! Looks like a miss in Plugin Framework version.

**Comment by t0yv0** [comment]
Miss in https://github.com/pulumi/pulumi-terraform-bridge/pull/816/files#diff-2c37089dfedf96709058079a9bcd887d58733edb7658fc06da48a90af693fd91
