### ISSUE TITLE
bug: Terraform Bridge does not reliably perform Terraform state upgrades

### ISSUE THREAD

**Issue by tmeckel** [pulumi/pulumi-terraform-bridge#923]
@t0yv0 Found the issue. Inside the Pulumi stack the resource id is lower case on the `webHooks` element:

`/subscriptions/e5116c25-7bc9-4e96-9c3e-88257f68db7c/resourceGroups/RG-WKB-Test/providers/Microsoft.ContainerRegistry/registries/acr4189bf944305c36f/webhooks/b1ec43f3ce50aab6`

![image](https://user-images.githubusercontent.com/14177833/228552242-9fdf7029-8f8e-4889-9e01-804f5d6614e7.png)

The parser inside the AzureRM Provider expects `webHooks`:

![image](https://user-images.githubusercontent.com/14177833/228552014-cd7a0e8b-61ea-4fdf-9ca6-158d40d727ec.png)

The team introduced the change with:

https://github.com/hashicorp/terraform-provider-azurerm/commit/821ea0a145254b3c2bfed79bd4e331c499f6ae45
https://github.com/hashicorp/terraform-provider-azurerm/pull/19507

No issue when using Terraform,  because the team added a (silent) state migration.

![image](https://user-images.githubusercontent.com/14177833/228553289-136c85c5-4afe-497f-8b70-cfa35352f488.png)

Pulumi isn't aware of state migrations because it handles the state on it's own. But in such cases this is a real problem, because in the current case, I've to update the Pulumi state manually and correct the casing from `webhooks` to `webHooks`.

_Originally posted by @tmeckel in https://github.com/pulumi/pulumi-terraform-bridge/issues/720#issuecomment-1488617011_
            
Affected versions: Upgrade from Azure Classic 5.16.0 to 5.38.0

**Steps to reproduce:**

1. Deploy Azure Container Registry with a WebHook using 5.16.0
2. Upgrade to Version 5.38.0
3. Try to change the infrastructure (e.g. add a Storage Account). `pulumi pre -r` will show an error about a the missing `webHooks` element.

**Comment by t0yv0** [comment]
Thank you for working out another possible root cause of problem here!
