### ISSUE TITLE
Language chooser is missing on Registry docs pages

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-terraform-bridge#926]
### What happened?

https://www.pulumi.com/registry/packages/aws/api-docs/sqs/queue/

<img width="821" alt="image" src="https://user-images.githubusercontent.com/410614/228618539-14c4ccaa-dc9e-4981-9b6c-686d696eec76.png">

I haven't independently verified that the issue is definitely in the provider schema but past experience indicates it probably is.

### Expected Behavior

Language chooser is present

### Steps to reproduce

n/a

### Output of `pulumi about`

n/a

### Additional context

We addressed this for many resources in https://github.com/pulumi/pulumi-terraform-bridge/issues/846, but it looks like we'll need another round of improvements to the parsing logic.

I suggest that we keep a single comment at the top of this issue with all affected pages to make testing a fix easier, and maybe include a list of pages to regression test since reading the diff of pulumi-aws is gonna be impossible for a human.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
Also broken on:
* https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/ (one of the most viewed pages in the entire registry).
* https://www.pulumi.com/registry/packages/aws/api-docs/cloudwatch/metricalarm/
* https://www.pulumi.com/registry/packages/aws/api-docs/sns/topic/
* https://www.pulumi.com/registry/packages/aws/api-docs/lambda/permission/

**Comment by sean1588** [comment]
will likely be resolved by - https://github.com/pulumi/pulumi-aws/issues/2624

**Comment by jkodroff** [comment]
Another presumably popular page with the issue: https://www.pulumi.com/registry/packages/aws/api-docs/eks/addon/

**Comment by sean1588** [comment]
some instances of this issue may also be related to: https://github.com/pulumi/pulumi/issues/15506

**Comment by sean1588** [comment]
Looks like all of these are now resolved with the merging of https://github.com/pulumi/pulumi-terraform-bridge/pull/1689. Thanks so much @guineveresaenger 🎉 



![Image](https://github.com/pulumi/pulumi-terraform-bridge/assets/16751381/3e84cb4a-fb4e-423d-9412-af4a72a45458)
