### ISSUE TITLE
Convert terraform-aws-github-runner

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-terraform-bridge#945]
Remaining work items for converting https://github.com/philips-labs/terraform-aws-github-runner

## Error

Hitting the following when trying to convert to TS:

```
pulumi convert --from terraform --language typescript --out pulumi
warning: Plugin converters are currently experimental
        error: main.pp:104,1-146,2: main.pp:2,42-48: undefined variable module; , and 3 other diagnostic(s); main.pp:2,42-48: undefined variable module; , and 3 other diagnostic(s)
        error: main.pp:237,1-270,2: main.pp:30,11-36,5: cannot assign expression of type list({
          applyServerSideEncryptionByDefault: list({
            kmsMasterKeyId: dynamic,
            sseAlgorithm: dynamic?,
          }),
          bucketKeyEnabled: dynamic,
        }) to location of type   list(  {
              applyServerSideEncryptionByDefault:   {
                  kmsMasterKeyId: output(string) | string?,
                  sseAlgorithm: output(string) | string,
                }
              | output({
                  kmsMasterKeyId: string?,
                  sseAlgorithm: string,
                })?,
              bucketKeyEnabled: bool | output(bool)?,
            }
          | output({
              applyServerSideEncryptionByDefault:   {
                  kmsMasterKeyId: string?,
                  sseAlgorithm: string,
                }?,
              bucketKeyEnabled: bool?,
            }))
        | output(list({
            applyServerSideEncryptionByDefault:   {
                kmsMasterKeyId: string?,
                sseAlgorithm: string,
              }?,
            bucketKeyEnabled: bool?,
          })): ; , and 7 other diagnostic(s); main.pp:30,11-36,5: cannot assign expression of type list({
          applyServerSideEncryptionByDefault: list({
            kmsMasterKeyId: dynamic,
            sseAlgorithm: dynamic?,
          }),
          bucketKeyEnabled: dynamic,
        }) to location of type   list(  {
              applyServerSideEncryptionByDefault:   {
                  kmsMasterKeyId: output(string) | string?,
                  sseAlgorithm: output(string) | string,
                }
              | output({
                  kmsMasterKeyId: string?,
                  sseAlgorithm: string,
                })?,
              bucketKeyEnabled: bool | output(bool)?,
            }
          | output({
              applyServerSideEncryptionByDefault:   {
                  kmsMasterKeyId: string?,
                  sseAlgorithm: string,
                }?,
              bucketKeyEnabled: bool?,
            }))
        | output(list({
            applyServerSideEncryptionByDefault:   {
                kmsMasterKeyId: string?,
                sseAlgorithm: string,
              }?,
            bucketKeyEnabled: bool?,
          })): ; , and 7 other diagnostic(s)
        error: main.pp:147,1-236,2: main.pp:48,21-50,5: cannot assign expression of type list({ instanceMetadataTags: string }) to location of type   {
            httpEndpoint: output(string) | string?,
            httpProtocolIpv6: output(string) | string?,
            httpPutResponseHopLimit: int | output(int)?,
            httpTokens: output(string) | string?,
            instanceMetadataTags: output(string) | string?,
          }
        | output({
            httpEndpoint: string?,
            httpProtocolIpv6: string?,
            httpPutResponseHopLimit: int?,
            httpTokens: string?,
            instanceMetadataTags: string?,
          })?: ; , and 15 other diagnostic(s); main.pp:48,21-50,5: cannot assign expression of type list({ instanceMetadataTags: string }) to location of type   {
            httpEndpoint: output(string) | string?,
            httpProtocolIpv6: output(string) | string?,
            httpPutResponseHopLimit: int | output(int)?,
            httpTokens: output(string) | string?,
            instanceMetadataTags: output(string) | string?,
          }
        | output({
            httpEndpoint: string?,
            httpProtocolIpv6: string?,
            httpPutResponseHopLimit: int?,
            httpTokens: string?,
            instanceMetadataTags: string?,
          })?: ; , and 15 other diagnostic(s)
        error: could not generate output program: failed to bind program
```

## Demo

- [x] https://github.com/pulumi/pulumi-terraform-bridge/pull/952, https://github.com/pulumi/pulumi-terraform-bridge/pull/962
- [x] https://github.com/pulumi/pulumi-terraform-bridge/pull/966
- [x] panic in GetTraversableType
     - [x] Making things dynamic. We need strict mode and non-strict mode in the binder.
- [x] naming: _very_ inconsistent (and incorrect) about changing variable/field names from snake_case to camelCase (config blocks)
    - [x] default config objects have inconsistent names 
 

## Full conversion

- [ ] not maintaining output descriptions from TF -> PCL
- [ ] tf-to-pulumi type mappings not deterministic: need to run `pulumi convert` multiple times to get a good result
- [ ] notImplemented
     - [ ] notImplemented("merge(var.tags,{\n\"ghr:environment\"=var.prefix\n})")
     - [ ] notImplemented("try(aws_sqs_queue.webhook_events_workflow_job_queue[0],null)")
     - [ ] notImplemented("templatefile(\"$${path.module}/policies/lambda-kms.json\",{\nkms_key_arn=var.server_side_encryption_configuration.rule.apply_server_side_encryption_by_default.kms_master_key_id\n})")
     - [ ] notImplemented("distinct([forlinlocal.logfiles:l.log_group_name])")
     - [ ] notImplemented("coalesce(var.ami_filter,local.default_ami[var.runner_os])")
     - [ ] notImplemented("compact(concat(\nvar.enable_managed_runner_security_group?[aws_security_group.runner_sg[0].id]:[],\nvar.runner_additional_security_group_ids,\n))"
- [ ] no validation for PCL variables (we're probably ok dropping this for now)
- [ ] no translation of terraform provider version ranges to pulumi versions
	- Do we need mappings to tell us this as well as the provider name? That feels painful to keep in sync.

**Comment by justinvp** [comment]
@AaronFriel, where would you prefer the epic and issues to live? All the actual converter code where the changes for this will be made lives in this repo. But I guess we could open the issues in the converter plug-in repo. I’d prefer to move off tf2pulumi repo as that tool and repo will be deprecated in the coming weeks.

**Comment by AaronFriel** [comment]
@justinvp I don't think it matters to me, if the code will live in this repository it makes sense to be here. If it's multi-repo, as I think the codegen work for the converter is, this is fine. Should we have an assignee on this and put it on a board?

**Comment by Zaid-Ajaj** [comment]
Since the example is now converting, will closing this issue. I've opened issues to track other problems we have encountered
 - https://github.com/pulumi/pulumi-converter-terraform/issues/19
 - https://github.com/pulumi/pulumi-converter-terraform/issues/18
 - https://github.com/pulumi/pulumi-converter-terraform/issues/16
 - https://github.com/pulumi/pulumi-converter-terraform/issues/17
