### ISSUE TITLE
Support parsing PULUMI_CONFIG for provider configuration overrides

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#955]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Consider supporting parsing PULUMI_CONFIG environment variable during Configure call. Any properties defined in the JSON struct at that variable should override missing configuration properties for the provider, therefore allowing the provider to be configured from the environment variable.

Related feature: 

[PR in pulumi/pulumi](https://github.com/pulumi/pulumi/pull/12605)

Clarification: this work is not changing default provider behavior in any of Pulumi providers but enables an opt-in behavior that works around issues for a customer.

**Comment by justinvp** [comment]
We should discuss before adopting this in any of our providers. cc: @Frassle

**Comment by t0yv0** [comment]
We're converging on some less intrusive options with @lblackstone  https://github.com/pulumi/pulumi-terraform-bridge/pull/991  (thanks @AaronFriel for suggesting to look into PreConfigureCallback).

**Comment by AaronFriel** [comment]
I think @iwahbe observed that we had that callback
