### ISSUE TITLE
Handling upgrade guides and breaking changes in changelogs

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-terraform-bridge#965]
on the cloudflare package, we recently shipped a major version change.

https://github.com/pulumi/pulumi-cloudflare/releases/tag/v5.0.0

it’s look like schematool(?) found some breaking changes, but there were more in the tf provider:

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/guides/version-4-upgrade
Couple questions:

as an end user, how would I know about this upgrade guide? Can we docgen it?
how can we get these into the changelogs?

**Comment by iwahbe** [comment]
Related to https://github.com/pulumi/schema-tools/issues/24

**Comment by jazzyfresh** [comment]
So far, any breaking changes such as mentioned in [the v5.0.0 cloudflare release](https://github.com/pulumi/pulumi-cloudflare/releases/tag/v5.0.0), are updated manually. However, we would like automation this. The generated breaking changes from github-actions bot [here](https://github.com/pulumi/pulumi-cloudflare/pull/364#issuecomment-1466240208) , we want to incorporate those into the changelog produced for a release. This will be tracked in https://github.com/pulumi/schema-tools/issues/24
