### ISSUE TITLE
Convert: External module support

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-terraform-bridge#976]
- [x] Implementation
- [x] Tests

**Comment by jazzyfresh** [comment]
adding to Platform project board

**Comment by Frassle** [comment]
This is done on the experimental branch, tests at https://github.com/pulumi/pulumi-terraform-bridge/pull/677/files#diff-68ba710d73f65e1e2485ac9085e68f092608d26e4d0eff34ee592675897dcf9c
